### ISSUE TITLE
NASA BlueMarble tiles have become blank

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#1000]
In the [The Gallery of Basemaps](https://datalore.jetbrains.com/report/static/HZqq77cegYd.E7get_WnChZ/05NSsbcsOYZMBN9n4JfKzL) demo I see "Fail to fetch" for the NASA GIBS BlueMarble_NextGeneration tileset. The developer console is showing the 500 error code.

This has been going on for about a month now, and other tilesets from NASA are working fine.

**Comment by alshan** [comment]
@IKupriyanov-HORIS have we removed NASA BlueMarble from API yet?

**Comment by IKupriyanov-HORIS** [comment]
> have we removed NASA BlueMarble from API yet?
It's still here. I'll remove it.
