### ISSUE TITLE
Ticks for `scale_x_continuous` with date format are off by 1

### ISSUE THREAD

**Issue by david-cortes** [JetBrains/lets-plot#1003]
If I create a line plot where a datetime variable uses `scale_x_continuous` with a date format specifier, the axis ticks will be placed at wrong places (off by 1).

For example, suppose I create the following series:
```python
import numpy as np, pandas as pd
df = pd.DataFrame({
    "Month" : pd.date_range("2021-07-01", periods=18, freq="ME").to_period("M").to_timestamp(),
    "Value" : np.arange(18)
})
df
```
```
Month	Value
0	2021-07-01	0
1	2021-08-01	1
2	2021-09-01	2
3	2021-10-01	3
4	2021-11-01	4
5	2021-12-01	5
6	2022-01-01	6
7	2022-02-01	7
8	2022-03-01	8
9	2022-04-01	9
10	2022-05-01	10
11	2022-06-01	11
12	2022-07-01	12
13	2022-08-01	13
14	2022-09-01	14
15	2022-10-01	15
16	2022-11-01	16
17	2022-12-01	17
```

**Notice for example that the value for December 2021 is 5.**

The following plot howevers puts the mark for December 2021 closer to '6':
```python
import lets_plot as g
g.LetsPlot.setup_html()
(
    g.ggplot(df, g.aes(x="Month", y="Value"))
    + g.geom_line()
    + g.scale_x_continuous(format="%b %Y")
)
```
![image](https://github.com/JetBrains/lets-plot/assets/11860098/5121ee0b-ccba-48f0-b999-28e79abd6edd)

Note that if I hover the mouse exactly over the Dec2021 mark, it will actually show a 6:
![image](https://github.com/JetBrains/lets-plot/assets/11860098/787ade1c-ef4a-48e5-8438-b55872e54129)

Compare against the following which correctly places the Dec2021 mark at 5:
```python
(
    g.ggplot(df, g.aes(x="Month", y="Value"))
    + g.geom_line()
    + g.scale_x_datetime(format="%b %Y")
)
```
![image](https://github.com/JetBrains/lets-plot/assets/11860098/b807e09c-e492-4a28-940e-15381fabfbb0)

**Comment by alshan** [comment]
Hi David, for this kind of data you have to use "datetime" scale because it knows that the data values actually are encoded date-time values and takes this in account when computing its breaks.

In contrast to this, "continuous" scale computes its breaks "thinking" that numbers are just numbers. Thus, automatic breaks could be any values, not necessary aligned to a 1st day of a moth. You can see the resulting breaks better if you apply more detailed formatting - with days, hours etc.

**Comment by david-cortes** [comment]
> Hi David, for this kind of data you have to use "datetime" scale because it knows that the data values actually are encoded date-time values and takes this in account when computing its breaks.
> 
> In contrast to this, "continuous" scale computes its breaks "thinking" that numbers are just numbers. Thus, automatic breaks could be any values, not necessary aligned to a 1st day of a moth. You can see the resulting breaks better if you apply more detailed formatting - with days, hours etc.

Still, the x-axis tick does not correspond to the correct y value - in the first plot, the x-axis tick intersects the y axis close to 6, while it should intersect it at 5, so the actual value that the tick represents is a bit to the left of it.

**Comment by alshan** [comment]
No follow up questions. Supposedly not an issue any longer.
