### ISSUE TITLE
Interactive pan, selected zoom and autoscale

### ISSUE THREAD

**Issue by maxkrivobok** [JetBrains/lets-plot#1019]
Hi! 
Plotly charts offer several interactive features that **_could greatly benefit lets-plot_**. These include:
**1. Panning:**
Users can click and drag the canvas to adjust the chart's view to their preference.
**2. Selected Zoom:**
Enabling users to choose a specific area of the chart for zooming, ensuring the selection fits within the chart dimensions.
**3. Autoscale:**
A click-triggered function that automatically adjusts the chart to its original dimensions.

**Comment by alshan** [comment]
Pan, zoom, double-click : see  [4.5.0](https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-450)
