### ISSUE TITLE
`alpha` aesthetic mapping not functioning as expected for `geom_label()`?

### ISSUE THREAD

**Issue by OSuwaidi** [JetBrains/lets-plot#1029]
The `alpha` aesthetic mapping only applies against the fill aesthetic of `geom_label()` not its color, hence the transparency effect is **only** visible if the color is manually set to "white".

Here's an example (taken from [here](https://lets-plot.org/python/pages/api/lets_plot.geom_label.html#lets_plot.geom_label)):
```
import numpy as np
from lets_plot import *
LetsPlot.setup_html()
n = 10
np.random.seed(42)
x = np.arange(n)
y = np.random.normal(loc=10, scale=2, size=n)
df = pl.DataFrame({"x": x, "y": y}).with_columns(pl.when(pl.col('y') > 10).then(pl.lit(1)).otherwise(pl.lit(0)).alias('alpha'))

(ggplot(df, aes(x='x', y='y', alpha='alpha')) +
    geom_bar(stat='identity', fill='#2b8cbe', tooltips='none') +
    geom_label(aes(label='y'), position=position_nudge(y=1),
              label_format='.1f', fill='#2b8cbe', color='white')
+ guides(alpha='none'))
```
which works as expected and produces:
<img src=https://github.com/JetBrains/lets-plot/assets/120381151/98269e5b-938c-419c-a777-a39c0272ccb9  width="500" height="300">

However, if you were to remove the `color='white'` property from `geom_label()` above, the color of the labels doesn't actually become less transparent (it seems like its just losing its fill saturation color):
<img src=https://github.com/JetBrains/lets-plot/assets/120381151/aeeb9e97-28d6-47f7-a61d-a6a630d0f313  width="500" height="300">

Additionally, if you were to remove the custom `fill='#2b8cbe'` property as well, then you see that the alpha aesthetic doesn't even get applied:
<img src=https://github.com/JetBrains/lets-plot/assets/120381151/4dbe0d49-649b-4513-89da-295a1f2c5153  width="500" height="300">

And to showcase how they're still visible (but fill is less saturated):
```
(ggplot(df, aes(x='x', y='y', alpha='alpha', fill=as_discrete('x'))) + 
    geom_bar(stat='identity', tooltips='none') +
    geom_label(aes(label='y'), nudge_y=1, label_format='.1f')
    + guides(alpha='none', fill='none'))
```
<img src=https://github.com/JetBrains/lets-plot/assets/120381151/79f7fcf1-106f-4bbd-b9d6-22dc2120a311  width="500" height="300">

And in my actual case, I have something like this:
```
import numpy as np
from lets_plot import *
from lets_plot.mapping import as_discrete
LetsPlot.setup_html()
n = 10
np.random.seed(42)
data = {
    'x': np.random.normal(size=n),
    'y': np.random.normal(size=n),
    'c': np.random.choice(list('abc'), size=n),
}
df = pl.DataFrame(data).with_columns(pl.when(pl.col('x') > 0.5).then(pl.lit(1)).otherwise(pl.lit(0.1)).alias('alpha'))

(ggplot(df, aes('x', 'y', color='c', alpha='alpha')) +
    geom_point()
    + geom_label(aes(label='y'), label_format='{.1f}', vjust=0, hjust=1, nudge_y=0.05)
    + guides(color='none', alpha='none')
)
```
<img src=https://github.com/JetBrains/lets-plot/assets/120381151/3e5c3af0-aabd-4418-b998-511a5298807a  width="500" height="300">

Which made me question why my labels aren't being transparent and had to debug this mystery for a long time (since replacing `geom_label()` with `geom_text()` works just fine)!

**Comment by OLarionova-HORIS** [comment]
This is the original behaviour of `geom_label()`:
alpha is applied to the background, but not to the text and border of the label.
For geom_text() - yes, alpha affects the text transparency.
Same issue with ggplot2 example : https://github.com/JetBrains/lets-plot/issues/753

**Comment by OSuwaidi** [comment]
Interesting,

But this approach would render the default behavior of `geom_label()` incompatible with the alpha aesthetic (`aes`). And in my case, I haven't specified a fill aesthetic, but rather a color aesthetic. As a result, the labels remain visible (even though I believe the alpha `aes` can still be applied to white fill objects, you can see that if white fill a bar plot).

So:
1. the color of the `geom_label()` must always match the color of the plot's background for alpha to make sense
2. `geom_label()` must always have a non-white fill `aes` specified since alpha only applies to it

?

**Comment by OLarionova-HORIS** [comment]
We will add an alpha toggle flag for `geom_label()`: with it, alpha will also be applied to the label text and border.
This should help - [example](https://nbviewer.org/github/JetBrains/lets-plot/blob/021e637dbc5f8a6dd0e2d3d52a38873469ca24a9/docs/f-24a/geom_label_alpha_stroke.ipynb)

**Comment by OSuwaidi** [comment]
@OLarionova-HORIS yes, that sounds like a great idea and easy to implement! 🚀

**Comment by alshan** [comment]
See `alpha_stroke=True` : https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-24a/geom_label_alpha_stroke.ipynb
