### ISSUE TITLE
arrow on segment: reduce arrow size for short segments

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#1040]
<img width="138" alt="image" src="https://github.com/JetBrains/lets-plot/assets/4430922/74864660-5360-4e9b-85fb-75be236b3535">

**Comment by IKupriyanov-HORIS** [comment]
Fixed via https://github.com/JetBrains/lets-plot/commit/c82651f1f96ec90af9bd7f701149083d8fd5d295.

Added new parameter `min_tail_length` to the `arrow()` function. 
With the value `min_tail_length=15` result is the following:
![image](https://github.com/JetBrains/lets-plot/assets/14200189/bae14be2-ad86-4c09-be71-67997fcafd35)
