### ISSUE TITLE
arrow on curve sometimes looks weird. 

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#1041]
<img width="271" alt="image" src="https://github.com/JetBrains/lets-plot/assets/4430922/b56109d5-654a-4b9c-aa6f-c57b2f93f69d">

All data and plot from here: https://aeturrell.github.io/coding-for-economists/vis-common-plots.html#connected-scatter-plot

**Comment by alshan** [comment]
Not suggesting to do like here: 
<img width="62" alt="image" src="https://github.com/JetBrains/lets-plot/assets/4430922/50d62a47-3661-49c5-8e7f-c08f0d7c4ba2">
but, maybe )
https://graphicdesign.stackexchange.com/questions/101996/arrow-head-brush-distorted-on-a-curved-path

**Comment by IKupriyanov-HORIS** [comment]
Fixed via https://github.com/JetBrains/lets-plot/commit/c82651f1f96ec90af9bd7f701149083d8fd5d295.

Adjusted arrow head angle calculation logic.
How it looks now:
![image](https://github.com/JetBrains/lets-plot/assets/14200189/a50ee703-78e3-4100-b7ed-1f1ee27f4ec3)
