### ISSUE TITLE
Assigning same alpha value to all datapoints causes unnecessary transparency

### ISSUE THREAD

**Issue by OSuwaidi** [JetBrains/lets-plot#1042]
I have a numeric column (`z`) that serves as the alpha value for each data point.

Initially, the alpha value is the same (`1`) for all data points (no emphasis on any):
```
import numpy as np
from lets_plot import *

LetsPlot.setup_html()


x = np.arange(1, 10)
y = x[::-1]
z = [1] * len(x)
data = {'x': x, 'y': y, 'z': z}

(ggplot(data, aes(x='x', y='y', alpha='z'))
    + geom_bar(stat='identity', fill='#2b8cbe', tooltips='none')
    + guides(alpha='none') 
    + geom_label(aes(label='y'), nudge_y=1, label_format='.1f', fill='#2b8cbe')
    )
```
The expected result is that there is no transparency effect, since they're all set to be the same value and equaling 1.

But this is what you get:
<img width="600" alt="Screenshot 2024-03-11 at 10 59 34 AM" src="https://github.com/JetBrains/lets-plot/assets/120381151/7afe9eda-a7e0-4d94-85ed-37836bc54ac2">

Compared to setting `alpha=1` outside the `aes` property (default):
<img width="592" alt="Screenshot 2024-03-11 at 10 59 47 AM" src="https://github.com/JetBrains/lets-plot/assets/120381151/dbc02c4c-073f-4703-a7a1-5e6a8b915898">

As a side note, no matter that the value of `z` is, it will always result in the same outcome. Up until you change one of the values to be different, (e.g., `z[0] = 0.9`), then things behave normally. Though it's still weird because the first bar now becomes very transparent (even though its alpha is 0.9), and no matter what its value, it will still be very transparent.

**Comment by alshan** [comment]
Hi, in this case you need to add `scale_alpha_identity()` because your intention is to apply data values directly to alpha values without any scaling or transformation.

**Comment by OSuwaidi** [comment]
Hey @alshan, thanks for your usual assistance 🎩 !

Adding  `scale_alpha_identity()` works perfect; but... I don't understand why is it not the default behavior? Why is it necessary to add this function `scale_alpha_identity()`?

I understand that `scale_alpha()` is used to customize and format the alpha `aes`'s legend, but why isn't the default behavior of providing custom alpha values via a column be `scale_alpha_identity()`?

Thanks!

**Comment by alshan** [comment]
Hi @OSuwaidi,

The general function of a scale is to map values in the data domain to values in the aesthetic domain. In the case of `alpha`, the aesthetic domain is a numeric range [0..1].

`scale_alpha_identity()` doesn't change data values, presuming that the data domain is equal to that of the `alpha` aesthetic. 
While this might be true in some cases, it's not a universal rule. Therefore, `scale_alpha_identity()` wouldn't be a good default choice.

**Comment by OSuwaidi** [comment]
@alshan wonderful, crystal clear, very much appreciated❗
