### ISSUE TITLE
Livemap: labels on the map look blurry

### ISSUE THREAD

**Issue by INekrasova-HORIS** [JetBrains/lets-plot#1045]
Livemap: labels on the map look blurry

![livemap](https://github.com/JetBrains/lets-plot/assets/73931962/6023ee8e-ff41-4d65-a927-81f1d0b0d44a)

**Comment by IKupriyanov-HORIS** [comment]
Blurry text is fixed for default and zoomed browser window.
Also fixed gaps between tiles on a zoomed window.

Screenshot taken from a Chrome with a 110% zoom:
![Screenshot from 2024-04-17 20-15-33](https://github.com/JetBrains/lets-plot/assets/14200189/01e1a474-dcff-47a9-9877-fd055b128b47)
