### ISSUE TITLE
Incorrect position for bar annotations when specifying `scale_x_reverse()`/`scale_y_reverse()`

### ISSUE THREAD

**Issue by INekrasova-HORIS** [JetBrains/lets-plot#1057]
Incorrect position for bar annotations when specifying `scale_x_reverse()`/`scale_y_reverse()`
```
import pandas as pd
from lets_plot import *
LetsPlot.setup_html()

mpg_df = pd.read_csv ("https://raw.githubusercontent.com/JetBrains/lets-plot-docs/master/data/mpg.csv")

p = ggplot(mpg_df) + geom_bar(aes("trans"),labels=layer_labels().line('@..count..')) 
p
```

The default position of the annotations is at the base of the bars.
![image](https://github.com/JetBrains/lets-plot/assets/73931962/246b5dbe-3e85-4e54-9cf3-414fa8803220)

```
p + scale_y_reverse()
```
When specifying the `scale_y_reverse()` annotations are at the top.

![image](https://github.com/JetBrains/lets-plot/assets/73931962/8a88c61f-7d90-43f9-8aa0-d5d80cf6415d)

**Comment by OLarionova-HORIS** [comment]
Fixed via https://github.com/JetBrains/lets-plot/commit/a84afe622f7909d18449b14d17c7e408d738a0af
