### ISSUE TITLE
Weird and problematic behavior : lets-plot does not respect x and y. Sizing problem ?

### ISSUE THREAD

**Issue by egayer** [JetBrains/lets-plot#1068]
Hi,
I am preparing plots for publication and encountering a particularly problematic behavior: `geom_path`, `geom_line`, `geom_ribbon`, and `geom_area_ridges` do not respect the x and y values when creating a step plot. Lets-plot seems to skip points as if trying to smooth the step plot. It appears that the issue is related to the ratio of width to height.

Please find attached some data and the code to reproduce the image attached, which illustrates the discrepancy between the expected result and the actual output. However, playing with `ggsize()` will help you understand why this becomes a serious problem when it comes to publication-ready plots. The problem may worsen with more data, which I am unable to provide here.

For the image : In red rectangles. In blue line connecting the x and y of each upper corner of the rectangles. For the narrower rectangles, the blue line does not stay flat.

[LineProblem.zip](https://github.com/JetBrains/lets-plot/files/14779270/LineProblem.zip)
![im](https://github.com/JetBrains/lets-plot/assets/14859142/ceadbb3f-854c-4c00-925d-d4fbcbb22180)

**Comment by IKupriyanov-HORIS** [comment]
Hello!
I see the problem. Path-like geoms use geometry simplification after the introduction of the polar coordinate system, but unfortunately this functionality also slept into a cartesian system, and there is no way to control this behaviour.

But I can suggest to use `geom_step()` as it does not trigger the simplification.
On your data I see proper steps with it:
![image](https://github.com/JetBrains/lets-plot/assets/14200189/b8c75483-aaee-4175-be30-f8c64d11b4a0)
