### ISSUE TITLE
Add a compact format of scientific notation (new symbol, not a regular 'e')

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/lets-plot#1071]
`1*10^0` -> `1`
`1*10^1` -> `10`
`1*10^2` -> `10^2`

**Comment by alshan** [comment]
We can cover #1 and #2 by adding settings similar to [powerlimits](https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.ScalarFormatter.set_powerlimits) in Matplotlib (and not just powers of 10 in this case).

As for #3, we can support 3rd option for the `exponent_format` parameter in `theme`:
- 'e' - regular "e" notation
- 'pow' - compact superscript
- 'pow_full' - superscript without shortening

----
If, in addition to str, the `exponent_format` parameter could accept a tuple/array : (format, min_exp, max_exp), that would work IMO.

**Comment by alshan** [comment]
Added in [v4.5.0](https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-450)
