### ISSUE TITLE
The GeoJson structure breaks if the ring start label occurs several times

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/lets-plot#1086]
Note that [0, 0] appears twice in a row. Without this duplication, the geometry would be parsed correctly:
```python
from lets_plot import *
import geopandas as gp

LetsPlot.setup_html()

d = gp.read_file("""
{"type":"MultiPolygon","coordinates":
    [
      [
        [
          [0,0], [0,0], [0, 5], [5, 5], [5, 0], [0, 0]
        ]
      ],
      [
        [
          [10, 10],[10, 20],[20, 20],[20, 10],[10, 10]
        ]
      ]
    ]
}""")

ggplot() + geom_polygon(map=d) + coord_fixed()
```
Actual:
![image](https://github.com/JetBrains/lets-plot/assets/14200189/58c5caa6-c99f-47b9-b6d3-8770ed805d1d)

Expected result:
```python
d.plot()
```
![image](https://github.com/JetBrains/lets-plot/assets/14200189/38dd0298-7e80-4108-845e-1ce1a27ccbb3)

**Comment by RYangazov** [comment]
Fixed via d5c2cf3d04db02251763a0d8a4b26aff2a5a0093
