### ISSUE TITLE
Interactive links in tooltipss/labels/texts

### ISSUE THREAD

**Issue by pvinokurov** [JetBrains/lets-plot#1091]
It would be nice to have interactive links in labels/texts for page anchors or external links.

**Comment by pvinokurov** [comment]
For example:
<pre>
plot{
    points {
        x(cityName)
        y(population)
        
        tooltips(link(href="#{cityName}")) 
    }
}
</pre>

**Comment by alshan** [comment]
"In the latest release of Grafana (version 8.5.0), there has been a change in the behavior of tooltips. Previously, tooltips would remain open until manually closed, but now they will close automatically when you move your mouse away from the trigger element. "
~ Grafana Grot )

Anyway, how do tooltips trigger in Grafana ? Mouse hover? click?

**Comment by pvinokurov** [comment]
Lets take a look at https://play.grafana.org/d/000000016/time-series-graphs
In my opinion, it's convenient enough. Copying a tooltip row on the left click also can be usefull.

**Comment by alshan** [comment]
Python variant see [4.5.0](https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-450)

**Comment by pvinokurov** [comment]
It looks awesome!

**Comment by alshan** [comment]
.. and Kotlin! [v4.9.0](https://github.com/JetBrains/lets-plot-kotlin?tab=readme-ov-file#what-is-new-in-490)
