### ISSUE TITLE
`theme`: left margin doesn't work for the `plot_title` parameter

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#1101]
Example:

```python
ggplot() + geom_point(x=0) + ggtitle("Title") + theme(plot_title=element_text(margin=[5, 100]))
```

Output:

<img src="https://github.com/JetBrains/lets-plot/assets/26162403/e5887d83-470c-4882-95b5-735eeeb1dddd" width="500"></img>

Expected:

<img src="https://github.com/JetBrains/lets-plot/assets/26162403/7d760d3c-cf34-4578-996e-844a5c26049b" width="500"></img>

**Comment by OLarionova-HORIS** [comment]
Fixed ignoring of horizontal margins for plot title/subtitle/caption. 
The image below shows the bounding boxes (in light blue) after the margins have been applied:

<img width="600" alt="Screenshot 2024-05-14 at 13 03 32" src="https://github.com/JetBrains/lets-plot/assets/46743085/334f3a09-f6bd-43ec-80a5-ff3c04c93d7c">
