### ISSUE TITLE
density2d plot extent by default

### ISSUE THREAD

**Issue by egayer** [JetBrains/lets-plot#1117]
Hi everyone, 

I am having trouble with `geom_density2d()` and can't get a correct plot when the X values are much smaller than the Y values (and vice versa). When X and Y are of the same order of magnitude, `geom_density2d()' behaves like other geoms, so the plot is readable.

Here is an example to illustrate this. What do we need to do to make it readable? Also, could `geom_density2d()' behave like the other geoms by default?

```
x=np.random.poisson(lam=50.0, size=100)*100
y=np.random.poisson(lam=10.0, size=100)

df=pd.DataFrame({'x':x, 'y':y})

p = ggplot(df, aes(x='x', y='y')) \
+ geom_density2d()
p
```

PS: same with `geom_ bin2d()`

**Comment by alshan** [comment]
Hi @egayer! 
With both, try using `+ coord_cartesian()`. 
By default, these geoms use `coord_fixed()`, which does not work well when the values on the X/Y scales have significantly different magnitudes.

**Comment by egayer** [comment]
Thank you @alshan, it works fine with `coord_fixed()`.

If it is not too much trouble for you guys, I feel it would be helpful to mention it directly on the `geom_ bin2d()` and `geom_density2d()` pages.

**Comment by alshan** [comment]
Certainly, this also just come to me that this should be mentioned in the docs.
