### ISSUE TITLE
Add protection from entering absurd values.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#115]
For the instance, entering `ggsize(1000000, 1000000)`  will freeze notebook  (at least datalore nb).

**Comment by IKupriyanov-HORIS** [comment]
Default limit is set to 10_000 x 10_000. Limit can be changed via env vars `LETS_PLOT_MAX_WIDTH` and
`LETS_PLOT_MAX_HEIGHT` or via function `LetsPlot.set({'max_width': 100_000, 'max_height': 100_000})`
