### ISSUE TITLE
`geom_histogram`: wrong plot area when `y='..density..'`

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#1157]
Example:

```python
ggplot({'x': [-.5, 0, 0, .5]}, aes(x='x')) + geom_histogram(aes(y='..density..'), binwidth=.5)
```

<img src="https://github.com/user-attachments/assets/c6b53e8e-40c9-48fa-9841-89f64f13e22d"></img>

The plot area is expected to be 1, but it's actually 2.

**Comment by alshan** [comment]
Related question: https://stackoverflow.com/questions/78875366/what-is-density-doing-in-lets-plot-histogram
