### ISSUE TITLE
secondary y-axis

### ISSUE THREAD

**Issue by syd-doyen** [JetBrains/lets-plot#1161]
Hi,
Question:
Is it was possible to have a secondary y-axis . In ggplot, scale_y_continuous has a parameter sec-axis that allows you to have a second vertical axis. I could not find the same parameter lets-plot scale_y_continuous. 
Thanks.

**Comment by alshan** [comment]
Hi, lets-plot doesn't have support for secondary axes. Also, I feel there might be a better solution targeting the series comparison use case.

**Comment by syd-doyen** [comment]
HI Igor, 

Thanks for your response. Before I attempt, would you know if I can draw an axis independently and added to a plot with the data associated with the second vertical axis scaled to be within the original vertical axis.

Cheers,
Aldo

**Comment by nsiicm0** [comment]
@alshan I have multiple use cases for visualization where overlaying data on a different y-axis might be helpful. Can you elaborate what you meant with your second statement?

**Comment by alshan** [comment]
Hi, what I meant was creating a function similar to [gggrid, ggbunch](https://lets-plot.org/python/pages/charts.html#l19-d19-grouping-plots),  but specifically designed for overlaying multiple plots, with shared x-axis and different y-axes as an option.

**Comment by nsiicm0** [comment]
Ah got it. This makes much more sense than a secondary y-axis and potentially even allow N y-axes. I like it. Sorry I didn't get it in your first reply and bringing this topic up again. 

As far as I can tell, this is not yet implemented. Is this somewhere on the horizon or not "tackled" at all?
I gather that the "new" insetting capability of ggbunch could be somehow abused to achieve something similar as a workaround (https://nbviewer.org/github/JetBrains/lets-plot-docs/blob/master/source/examples/cookbook/geopandas_kotlin_isl.ipynb) but it would probably not work for tooltips and such.

**Comment by alshan** [comment]
It's not yet tackled. With ggbunch it is indeed possible to overlay plots, but the alignment of inner plotting areas (a.k.a. plot panel) would be challenging. I'm not 100% sure about tooltips, but most likely the topmost plot would consume all mouse events.
What would be a good name for this function? Maybe ggdeck() (like a deck of cards)?

**Comment by nsiicm0** [comment]
That's what I think as well with the topmost plot layer for the mouse events.

`ggstack` would have been my initial guess. But `ggdeck` is fine too.

**Comment by alshan** [comment]
Very good, I've submitted a feature request: #1337
