### ISSUE TITLE
superscript formatting

### ISSUE THREAD

**Issue by Zaf4** [JetBrains/lets-plot#1166]
Hi,

I could not figure out a way to format superscripts as  **10<sup>3</sup>** rather than **1.10<sup>3</sup>** Is there a workaround for this or is this not implemented in anyway yet?
I guess #1071 is related to this.

the last thing I tried was the following.

```
+ scale_y_log10(format=".0~e")
+ theme(exponent_format="pow")
```
I was hoping `.0` would get rid of the **"1."** but `.1` , `.2` and `.0`  or even only `~e` behaves the same.

**Comment by alshan** [comment]
Unfortunately, the shortened form is not yet implemented. Please, follow #1071 .
