### ISSUE TITLE
Unable to display or save graph when using geom_path

### ISSUE THREAD

**Issue by chameroy** [JetBrains/lets-plot#1168]
I've been trying out lets-plot through a Jupyter notebook on Windows 11.

I'm experiencing an issue that comes up when I use geom_path. I receive this error message both when trying to view a plot in Jupyter and when trying to save the image using ggsave, regardless of file format:

`Exception: Internal error: NullPointerException : <no message>`

Unfortunately, that's all I receive. Using geom_line in place of geom_path produces a graph, but not always with the desired result.

**Comment by IKupriyanov-HORIS** [comment]
Hi! 
Could you please provide an example? This will help us a lot.

**Comment by chameroy** [comment]
Sure. Here is an example of some code I've been trying to run:

```
plot = (
ggplot(core_10004_1A_1, aes("value", "depth_m", group="section_no")) +
    ggsize(150, 500) +
    geom_line() +
    facet_grid(x="channel", scales="free") +
    scale_y_reverse() +
    labs(x="Values", y="Depth (m)") +
    theme(legend_position="none")
)

ggsave(plot, "plot_test.png")
```

I've tried to get the resulting plot to show in Jupyter as well as save it locally in case this is a Jupyter issue. I get the same outcome in either case.

This is what I get when I use geom_line:
![plot_test](https://github.com/user-attachments/assets/24d26e00-5b57-4410-83f1-b7f951113245)

However, when I use geom_path, I get the error message I previously mentioned.

Running the same code using geom_path (and some minor tweaks due to library differences) using plotnine gives me closer to what I'm looking for:
![plot9_test](https://github.com/user-attachments/assets/ccf4c7c8-87f5-4612-b96a-557b15c2edad)

**Comment by IKupriyanov-HORIS** [comment]
Thanks! The code is totally fine. Could you please attach your data (`core_10004_1A_1`) if possible? Looks like it is the key for fixing the issue.

**Comment by chameroy** [comment]
Sure. Here it is. FYI, it's tab-delimited and has about 200,000 records. The original has close to 500,000, but it's too large for me to upload here. Hopefully, this should be good enough.

[core_10004_1A_1.csv](https://github.com/user-attachments/files/16840690/core_10004_1A_1.csv)

**Comment by IKupriyanov-HORIS** [comment]
Thank you! I'v reproduced the issue. 
To workaround the problem add `sampling='none'` to `geom_path(...)`.  
Full code:
```python
plot = (
ggplot(core_10004_1A_1, aes("value", "depth_m", group="section_no")) +
    ggsize(150, 500) +
    geom_path(sampling='none') +
    facet_grid(x="channel", scales="free") +
    scale_y_reverse() +
    labs(x="Values", y="Depth (m)") +
    theme(legend_position="none")
)
plot
```

**Comment by chameroy** [comment]
That works! Thanks!

You referred to this as a workaround. I assume that this is not intended behavior? Will this be addressed in a future version?

Thank you again!

**Comment by IKupriyanov-HORIS** [comment]
> I assume that this is not intended behavior? Will this be addressed in a future version?
Definitely.
