### ISSUE TITLE
Legend: add theme "Spacing and margins"

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#1180]
See ggplot2 legend [Spacing and margins](https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-legends/#spacing-and-margins).

**Comment by OLarionova-HORIS** [comment]
Added: 
`legend_margin, legend_spacing, legend_spacing_x, legend_spacing_y`,
`legend_box, legend_box_just, legend_box_spacing`
Commit: https://github.com/JetBrains/lets-plot/pull/1209

**Comment by alshan** [comment]
https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-450
