### ISSUE TITLE
Legend: add theme parameters controlling size of the key.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#1181]
```
  legend.key,
  legend.key.size,
  legend.key.height,
  legend.key.width,
```

See: https://ggplot2.tidyverse.org/reference/theme.html

**Comment by alshan** [comment]
Related #1180

**Comment by OLarionova-HORIS** [comment]
Added: https://github.com/JetBrains/lets-plot/commit/281816269c2b933cc48a2cfe8325cf2e51ed4416

**Comment by alshan** [comment]
Release [4.5.0](https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-450)
