### ISSUE TITLE
Display integer values without fractional part in tooltips

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/lets-plot#1186]
```python
from lets_plot import *
LetsPlot.setup_html()

d = {
    'l': [3],
}
ggplot(d, aes(color='l')) + geom_point() + ggsize(300, 200)
```
![image](https://github.com/user-attachments/assets/dcb5ccef-3aa3-4d74-a8c1-9044854eaaae)

```python
from lets_plot import *
LetsPlot.setup_html()

d = {
    'l': [3_000_000],
}
ggplot(d, aes(color='l')) + geom_point() + ggsize(300, 200)
```
![image](https://github.com/user-attachments/assets/7bf37428-b9a0-490e-b4d3-c35e6ffefea0)

**Comment by alshan** [comment]
Maybe related: 
![image](https://github.com/user-attachments/assets/32cb7e64-4550-4470-87be-8a78674348ed)

see: https://github.com/JetBrains/lets-plot/issues/1188#issuecomment-2353701572
