### ISSUE TITLE
`ggmarginal`: bottom `boxplot` is broken

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#1189]
Example:

```python
data = {
    "x": [0, 0, 1, 1, 1, 2],
    "y": [0, 0, 2, 2, 2, 1],
}
ggplot(data, aes("x", "y")) + \
    geom_point() + \
    ggmarginal("trbl", layer=geom_violin(color='blue', fill='blue', alpha=.1)) + \
    ggmarginal("trbl", layer=geom_boxplot(color='red', fill='red', alpha=.1))
```

<img src="https://github.com/user-attachments/assets/13a15bb6-85e8-4eb6-89e6-796bcfc827fb" width="500"></img>

---

**Note:** Worked in 4.2.0.

**Comment by alshan** [comment]
Blamed commit: https://github.com/JetBrains/lets-plot/commit/4ac81f69b493e36303ddb1edc899b0dbf36261fa
