### ISSUE TITLE
Removing only x facet labels in facet_grid

### ISSUE THREAD

**Issue by shriv** [JetBrains/lets-plot#1191]
Kia ora, 
I have a facet grid plot from which I want to remove the facet labels only for columns (x facet) but `theme(strip_text = element_blank())` removes all facet labels. Is there an option to only turn off one or the other like with `strip.text.x` in ggplot2? 

Thanks!

**Comment by alshan** [comment]
Kia ora :) Sorry to inform that the this is not currently possible. I'v submitted the issue: #1195
