### ISSUE TITLE
Theme: missing strip.text.x parameter

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#1195]
... and few other parameters controlling appearance of facet labels:

strip.text.x, 
strip.text.x.top, strip.text.x.bottom, 
strip.text.y, 
strip.text.y.left, strip.text.y.right

**Comment by OLarionova-HORIS** [comment]
Added: 
`strip_background_x, strip_background_y`,
 `strip_text_x, strip_text_y`
Commit: https://github.com/JetBrains/lets-plot/commit/2e82a6507db94adf1430bc1b30edc48a2cfc790a

**Comment by alshan** [comment]
Released in [v4.5.0](https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-450)
