### ISSUE TITLE
Allow tuples to define the linetype in element_line

### ISSUE THREAD

**Issue by concimuscb** [JetBrains/lets-plot#1198]
Hello,

It would be interesting to add the possibility of passing tuples to the linetype argument to define custom linetypes. 

I quite like the plotnine implementation: (4, (1, 4, 10, 3))

The first element is always an integer which defines the offset to start drawing the line in relation to the axis of the chart.
The second element is a tuple of n elements. The first element is ink, second is space, third is ink, fourth is space, and so on so forth.

In the example a line is drawn with 4 (px?) off set and then 1 px ink, 4 px space, 10 px ink, 3 px space and then the sequence is repeated 1,4,10,3....

Not sure how challenging would it be to implement this.

**Comment by OLarionova-HORIS** [comment]
Commit https://github.com/JetBrains/lets-plot/commit/9ac0ed8762a75472e2587ee270ff203bd79f72a0 :
- `[dash, gap,, ...]`;
- `[offset, [dash, gap, , ...]]`;
- string of hexadecimal digits

**Comment by alshan** [comment]
Released in [v4.5.0](https://github.com/JetBrains/lets-plot/releases/tag/v4.5.0)
