### ISSUE TITLE
White background needed when plot is shown on a dark backdrop in PyCharm dark scheme

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#121]
Single plot in PyCharm notebook:
![image](https://user-images.githubusercontent.com/4430922/80262956-188a0380-865d-11ea-9332-3ca70a1a947f.png)

GGBunch in PyCharm notebook:
![image](https://user-images.githubusercontent.com/4430922/80263100-80d8e500-865d-11ea-9850-c4507701d46a.png)

**Comment by Ub3rJosh** [comment]
Was this fixed?

**Comment by alshan** [comment]
This one is pointing out that a transparent plot does not look good on dark background. Now plots are rendered with an opaque background. So, yes, it was fixed.
