### ISSUE TITLE
lets_plot_kotlin_bridge is unable to locate libc++.1.dylib, I am using Mac m2

### ISSUE THREAD

**Issue by dipunew** [JetBrains/lets-plot#1234]
The error message indicates that the lets_plot_kotlin_bridge is still unable to locate libc++.1.dylib.

**Comment by alshan** [comment]
Interesting, what kind of Python env are you using?

**Comment by VDovidaytis-HORIS** [comment]
Possible fix of the problem: https://github.com/JetBrains/lets-plot/commit/241ee55771a95ac69eba8494ce5e05fc1b327e5f

**Comment by VDovidaytis-HORIS** [comment]
Could you provide more details, please:

 - full error output
 - macOS version
 - `xcodebuild -version` output
 - `xcode-select -version` output
 - PyEnv version and how did you install it.
 
 I will try to reproduce the error.

**Comment by VDovidaytis-HORIS** [comment]
> I’ve also tried the suggested fix ([241ee55](https://github.com/JetBrains/lets-plot/commit/241ee55771a95ac69eba8494ce5e05fc1b327e5f)), but unfortunately, the issue still persists.

And let me clarify: how did you try the fix?

**Comment by keatingw** [comment]
Hi there, just chiming in that I have the same error on an M1 Max Macbook using Python 3.12.4 and lets-plot v4.5.1—hopefully this can help reproduce.

I tried to test the fix posted above but couldn't get Gradle building correctly (though admittedly didn't have much time to troubleshoot robustly).

Details:
- macOS version: 14.7.1
- no xcodebuild install, so `xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`
- `xcode-select version 2408`

I'm using `uv` to set up an environment and install:
```shell
uv venv -p 3.12.4
uv pip install lets-plot
.venv/bin/python -c "from lets_plot import *"
```
Gives:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/<user>/Developer/lp-test/.venv/lib/python3.12/site-packages/lets_plot/__init__.py", line 17, in <module>
    from .frontend_context import *
  File "/Users/<user>/Developer/lp-test/.venv/lib/python3.12/site-packages/lets_plot/frontend_context/__init__.py", line 6, in <module>
    from ._configuration import *
  File "/Users/<user>/Developer/lp-test/.venv/lib/python3.12/site-packages/lets_plot/frontend_context/_configuration.py", line 8, in <module>
    from ._html_contexts import _create_html_frontend_context, _use_isolated_frame, _create_wb_html_frontend_context
  File "/Users/<user>/Developer/lp-test/.venv/lib/python3.12/site-packages/lets_plot/frontend_context/_html_contexts.py", line 7, in <module>
    from ._jupyter_notebook_ctx import JupyterNotebookContext
  File "/Users/<user>/Developer/lp-test/.venv/lib/python3.12/site-packages/lets_plot/frontend_context/_jupyter_notebook_ctx.py", line 17, in <module>
    from .. import _kbridge as kbr
  File "/Users/<user>/Developer/lp-test/.venv/lib/python3.12/site-packages/lets_plot/_kbridge.py", line 7, in <module>
    import lets_plot_kotlin_bridge
ImportError: dlopen(/Users/<user>/Developer/lp-test/.venv/lib/python3.12/site-packages/lets_plot_kotlin_bridge.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: <C73BD5C1-9BE6-3DC6-8C81-759A39C12D94> /Users/<user>/Developer/lp-test/.venv/lib/python3.12/site-packages/lets_plot_kotlin_bridge.cpython-312-darwin.so
  Reason: tried: '/Users/vdovidaytis/Applications/miniconda3/envs/py312-arm/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vdovidaytis/Applications/miniconda3/envs/py312-arm/lib/libc++.1.dylib' (no such file), '/Users/vdovidaytis/Applications/miniconda3/envs/py312-arm/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/vdovidaytis/Applications/miniconda3/envs/py312-arm/lib/libc++.1.dylib' (no such file)
```

Thank you!

**Comment by VDovidaytis-HORIS** [comment]
@keatingw, hello!

Thank you for your report!

First, let me ask you to try installing the dev wheel from this archive into your environment:

[lets_plot-4.5.2.dev1-cp312-cp312-macosx_11_0_arm64.zip](https://github.com/user-attachments/files/17874978/lets_plot-4.5.2.dev1-cp312-cp312-macosx_11_0_arm64.zip)


Example:
```
pip uninstall lets-plot
unzip lets_plot-4.5.2.dev1-cp312-cp312-macosx_11_0_arm64.zip
pip install lets_plot-4.5.2.dev1-cp312-cp312-macosx_11_0_arm64/lets_plot-4.5.2.dev1-cp312-cp312-macosx_11_0_arm64.whl
```

This Python wheel contains the required fix.

**Comment by keatingw** [comment]
Confirming that dev wheel works from my end—the import error no longer occurs and I can render the quick start guide example plot. Thank you!

**Comment by paupereira** [comment]
I have the same problem but when I try the fix suggested by @VDovidaytis-HORIS and run `pip install lets_plot-4.5.2.dev1-cp312-cp312-macosx_11_0_arm64/lets_plot-4.5.2.dev1-cp312-cp312-macosx_11_0_arm64.whl
`, I get the error `ERROR: lets_plot-4.5.2.dev1-cp312-cp312-macosx_11_0_arm64.whl is not a supported wheel on this platform.`

I'm on a Apple M2 Pro, macOS Sequoia 15.1, using python 3.12.

**Comment by quickcoffee** [comment]
I have the same error as @paupereira (`is not a supported wheel on this platform.`).
I'm on a Apple M1, macOS 14.5, using python 3.11.0.

> could you please show the output of the following command:
@VDovidaytis-HORIS the output is `arm64`

**Comment by VDovidaytis-HORIS** [comment]
@quickcoffee  this is because you tried to install my wheel, which is built for Python 3.12, on your Python 3.11.

Okay, everyone. We have made a dev release with the required fix for all platforms available on PyPI.org. Please check it out:

```
pip install lets-plot==4.5.2.dev1
```

**Comment by quickcoffee** [comment]
@VDovidaytis-HORIS my bad, thanks!

Can confirm that with `4.5.2.dev1` the error is gone 🥳

**Comment by paupereira** [comment]
`4.5.2.dev1` fixed the issue :D
For the record, `python -c "import platform; print(platform.machine())"` returns `arm64`.

**Comment by dipunew** [comment]
Thank you so much VDovidaytis!. lets-plot==4.5.2.dev1 is working.

**Comment by VDovidaytis-HORIS** [comment]
> Thank you so much VDovidaytis!. lets-plot==4.5.2.dev1 is working.

You're welcome! But keep in mind that this is a dev version — don't forget to update it to the next release.
