### ISSUE TITLE
Can't  insert a different label or title, per plot, for plots in FacetWrap or FacetGrid

### ISSUE THREAD

**Issue by Alexander-Egistov** [JetBrains/lets-plot#1236]
Greetings,

Recently I have started using LetsPlot at work, in order to analyse measured experiment data, and it is far more comfortable, by far, then every other plotting framework in python, yet I have encountered a small problem - I can't insert a different label per each facet of facet grid or facet wrap, or at least add a different text in the title of the titles of facet grid or facet wrap.

And if I create such a plot object, there seems to be no way to iterate over the plots and edit those labels manually, or perhaps I am missing something?

So how can I change the labels or the titles to have a different label for each plot in the facet grid?

Let's say in this example?

import pandas as pd
import numpy as np
from lets_plot import *
LetsPlot.setup_html()
import seaborn as sns

pengu = sns.load_dataset('penguins').dropna()

g = (
    ggplot(pengu, aes(x = 'body_mass_g', y = 'bill_length_mm',))
    + geom_point(aes(color = 'species'))
    # + geom_smooth(aes(color='species'))
    + geom_smooth(aes())
    

    + ggmarginal('tr',layer=geom_density())
    + ggmarginal('tr',layer=geom_histogram( aes(fill='species'),alpha = 0.25, size = 0.25))
    + ggmarginal('bl', size = 0.05, layer=geom_boxplot(aes(color = 'species'),size = 0.4,))
    
    + facet_wrap(facets=['sex','island',], format = '{d} \nhow to add different text per plot?\nI need an R^2 value here')
    + labs(title='A facet grid of penguins', subtitle='colorful penguins', caption='caption' )

    + geom_label(x=4500, y=58, label='How to put different label \nper facet?', size=10)
    + xlab('body_mass_g') + ylab('bill_length_mm')
    + ggsize(1500,1000)
    + theme_bw()
)
g

![Screenshot_20241111_200417](https://github.com/user-attachments/assets/42db0b24-1b9d-4ce2-8019-2b7c063d2d83)

**Comment by alshan** [comment]
Hi, beautiful pic ! :)  I assume `R` in the facet strip is a variable in dataset and on top of chart is some arbitrary text ?

**Comment by Alexander-Egistov** [comment]
> Hi, beautiful pic ! :) I assume `R` in the facet strip is a variable in dataset and on top of chart is some arbitrary text ?

I needed to do similar charts for experiment data for work, and i did it in python, because it's the only language I know, but could not find a way to insert an R_Squared value for the linear regression line, since there appears no way to output any text, calculation or anything for the "geom_smooth", nor could I find a way to modify different facets of the facet grid.

And I don't really mind where to put the R-squared value, in the title, or as a label, or as an additional output  into the facet titles, no matter what I did, I couldn't find a way to do it.

Eventually I have just written a function to make individual plots with the R value in the title, and ran a loop to put them in a gggrid, yet that was a clunky and convoluted solution.

It would be really nice if the geom_smooth function would be able to output R squared values, based on what's it's smoothing, like in Excel, in addition to any other parameter defined to it, since this is far superior to excel.

**Comment by alshan** [comment]
Ok, to have custom text in facet titles you need to add another column (let's call it "facet") to the `pengu`:
```
# Compute R^2-values (replace with your formula)
R2_values = pengu.apply(
    lambda row: hash(row['sex'] + row['island']), 
    axis=1
)

# Create the "facet" column combining all elements. The value will be in facet titles.
pengu['facet'] = pengu.apply(
    lambda row: f"{row['sex']}\n{row['island']}\nR^2={R2_values[row.name]:.2e}", 
    axis=1
)
``` 

and then use this variable for faceting. The updated code: 

```
g = (
ggplot(pengu, aes(x = 'body_mass_g', y = 'bill_length_mm',))
+ geom_point(aes(color = 'species'))
# + geom_smooth(aes(color='species'))
+ geom_smooth(aes())
+ ggmarginal('tr',layer=geom_density())
+ ggmarginal('tr',layer=geom_histogram( aes(fill='species'),alpha = 0.25, size = 0.25))
+ ggmarginal('bl', size = 0.05, layer=geom_boxplot(aes(color = 'species'),size = 0.4,))

+ facet_wrap(facets=['facet'])
+ labs(title='A facet grid of penguins', subtitle='colorful penguins', caption='caption' )

#+ geom_label(x=4500, y=58, label='How to put different label \nper facet?', size=10)
+ xlab('body_mass_g') + ylab('bill_length_mm')
+ ggsize(1500,1000)
+ theme_bw()
)

g
```
![image](https://github.com/user-attachments/assets/442ce4c2-50f8-4811-9ed6-a9dddd765b3a)

As for `geom_label()`, you can use similar technique, or you can create smaller dataframe containing a description for each of the facet panels: 

```
unique_combinations = pengu[['sex', 'island', 'facet']].drop_duplicates()

# Add the "description" column
unique_combinations['description'] = unique_combinations.apply(
    lambda row: f"{row['sex']} penguins\nof {row['island']} island.", 
    axis=1
)

g + geom_label(
    aes(label="description"), 
    data=unique_combinations,   # <--- !
    x=4500, y=58, size=10)
``` 
![image](https://github.com/user-attachments/assets/8a0fe7a1-9bf9-4e01-9a89-106a7b37b13b)

**Comment by alshan** [comment]
I'm glad to hear it worked out for you and with this I'm closing this issue as completed :)
