### ISSUE TITLE
NPE in examples/jupyter-notebooks/geopandas_naturalearth.ipynb

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#124]
In the last cell: 
`Internal error occurred in lets-plot: NullPointerException : <no message>`

The issue is not present in 1.3.0 but is reproducible in dev build.
Where is our log btw?

**Comment by IKupriyanov-HORIS** [comment]
Fixed with commit https://github.com/JetBrains/lets-plot/commit/e9269e8948b8cba9ded66cf5063902d27aec08e2
