### ISSUE TITLE
Extra trim in formatted number when type='g'

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#1241]
Example:

```python
d = 10
v = 3.14 * 10**d

ggplot() + geom_label(x=0, label=v, label_format=".8g")
```

Output:

<img src="https://github.com/user-attachments/assets/a0163fb1-317c-488a-8a34-d6f1580d4f69"></img>

Expected:

<img src="https://github.com/user-attachments/assets/b0f2237d-72fe-49c8-a8d5-e3aa0846dfcd"></img>

**Comment by alshan** [comment]
To keep zeroes you need to use '#' flag :  `label_format="#.8g"`
