### ISSUE TITLE
How to adjust the vertical position of geom_text when using position_dodge

### ISSUE THREAD

**Issue by syd-doyen** [JetBrains/lets-plot#1248]
Hi, 

I'm just trying to understand whether the following behaviour is expected.
I'm using PyCharm-in windows 10,  lets-plot 4.5.1

```python

import pandas as pd
import os
import lets_plot as lp

df = pd.DataFrame(data=[['Subaru', 'Sold', 4], ['Subaru', 'InStock', 16],
                            ['Nissan', 'Sold', 2], ['Nissan', 'InStock', 8],
                            ['Ford', 'Sold', 3], ['Ford', 'InStock', 10],
                            ['Honda', 'Sold', 6], ['Honda', 'InStock', 2],
                            ], columns=['Brand', 'Status', 'Available'])
# the plot
p = (lp.ggplot(df, lp.aes(x='Brand', fill='Status', weight='Available'))
        + lp.geom_bar(position=lp.position_dodge(width=0.6), width=0.5, alpha=0.7)
        + lp.geom_text(lp.aes(label='..count..', group='Status'),
                         stat='count',
                         position=lp.position_dodge(width=0.6),
                         label_format="{d}",  size=9)
        + lp.ggtitle('Car Inventory') + lp.theme_bw())
p.show()
```
This code results in this:
![image](https://github.com/user-attachments/assets/f1ddf56b-240b-4953-bbc4-49a076b88f4f)

This is fine but I want to slightly move the text higher so it is outside of the bar. Not sure how to accomplish this. I tried using nudge_y=0.5  (an argument in geom_text) with the following results.  

```
p = (lp.ggplot(df, lp.aes(x='Brand', fill='Status', weight='Available'))
       + lp.geom_bar(position=lp.position_dodge(width=0.6), width=0.5, alpha=0.7)
       + lp.geom_text(lp.aes(label='..count..', group='Status'),
                         stat='count',
                         nudge_y = 0.5,
                         position=lp.position_dodge(width=0.6),
                         label_format="{d}",  size=9)
        + lp.ggtitle('Car Inventory') + lp.theme_bw())
p.show()
```
The vertical position is ok but the horizontal position has completely changed. It is not respecting the position_dodge.
See bellow. If this is expected any hints on how to move the geom_text to be higher than the bar?

![image](https://github.com/user-attachments/assets/ffc6d895-5c81-4ad9-bd77-f3cb540fe2e7)

Thanks in advance for your help.

**Comment by alshan** [comment]
Hi, it looks like `nudge_y` cancels `position_dodge`. Likely an issue but not 100% sure yet.
There are other ways however:

1. Use `vjust=0`:
```
        + lp.geom_text(lp.aes(label='..count..', group='Status'),
                         stat='count',
                         vjust=0,
                         position=lp.position_dodge(width=0.6),
                         label_format="{d}",  size=9)
```
![image](https://github.com/user-attachments/assets/73c95e5d-e485-43ef-927c-de861a5f1936)

2.  Use `vjust=0` and and `geom_label` with alpha:
Unlike `geom_text`, `geom_label` has padding options.
```
        + lp.geom_label(lp.aes(label='..count..', group='Status'),
                         stat='count',
                         vjust=0, alpha=0, label_size=0,
                         position=lp.position_dodge(width=0.6),
                         label_format="{d}",  size=9)
```
![image](https://github.com/user-attachments/assets/f42e046f-891e-4a4d-a62a-88290270b588)

4. Use "layer labels" (a.k.a. annotations) instead of geoms.
You might want to check out these docs: [Annotating Charts](https://lets-plot.org/python/pages/annotations.html).

```
p = (lp.ggplot(df, lp.aes(x='Brand', fill='Status', weight='Available'))
        + lp.geom_bar(position=lp.position_dodge(width=0.6), width=0.5, alpha=0.7,
                      labels=lp.layer_labels().line('@..count..').format('..count..', '{d}')
                     )
        + lp.ggtitle('Car Inventory') + lp.theme_bw())

``` 
![image](https://github.com/user-attachments/assets/5c5a8710-920d-43c1-8fc2-44323f550943)
