### ISSUE TITLE
`theme`: parameter `exponent_format` does not switch on superscript

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#1250]
Example:

```python
values = [2e-10, 3e-10]
ggplot() + \
    geom_text(aes(x=values, label=values)) + \
    scale_x_continuous(breaks=values) + \
    theme(exponent_format='pow')
```

Output:

<img src="https://github.com/user-attachments/assets/101582cb-57f7-43f6-9b1a-1edf9025d9e2"></img>

Expected:

<img src="https://github.com/user-attachments/assets/3c73883e-45ec-429b-b7d7-9b3c837e09d7"></img>

**Note**: To get the expected behaviour, you should explicitly specify the format `"g"` or `"e"` wherever superscript is required, but I'm not sure it's intended to work that way.

**Comment by alshan** [comment]
Default formatting should respect `exponent_format='pow'`.
