### ISSUE TITLE
gggrid does not share labels 

### ISSUE THREAD

**Issue by Zaf4** [JetBrains/lets-plot#1252]
I am not sure I am doing it correctly 

I would expect following code to produe grid with the shared x and y labels, but it does not.
```
plot1 = ggplot({"x": [1, 2, 3], "y": [4, 5, 6]}) + geom_point(aes("x", "y"))
plot2 = ggplot({"x": [2, 3, 4], "y": [6, 7, 8]}) + geom_point(aes("x", "y"))
plot3 = ggplot({"x": [1, 2, 3], "y": [4, 5, 6]}) + geom_point(aes("x", "y"))
plot4 = ggplot({"x": [2, 3, 4], "y": [6, 7, 8]}) + geom_point(aes("x", "y"))

grid = gggrid([plot1, plot2, plot3, plot4], ncol=2, sharex="all", sharey="all")

grid = grid + theme_classic()+ ggsize(600, 400)+theme(axis_title=element_text(size=20,face="bold"))
grid
```
![issue](https://github.com/user-attachments/assets/de3c9c77-fbd1-4e63-9db2-bb493c568068)

Is this the intended behavior, if so is there way to share x and y labels? Note that, I tried with `grid+labs()` which raise an error.

**Comment by alshan** [comment]
`sharex`, `sharey` only align limits along respective axis. Any further adjustments if needed you will have to do for each plot in grid individually, using `theme()`, `labs()` etc.

**Comment by Zaf4** [comment]
Thanks for the clarification, I guess there is no way to add common xy labels like in the seaborn.
