### ISSUE TITLE
Tooltips overlapping when not enough vertical space for them

### ISSUE THREAD

**Issue by Nikita-Pavlenko** [JetBrains/lets-plot#1254]
On the attached video we can see that when there is lack of vertical space for all tooltips, they started to behave chaotic.

![image](https://github.com/user-attachments/assets/f3982b60-ecb0-480f-9977-a754e521a893)
![image](https://github.com/user-attachments/assets/eb2a9928-eeb5-4517-9352-01f45db76c56)
[Screencast from 25-11-24 18_17_49.webm](https://github.com/user-attachments/assets/7b63e789-ea45-4c58-a3ec-e812c23f4567)

**Comment by IKupriyanov-HORIS** [comment]
Appears to be a regression: see #793 and #895.

**Comment by alshan** [comment]
Hi @Nikita-Pavlenko , this hopefully fixed in [v4.9.3](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v4.9.3).
