### ISSUE TITLE
map: do not apply 'alpha' to (boundary) color in geom_polygon

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#126]
The following expression: 
```python
p + geom_livemap() + geom_polygon(map=CA, color='red', alpha=0)
```
should show CA boundary in red.

Currently it doesn't show anything.

**Comment by IKupriyanov-HORIS** [comment]
Fixed in https://github.com/JetBrains/lets-plot/commit/c969be7f3afad65fbbb900282520378f432847aa
