### ISSUE TITLE
Plot limited to 1000 lines (`Internal error: IllegalStateException : Too many groups: 1099`)

### ISSUE THREAD

**Issue by BenWoodworth** [JetBrains/lets-plot#1261]
I'm running into a hard limit with the number of lines/"colors" in a plot of mine. It looks like it's coming from [DataProcessing.kt](https://github.com/JetBrains/lets-plot/blob/v4.5.1/plot-builder/src/commonMain/kotlin/org/jetbrains/letsPlot/core/plot/builder/data/DataProcessing.kt#L392C9-L392C25).

Could this limit be increased/removed, or made configurable?

For me I can work around it by having a separate geomLine layer for each group of data on the plot, but for me, with a lot of relatively short-lived lines, it would be convenient to not need to worry about hitting a limit

**Comment by alshan** [comment]
Hi @BenWoodworth , in [v4.9.3](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v4.9.3) we increased the max groups limit to 100.000. Also, the legend will not be show (if num of items >=200).
