### ISSUE TITLE
map: add support for `arrow` param in geom_segment()

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#131]

**Comment by alshan** [comment]
An example where we have an "arrow" but it's not working on map:  [Pushkin](https://datalore.jetbrains.com/view/notebook/DyD2CLrAbpfO3FMtg6QuhT)

**Comment by OLarionova-HORIS** [comment]
Added.
https://github.com/JetBrains/lets-plot/pull/531
https://github.com/JetBrains/lets-plot/pull/533
