### ISSUE TITLE
 map: geom_text vjust="center" is a bit off

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#132]
```python
data = {
    'label': ["==    0 ==>", "==   60 ==>", "==  120 ==>", "==  180 ==>", "== -60 ==>", "== -120 ==>"],
    'angle': [0, 60, 120, 180, -60, -120],
}

p + geom_livemap() + geom_point(x=0, y=0, size=140, color='white', alpha=0.6)\
  + geom_text(aes(label = 'label', angle='angle'), data=data,
              x=0, y=0, 
              hjust = "left", vjust = "center",
              size=10, family='monospace', color='red')
```
![image](https://user-images.githubusercontent.com/4430922/81104515-a0370400-8ee0-11ea-8940-109fcd1ee31c.png)

Compare to not on the map: 
![image](https://user-images.githubusercontent.com/4430922/81104638-d2486600-8ee0-11ea-98f0-44fb37f1ffe3.png)

**Comment by alshan** [comment]
`geom_text()` looks good in this demo : [Quickstart with Maps](https://datalore.jetbrains.com/view/notebook/9dzGjTQay4ENqj7GTEIvBU)

**Comment by IKupriyanov-HORIS** [comment]
Fixed via https://github.com/JetBrains/lets-plot/commit/dcab039d.
