### ISSUE TITLE
is_discrete: a rounding error.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#135]
See geom_smooth.ipynb

A rounding error occurs when using 'is_discrete'.  However, its not clear whether this is caused by 'is_discrete' or not.

![image](https://user-images.githubusercontent.com/4430922/81443473-7cbfc380-9143-11ea-99a0-621e212e5934.png)

**Comment by alshan** [comment]
I've patched DataProcessing (https://github.com/JetBrains/lets-plot/commit/e7c5ca7e5f7a4211fe8c9cf6227b2f2ecfbde33f).

Needs further investigation: 
- Why `data.isNumeric(variable)` returns `True`. Expected `False` for `as_discrete(var)`
- It seems that two different color scales are created for points layer and for lines layer. Expected - one color scale per plot.

**Comment by IKupriyanov-HORIS** [comment]
Fixed rounding error, but color scales issue is not related with `as_discrete` function and requires separate issue:
![image](https://user-images.githubusercontent.com/14200189/82668667-aba95f80-9c42-11ea-8a5d-72474088b296.png)
