### ISSUE TITLE
Pycharm integration not functional

### ISSUE THREAD

**Issue by holgerbrandl** [JetBrains/lets-plot#138]
When running the example from https://github.com/JetBrains/lets-plot/blob/master/README_PYTHON.md#start under pycharm using a juptyer with the latest kotlin kernel running on ubuntu, lets-plot does not work and fails with 
![image](https://user-images.githubusercontent.com/200952/81991405-764cb280-9641-11ea-9321-284cdcdbfdfa.png)

Most likely this more a pycharm problem.

**Comment by alshan** [comment]
Hi Holger, you are trying to run python code with Kotlin kernel. 
Please, try this example: https://github.com/JetBrains/lets-plot-kotlin/blob/master/README.md

Frankly, I've never tried it in PyCharm )

**Comment by alshan** [comment]
Not sure if PyCharm can handle Kotlin code. If not, this should work in IDEA in data science project mode.

**Comment by holgerbrandl** [comment]
Indeed, I guess it was late. :-) However, same problem when actually using the kotlin example. I think I've stumbled over https://youtrack.jetbrains.com/issue/PY-38331 (again).

Thanks for the help @alshan and sorry for the tracker spam.
