### ISSUE TITLE
map: calif.housing

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#140]
See this modified (!) notebook: https://github.com/JetBrains/lets-plot/tree/master/docs/examples/jupyter-notebooks-dev/issues/map-california-housing

Modifications:
- used the entire housing data (without sampling)
- data in ggplot(data=...)
- polygons (CA boundaries geodataframe) are in layer's map=...

The issue: no maps are shown, instead a cryptic message is displayed: `Can't apply sampling: couldn't deduce the (X) variable`

**Comment by IKupriyanov-HORIS** [comment]
This issue can be reproduced without `map` parameter:
```
data = {
    'foo': [i for i in range(0,50_000)],
    'bar': [i for i in range(0,50_000)],
    'baz': [i for i in range(0,50_000)],
    'foobar': [i for i in range(0,50_000)],
}
ggplot(data) + geom_point()
ggplot(data) + geom_polygon()
```
Root of the issue is sampling, applied even for layers without any data mappings. Also there is some kind of AI on some layers, selecting random variables from data (like `geom_point`).

**Comment by alshan** [comment]
Related #73
