### ISSUE TITLE
Document smoothing parameters in `geom_smooth()`

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#178]
Imported parameters are not documented: 

method, n, level, se, span, deg, seed, max_n

There are descriptions in the kotlin variant: https://github.com/JetBrains/lets-plot-kotlin/blob/2bf0aed899963d2422825db359605729cc1162f9/plot-api/src/main/kotlin/jetbrains/letsPlot/geom/geom_smooth.kt#L45

but might not be totally correct. Check with Ilya.

**Comment by IKupriyanov-HORIS** [comment]
Fixed by https://github.com/JetBrains/lets-plot/pull/179
