### ISSUE TITLE
sphinx-doc: provide a yml env file.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#195]
Provide a yml environment file containing all dependencies necessary for building the documentation.

In readme provide an info on how to create / update the conda environment used when the documentation is being built.
See: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by VDovidaytis-HORIS** [comment]
Done.

https://github.com/JetBrains/lets-plot/commit/3bd53ffd80579d2d51facb8179d1eb372422502e
https://github.com/JetBrains/lets-plot/commit/babdb780a98a5e45db41cacc1a963d2db09d4e17

**Comment by VDovidaytis-HORIS** [comment]
Fixed.

https://github.com/JetBrains/lets-plot/commit/01c8489f0e81d56c05ec8af4654411bb5ba824ec
https://github.com/JetBrains/lets-plot/commit/2ab763afaaf31111bde53a0d7515df956246ed94
