### ISSUE TITLE
Marginal plots

### ISSUE THREAD

**Issue by abergou** [JetBrains/lets-plot#200]
Seaborn has a very nice [`jointplot`](https://seaborn.pydata.org/generated/seaborn.jointplot.html) which combines a scatterplot with a histogram of x and y. Is creating a plot like this possible in `lets-plot`? If not then might it be possible to add low level hooks to create such a plot (e.g. the ability to add plots to the x and y axes of a main plot where the x and y axes are shared).

**Comment by alshan** [comment]
Nice plots indeed. In Lets-Plot you can freely combine plots using the general-purpose `GGBunch` object . See the [ggbunch example](https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/ggbunch.ipynb). 

Unfortunately, at the moment Lets-Plot doesn't have capability to flip axis on plots so the Y-histogram can't be done at this time.

**Comment by alshan** [comment]
Hi @abergou 
We've added `ggmarginal()` in 2.4.0: https://github.com/JetBrains/lets-plot#marginal-plots

It might also make sense to add a higher level API to make building marginal plots simpler and quicker. Will try to do it later.
