### ISSUE TITLE
Wikimedia Tileservers going away for 3rd party usage

### ISSUE THREAD

**Issue by reedy** [JetBrains/lets-plot#211]
It's deprecated for 3rd parties, and use will be disallowed in the near future (slated for 2020-10-12; ie tomorrow as of writing)

https://lists.wikimedia.org/pipermail/maps-l/2020-August/001729.html
https://phabricator.wikimedia.org/T261424

**Comment by alshan** [comment]
Thank you for the heads-up, we will update examples asap.
