### ISSUE TITLE
Is there a way to use the standard ggplot theme with lets-plot?

### ISSUE THREAD

**Issue by prasoon2211** [JetBrains/lets-plot#221]
Hi,
Is there a way to achieve the standard ggplot theme with lets-plot plots? Perhaps something similar to `sns.set()`? I didn't find anything in the docs but maybe I missed it.

**Comment by alshan** [comment]
No, customization of the plot elements beyond removing axis lines/ticks or labels is not yet implemented.
What are you missing most from the standard ggplot theme? Background or grid lines or both? )
![image](https://user-images.githubusercontent.com/4430922/97616194-9c4cf000-19f2-11eb-922c-51de33622b4a.png)

**Comment by prasoon2211** [comment]
Nothing specific really -  I was just giving lets-plot a try to see how well it works and the default theme wouldn't fit in with some of my other plots so I was wondering is there is an easy way to switch over to default ggplot theme 😅

Personally, the background, the default ggplot colour scheme for the various geoms and the font would be my top 3.

**Comment by alshan** [comment]
Thank you for the feedback!

**Comment by holgerbrandl** [comment]
I'd also love to have an option to bring back ticklines (readability) and background (better overall contrast of plot wrt to background). 

Theming goes clearly beyond those 2 aspects and includes many other attributes that a user may want to customize. E.g. see https://ggplot2.tidyverse.org/reference/#section-themes and for a complete listing https://ggplot2.tidyverse.org/reference/theme.html

**Comment by alshan** [comment]
Themes were added in 
- Lets-plot [v2.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#220---2021-10-29)
- Lets-plot for Kotlin [v3.1.0](https://github.com/JetBrains/lets-plot-kotlin/blob/master/CHANGELOG.md#310---2021-11-05)

**Comment by holgerbrandl** [comment]
That's wonderful news. Thanks a lot. 

Is there a way to set a default theme (e.g. in a jupyter notebook)?

**Comment by alshan** [comment]
Unfortunately no, at the moment there is no way to set a default theme. I've created a ticket: #495
