### ISSUE TITLE
Nice to be able to override the default tooltip color.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#231]
![image](https://user-images.githubusercontent.com/4430922/98733273-466f3500-236e-11eb-85d6-35883f88c6b2.png)

Sometimes it is desirable to have color of tooltip different from the color of marker.

See Out[12] here: https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/geopandas_naturalearth.ipynb

**Comment by OLarionova-HORIS** [comment]
Done: https://github.com/JetBrains/lets-plot/pull/277
