### ISSUE TITLE
Support facet_wrap

### ISSUE THREAD

**Issue by ValdarT** [JetBrains/lets-plot#238]
It would be nice if [facet_wrap](https://ggplot2.tidyverse.org/reference/facet_wrap.html) was supported. 

Alternatively, this use case could be supported by allowing to specify number of rows/columns in `facet_grid` either through additional arguments (`nrow`/`ncol`) or by allowing integer values for `rows`/`cols` if the other has string value (the string would indicate the column to use and the integer would indicate how many rows/column to use for the plot). This would deviate from the original R ggplot2 API, though.

**Comment by alshan** [comment]
We prefer to stick with R ggplot2 API as closely as possible) Supporting of the facet_wrap is a must, will try to add it soon, thanks!

**Comment by alshan** [comment]
Hi, I've added the `facet_wrap()` function in [v2.0.0](https://github.com/JetBrains/lets-plot/releases/tag/v2.0.0)

Also the facet labels now support custom formatting and ordering.

The facet appearance is nicer now as well (I hope :)). Check this out: [Facets demo](https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/facets.ipynb)
