### ISSUE TITLE
Tooltip should appear if the mapped data is continuous

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#241]
```
import random
from lets_plot import *

def get_points(n):
    random.seed(37)
    return dict(
        x = list(range(n)),
        v = [random.uniform(-.8, .9) for _ in range(n)]
    )

(ggplot(get_points(20), aes(x='x', fill='v')) +
     geom_tile() +
     scale_fill_brewer(palette='PRGn'))
```

No tooltip appear on tiles.

**Comment by alshan** [comment]
Batik example: https://github.com/JetBrains/lets-plot/blob/5c190d0badac8618715f683c5ff0f98c044b07c3/plot-demo/src/jvmBatikMain/kotlin/plotDemo/plotConfig/ScaleBrewerWithContinuousDataBatik.kt

**Comment by OLarionova-HORIS** [comment]
Fixed: https://github.com/JetBrains/lets-plot/commit/b82ca3e16be13f3afe3f16ebefef2ca0320ce737
