### ISSUE TITLE
Strange looking legend for tiles

### ISSUE THREAD

**Issue by IKrukov-HORIS** [JetBrains/lets-plot#245]
Sometimes legend for tiles looks  like this:
![Screenshot from 2020-11-25 18-42-55](https://user-images.githubusercontent.com/45228182/100250030-436b6b80-2f4e-11eb-9450-4e9e62847d73.png)

Example:

d = { 'x' : [1], 'y' : [1], 'c' : [0]}
ggplot(d) + geom_tile(mapping=aes(x='x', y='y', fill='c', color='c')) + \
scale_color_brewer(name = 'c', palette='Spectral') +  \
scale_fill_brewer(name='', palette='Spectral')

**Comment by alshan** [comment]
Bug: In `scale_xxx()` parameter `name=''` has the same effect as `guide='none'` - hides the legend.
Expected:  parameter `name=''` should only remove the legend title.
