### ISSUE TITLE
y-tooltip should be aligned with a tile center.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#246]
![image](https://user-images.githubusercontent.com/4430922/100487588-79882700-30d7-11eb-8c24-34303640a52a.png)

code:
```
ggplot() + geom_tile(aes(x=[0], y=[0]))
```

**Comment by OLarionova-HORIS** [comment]
Fixed by https://github.com/JetBrains/lets-plot/pull/254
