### ISSUE TITLE
Long titles are displayed incorrectly

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#289]
Look at the following simple example:

```python
from lets_plot import *
LetsPlot.setup_html()

ggplot() + geom_rect(xmin=0, xmax=1, ymin=0, ymax=1) + \
    ggtitle('A B C D E F G H I J K L M N O P Q R S T U V W X Y Z'
            'a b c d e f g h i j k l m n o p q r s t u v w x y z')
```
<img src="https://user-images.githubusercontent.com/26162403/104721542-95ef2a00-573e-11eb-9f3b-f70e4925a4f3.png" width="400" height="300">

The problem here is not only that there is not enough space for a long title, but that the title is shifted from the center.

Even with not very long titles we face a similar situation. For example, when we put a few small plots into `GGBunch()`.

Screen from my notebook:
<img src="https://user-images.githubusercontent.com/26162403/104722430-da7ac580-573e-11eb-82ae-bc3b8145e023.png" width="400" height="300">

**Comment by alshan** [comment]
As a workaround let's align the title to the left instead of center. @OLarionova-HORIS could you take a look?

**Comment by OLarionova-HORIS** [comment]
PR: https://github.com/JetBrains/lets-plot/pull/293

**Comment by alshan** [comment]
@OLarionova-HORIS Aligning to the left of the overall plot area in not looking good: 
![image](https://user-images.githubusercontent.com/4430922/105233707-3925b200-5b38-11eb-8beb-d08e17c88b18.png)

Let's align to the left of 'geom' area inside plot. See: 
http://www.cookbook-r.com/Graphs/Titles_(ggplot2)/

**Comment by OLarionova-HORIS** [comment]
Now the title is inside the geom area of the plot.
Commit: https://github.com/JetBrains/lets-plot/commit/43c4c40c01ccb48df7277409291251e0631195eb
Result of these changes:

![image](https://user-images.githubusercontent.com/46743085/105333685-0edefd80-5be7-11eb-8957-924228dd9f93.png)
