### ISSUE TITLE
Tooltips not working for geom_segment()

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#296]
A simple illustrative example:

```python
from lets_plot import *
LetsPlot.setup_html()

data = {'x': [0, 0], 'xend': [1, 1], 'y': [0, 1], 'yend': [1, 0], 'c': ['c1', 'c2']}

ggplot(data) + \
    geom_point(aes(x='x', y='y', color='c'), \
               tooltips=layer_tooltips().line('@c')) + \
    geom_segment(aes(x='x', y='y', xend='xend', yend='yend', color='c'), \
                 tooltips=layer_tooltips().line('@c'))
```

![tooltips over geom_segment()](https://user-images.githubusercontent.com/26162403/105999539-e1022900-60be-11eb-9679-5987000f9558.gif)

**Comment by OLarionova-HORIS** [comment]
Commit: https://github.com/JetBrains/lets-plot/commit/062378e9e4d12f8b5cd263ef69bdeeb1a5fbd5dd
Tooltips will be displayed at the start and end points: 
<img width="493" alt="Screenshot 2021-03-02 at 19 15 19" src="https://user-images.githubusercontent.com/46743085/109678499-bdce0c00-7b8b-11eb-844b-cd9f3b19c32c.png">
