### ISSUE TITLE
Maximum possible value for vjust is too small

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#297]
The values of vertical text alignment (`vjust` parameter) are between 0 and 1. But 1 (maximum shift) is sometimes too small to separate points and texts. Look at the example below:

```python
from lets_plot import *
LetsPlot.setup_html()

data = {'x': [0], 'y': [0], 't': ['Point']}

ggplot(data, aes(x='x', y='y')) + \
    geom_point() + geom_text(aes(label='t'), vjust=1)
```

<img src="https://user-images.githubusercontent.com/26162403/105999838-36d6d100-60bf-11eb-8295-910a83985987.png" width="400" height="300">

I think we need either a wider range of admissible values for `vjust` or a bigger shift corresponding to the value of 1.

**Comment by alshan** [comment]
We need to support `nudge_x, nudge_y` parameters (#74). 
Also 'label.padding' may help. (https://ggplot2.tidyverse.org/reference/geom_text.html).
