### ISSUE TITLE
Support rectangle 'linetype' in geom_livemap()  

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#307]
```
geom_rect(xmin=-72, ymin=41.5, xmax=-71, ymax=42, alpha=0, color="magenta", linetype="dashed")
```

is shown with solid border.

See the last output in this demo: https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/geocoding_examples.ipynb

**Comment by IKupriyanov-HORIS** [comment]
Fixed via https://github.com/JetBrains/lets-plot/commit/dfbb83e877693e082b1a1c40b4c182574d7bea60
