### ISSUE TITLE
jcenter will be shutdown

### ISSUE THREAD

**Issue by BigMichi1** [JetBrains/lets-plot#311]
hi,
could you please also upload the artefacts to another repository, as jcenter will be shut down in some months. see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by alshan** [comment]
Yes, this is unfortunate to say least. We will do it ASAP.

**Comment by alshan** [comment]
Not using bintray since [2.0.2](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#202---2021-04-13).
