### ISSUE TITLE
add stat_summary, stat_summary_bin to ggplot

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#316]
https://ggplot2.tidyverse.org/reference/stat_summary.html

**Comment by ValdarT** [comment]
For what it's worth I quite miss this for quickly creating (bootstrapped) error bars.

**Comment by alshan** [comment]
Related: [53]

**Comment by ASmirnov-HORIS** [comment]
`stat_summary()`: #803
`stat_summary_bin()`: #810
