### ISSUE TITLE
geom_text: add support for lineheight, nudge_x, nudge_y, inward and outward

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#324]
params:
`nudge_x, nudge_y`

text alignments (hjust, vjust): 
`inward, outward`

**Comment by alshan** [comment]
Related #297

**Comment by OLarionova-HORIS** [comment]
lineheight, nudge_x/y: https://github.com/JetBrains/lets-plot/pull/613
inward, outward: https://github.com/JetBrains/lets-plot/pull/615
