### ISSUE TITLE
Bad axis labels when using both plot and layer data

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#327]
Consider the following plots:

```python
from lets_plot import *
LetsPlot.setup_html()

data1 = {
    'x': ['a', 'b', 'c'],
    'ymin': [1, 1, 2],
    'ymax': [3, 2, 3],
}
data2 = {
    'x': ['b', 'a', 'c', 'a', 'b', 'c'],
    'y': [2, 1, 3, 3, 1, 2],
}

ggplot(data1) + \
    geom_point(aes(x='x', y='y'), data=data2) + \
    geom_linerange(aes(x='x', ymin='ymin', ymax='ymax'))
```

<img src="https://user-images.githubusercontent.com/26162403/108220117-72593e00-7147-11eb-958a-69016c8f2ce9.png" width="400" height="300" />

```python
ggplot(data1) + \
    geom_point(aes(x='x', y='y'), data=data2) + \
    geom_linerange(aes(x='x', ymin='ymin', ymax='ymax')) + \
    scale_x_discrete(reverse=True)
```

<img src="https://user-images.githubusercontent.com/26162403/108219880-33c38380-7147-11eb-9e4a-dc17c4fff375.png" width="400" height="300" />

Here we see:
- Inconsistent order of axis labels for `reverse=True` when using both plot and layer data.
- Invalid axis labels when using both plot and layer data.
- Unexpected rotation of axis labels for `reverse=True` when using both plot and layer data.

**Comment by alshan** [comment]
Was fixed by recent refactorings.
