### ISSUE TITLE
Axis titles depend on order of datasets

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#333]
Look at the titles for y axis:

```python
from lets_plot import *
LetsPlot.setup_html()

data1 = {'x': [0, 1], 'y': [0, 1]}
data2 = {'s': [1], 'i': [0]}

ggplot() + \
    geom_point(aes(x='x', y='y'), data=data1) + \
    geom_abline(aes(slope='s', intercept='i'), data=data2)
```

<img src="https://user-images.githubusercontent.com/26162403/108596362-9f029500-7395-11eb-9559-129cc2dc0cda.png" width="400" height="300"/>

```python
ggplot() + \
    geom_abline(aes(slope='s', intercept='i'), data=data2) + \
    geom_point(aes(x='x', y='y'), data=data1)
```

<img src="https://user-images.githubusercontent.com/26162403/108596395-c5c0cb80-7395-11eb-98b3-17ad5b73d2af.png" width="400" height="300"/>

It seems that the axis title depends on the order of layers - each with its own data. If we do the same in ggplot2, in both cases axes will be titled "x" and "y".

**Comment by alshan** [comment]
It seems we should derive x/y axis labels from x/y aesthetics only and ignore other positional aesthetics.
If there are nothing to derive from, then just use "x", "y" labels.

See related #334

**Comment by OLarionova-HORIS** [comment]
PR: https://github.com/JetBrains/lets-plot/pull/342
