### ISSUE TITLE
geom_hline(): graph plotted outside of coordinate plane visible part

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#334]
If we try the following code:

```python
from lets_plot import *
LetsPlot.setup_html()

ggplot() + geom_hline(yintercept=1)
```

we will see only the blank plot. But if we shift our view, then it will be all right:

```python
ggplot() + geom_hline(yintercept=1) + coord_cartesian(ylim=[.5, 1.5])
```
<img src="https://user-images.githubusercontent.com/26162403/108597298-66fd5100-7399-11eb-9aef-172595b01022.png" width="400" height="300"/>

The same is true for `geom_vline()`.

**Comment by alshan** [comment]
This might be an expected behavior. What does ggplot2 show in case 1?

**Comment by ASmirnov-HORIS** [comment]
In ggplot2, the plot in case 1 looks the same as in case 2.
