### ISSUE TITLE
geom_density: The "..count.." variable is not computed correctly

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#340]
```
import numpy as np
from lets_plot import *

dat = dict(
    xs = np.random.normal(0, 10, 1000)
)

(ggplot(dat, aes(x="xs", y="..count..")) +
 geom_histogram(bins=10) +
 geom_density(n=10, color="red")).show()
```

![image](https://user-images.githubusercontent.com/4430922/109541189-85e29e00-7a91-11eb-9cd6-aff1e755d5ee.png)

The density "count" estimate is not even close to what the histogram is showing.

At the same time the "..density.." variable seem computed correctly.

**Comment by ASmirnov-HORIS** [comment]
What about to remove `bins` parameter from `geom_histogram()` and add `stat='bin'` into `geom_density()`? Now it is different statistics as I understand.

**Comment by alshan** [comment]
Yes, it seems the "..count.." computed by density stat is fine. 
What I need is to adjust these values to match the histogram values. (see https://stackoverflow.com/questions/37404002/geom-density-to-match-geom-histogram-binwitdh)
