### ISSUE TITLE
Plots not showing in SciView when remote debugging

### ISSUE THREAD

**Issue by mirbagheri** [JetBrains/lets-plot#348]
I have previously used lets-plot with my local interpreter in Scientific Mode with no problem. Switching to a remote interpreter lets-plot stopped working and my plots wont show up in SciView. Here are my system info:

PyCharm 2020.0.3.3
lets-plot python package 2.0.0
Lets-Plot in SciView plugin 1.0.9.202

**Comment by alshan** [comment]
When with remote interpreter does the other SciView functionality work? 
- dataframe explorer
- matplotlib plots

**Comment by mirbagheri** [comment]
I did not check dataframe explorer, but matplotlib plots work for me.

> When with remote interpreter does the other SciView functionality work?
> 
> * dataframe explorer
> * matplotlib plots

**Comment by alshan** [comment]
This is very bad, could you try to inject the following code AFTER `from lets_plot import *`:

```
from lets_plot.frontend_context._mime_types import LETS_PLOT_JSON
import lets_plot.frontend_context._configuration as _cfg
from lets_plot.frontend_context._intellij_python_json_ctx import IntellijPythonJsonContext

_cfg._default_mimetype = LETS_PLOT_JSON
_cfg._frontend_contexts[LETS_PLOT_JSON] = IntellijPythonJsonContext()
```

**Comment by mirbagheri** [comment]
@alshan, Thanks! I can now plot using lets_plot with the lines you provided added to my script.

**Comment by alshan** [comment]
This is great! I'll fix it in the next release, thank you for reporting.

**Comment by alshan** [comment]
hi @mirbagheri, try the latest [v2.0.1](https://github.com/JetBrains/lets-plot/releases/tag/v2.0.1) - it should work without the hack.

**Comment by mirbagheri** [comment]
@alshan, Yes! v2.0.1 is now working seamlessly for me.
