### ISSUE TITLE
Plugin not compatible with PyCharm 2021.1

### ISSUE THREAD

**Issue by mirbagheri** [JetBrains/lets-plot#360]
I cannot use the plugin after updating PyCharm to 2021.1 version. I get the following error at the startup of the IDE:

Plugin error: Plugin 'Lets-Plot in SciView' (version '1.0.10.202') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PY-211.6693.115

Plugin version: 1.0.10.202
Let's plot python library version: 2.0.2

**Comment by alshan** [comment]
Hi @mirbagheri , thank you for reporting this issue. 
Please try the latest plugin v1.0.11. It's compatible with PyCharm 2021.1.

**Comment by mirbagheri** [comment]
@alshan Thanks for the quick response. The update resolved the issue. Do you know why that update did not show up in my plugin updates? I frequently check plugin updates manually via "Check for Updates" options in the PyCharm menu.

**Comment by alshan** [comment]
You didn't see updates because there were none ) I've just uploaded this v1.0.11 where the compatibility range was extended. Your feedback was very timely.

**Comment by mirbagheri** [comment]
@alshan Thanks for the clarification! With the fix in the update, I assume the issue could be closed.
