### ISSUE TITLE
LetsPlot.setup_html() in pycharm jupyter has no ouput

### ISSUE THREAD

**Issue by robertdefilippi** [JetBrains/lets-plot#363]
Hi,

I'm using pyCharm to run a jupyter server, and wanted try out `let_plot` and I'm having issues getting the package to renger images. I find this odd, because I can render images from plotly, matplotlib, etc.

Here is the code I'm running:

```
import numpy as np
from lets_plot import *
LetsPlot.setup_html()

np.random.seed(12)
data = dict(
    cond=np.repeat(['A','B'], 200),
    rating=np.concatenate((np.random.normal(0, 1, 200), np.random.normal(1, 1.5, 200)))
)

ggplot(data, aes(x='rating', fill='cond')) + ggsize(500, 250) \
+ geom_density(color='dark_green', alpha=.7) + scale_fill_brewer(type='seq') \
+ theme(axis_line_y='blank')
```

Here is the output in pyCharm:
![image](https://user-images.githubusercontent.com/9288605/116012168-f374fb80-a5f6-11eb-818d-ceb9473f7720.png)

However, if I run a jupyter server outside of pycharm the rendering does occur, so I'm not sure what the issue is in pycharm.

![image](https://user-images.githubusercontent.com/9288605/116012474-a4c86100-a5f8-11eb-8ff3-563ee09143ae.png)

Config:
```❯ pip freeze | grep lets-plot 
lets-plot==2.0.2

PyCharm 2021.1.1 (Professional Edition)
Build #PY-211.7142.13, built on April 21, 2021
macOS 10.15.7
```

I don't think this is my version of pyCharm, because I also tried the same code on version 2020.3.5 and still no output.

Any help would be greatly appreciated.

Thanks,

**Comment by alshan** [comment]
Hi, this might happen when the notebook is not "trusted" - see the checkbox in the editor header to the right.
![image](https://user-images.githubusercontent.com/4430922/116092550-e3e7c800-a673-11eb-9768-bfa7c93201e0.png)

I also noticed, that "Run All" button does nothing in "Preview only" mode - make sure you are in the "Editor & Preview" mode.

**Comment by robertdefilippi** [comment]
So that's really odd. I enabled "Trusted" for a notebook, and it still did not work. However, I enabled it in another and it _did work_.

I'm really confused now.

**Comment by alshan** [comment]
From my experience, it doesn't take effect immediately but closing the notebook and reopening it helps.

**Comment by robertdefilippi** [comment]
Just confirming @alshan that your suggestion worked. Thanks for helping me through this.
