### ISSUE TITLE
Poor font rendering within SciView

### ISSUE THREAD

**Issue by arthurire** [JetBrains/lets-plot#364]
I'm using a remote python on my server (Ubuntu 20 LTS, Python 3.8), everything works fine in Jupyter Notebook in web browser.

However if I use Sentific Mode and SciView instead, fonts in SciView seems rendering poorly.

In Jupyter Notebook (Chrome 81)
![image](https://user-images.githubusercontent.com/27836456/116208781-d6b20280-a773-11eb-86e7-8cd433f3844f.png)

In PyCharm SciView (PyCharm 2021.1.1, Mac Mini M1)
![image](https://user-images.githubusercontent.com/27836456/116209970-0281b800-a775-11eb-99d9-16c2654c6498.png)

Here's the code to replicate this plot (copied from plugin homepage)

    import numpy as np
    from lets_plot import *
    LetsPlot.setup_html()
    np.random.seed(12)
    data = dict(
        cond=np.repeat(['A','B'],200),
        rating=np.concatenate((np.random.normal(0,1,200),np.random.normal(1,1.5,200)))
    )
    p = ggplot(data,aes(x='rating',fill='cond')) + ggsize(500,250)\
        + geom_density(color='dark_green',alpha=.7)+ scale_fill_brewer(type='seq')\
        + theme(axis_line_y='blank') 
    p.show()

**Comment by arthurire** [comment]
Rendering quality does not change with the size of the image or window.

**Comment by alshan** [comment]
You are right, the characters look terrible, I'll have to look at it.
Saving png via the menu on the tab should give you better quality.

**Comment by alshan** [comment]
@arthurire could you check out the latest [Lets-Plot-in SciView](https://plugins.jetbrains.com/plugin/14379-lets-plot-in-sciview) v1.1.0 ? 

The font rendering quality should be a lot better now.

**Comment by arthurire** [comment]
> @arthurire could you check out the latest [Lets-Plot-in SciView](https://plugins.jetbrains.com/plugin/14379-lets-plot-in-sciview) v1.1.0 ?
> 
> The font rendering quality should be a lot better now.

Hi Alshan,

Sorry for the late reply. Font rendering quality is a lot better.

I'll close this issue. Thank you!
