### ISSUE TITLE
Exclude slf4j implementation from lets-plot-common

### ISSUE THREAD

**Issue by KiperUladzislau** [JetBrains/lets-plot#374]
Is it possible to exclude "org.slf4j:slf4j-simple" implementation of SLF4J logger as it's considered to be a bad practice to include concrete implementations for logger API?

**Comment by alshan** [comment]
This is good point, thanx.

**Comment by alshan** [comment]
Fixed in Lets-Plot v2.0.3, Lets-Plot Kotlin v3.0.0
