### ISSUE TITLE
geocoding: ValueError: No objects were found for Munich

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#379]
```
gcoder = geocode_cities("Munich").countries("Germany")
```
> ValueError: No objects were found for Munich.

```
gcoder = geocode_cities("München").countries("Germany")
```
Doesn't work as expected either: finds some area near Munich.

**Comment by IKupriyanov-HORIS** [comment]
Fixed with geocoding data update.

```
gcoder = geocode_cities("Munich").countries("Germany")
gcoder.get_geocodes()
```

Out:
id | city | found name | country
-- | -- | -- | --
1700534808 | Munich | München | Germany


```
gcoder = geocode_cities("München").countries("Germany")
gcoder.get_geocodes()
```

Out:
id | city | found name | country
-- | -- | -- | --
1700534808 | München | München | Germany
