### ISSUE TITLE
Question: creating scatterplots with marginal histograms?

### ISSUE THREAD

**Issue by robertdefilippi** [JetBrains/lets-plot#384]
Hey,

I'm just wondering if creating scatterplots with marginal histograms is currently possible in `lets-plot` ?

![image](https://user-images.githubusercontent.com/9288605/120663825-62483e80-c458-11eb-9500-577d567dcf72.png)

More examples here:
https://stackoverflow.com/questions/8545035/scatterplot-with-marginal-histograms-in-ggplot2

Thanks

**Comment by alshan** [comment]
Hi, this is not possible in Lets-Plot currently but it seems like very useful visualization and we certainly have to provide it. Will rise the priority.

**Comment by robertdefilippi** [comment]
Oh great, and thanks for the quick response @alshan!

**Comment by alshan** [comment]
Hi, @robertdefilippi 
We've added `ggmarginal()` in v2.4.0: https://github.com/JetBrains/lets-plot#marginal-plots
