### ISSUE TITLE
tooltip format() should understand date-time format pattern

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#387]
```
tooltips=layer_tooltips().format("Date", "{%y}")
```

returns error:

> Wrong number pattern: %y

```
tooltips=layer_tooltips().format("Date", "%y")
```

returns error:

> Wrong number of arguments in pattern '%y' to format 'Date'. Expected 1 argument instead of 0

**Comment by OLarionova-HORIS** [comment]
Related #392:
adding date-time format support to `class StringFormat` will solve both issues.

**Comment by OLarionova-HORIS** [comment]
Added: https://github.com/JetBrains/lets-plot/pull/421
