### ISSUE TITLE
Formatting: ".1s" pattern is not working as expected

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#390]
It yields a round number like: "41M"

Expected: "40.7M"

**Comment by IKupriyanov-HORIS** [comment]
SI format works in a different way - the number in a format string is the number of significant digits in the output, including both  integer and fraction parts of a number (we were inspired by the `d3.format` library, you can try it [here](http://bl.ocks.org/zanarmstrong/05c1e95bf7aa16c4768e)).  

This is how lets-plot formats number 40_691_000:
> ".1s" => "41M"
> ".2s" => "41M"
> ".3s" => "40.7M"
> ".4s" => "40.69M"
