### ISSUE TITLE
formatting: scale_x_datetime should apply date-time formatting to the breaks

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#392]
```
t = pd.to_datetime("2021-01-01")
(ggplot() 
  + geom_vline(xintercept=t)
  + scale_x_datetime(format="%d %b\'%y"))
```
works as expected:
![image](https://user-images.githubusercontent.com/4430922/121727416-dff3f600-cab9-11eb-810f-c2c82ec114e7.png)

Scale with 'breaks' doesn't work:
```
(ggplot() 
  + geom_vline(xintercept=ut)
  + scale_x_datetime(format="%d %b\'%y", breaks=[t]))
```
![image](https://user-images.githubusercontent.com/4430922/121727676-34977100-caba-11eb-9842-792794d07c94.png)

```
(ggplot() 
  + geom_vline(xintercept=ut)
  + scale_x_datetime(format="{%d %b\'%y}", breaks=[t]))
```

> Wrong number pattern: %d %b'%y

```
(ggplot() 
  + geom_vline(xintercept=t)
  + scale_x_datetime(breaks=[t]))
```

![image](https://user-images.githubusercontent.com/4430922/121727771-58f34d80-caba-11eb-87e8-2708b3ba0488.png)

After converting pandas Timestamp to "UNIX time" It doesn't work either:
```
# UNIX time (delta from UNIX epoch in ms)
ut = (pd.to_datetime("2021-01-01") - pd.Timestamp("1970-01-01")) // pd.Timedelta("1ms")

(ggplot() 
  + geom_vline(xintercept=ut)
  + scale_x_datetime(breaks=[ut]))
```

![image](https://user-images.githubusercontent.com/4430922/121727986-a8397e00-caba-11eb-9e48-6fcc0751a559.png)

**Comment by OLarionova-HORIS** [comment]
Applying date-time formatting to breaks works now: 
https://github.com/JetBrains/lets-plot/pull/421 - date-time format support was added to StringFormat.
