### ISSUE TITLE
tooltip on y-axis looks wrong

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#393]
![image](https://user-images.githubusercontent.com/4430922/121781525-35400e00-cb73-11eb-87c2-5e290c572517.png)

.. I'll add the code example later.

**Comment by alshan** [comment]
In this notebook: [COVID-19 in India: EDA and Spatial Visualization](https://www.kaggle.com/alshan/covid-19-in-india-eda-and-spatial-visualization)

**Comment by OLarionova-HORIS** [comment]
Could you please clarify what is the expected result? Should match the axis label?

**Comment by alshan** [comment]
I meant "y-axis", sorry. I was using:
```
scale_y_continuous(format="{} %")
```
and expected the value being formatted using default formatter. The only difference would be the added suffix: ' %'

**Comment by alshan** [comment]
When I try to fix tooltip formatting via `layer_tooltips().format('@Y', '{.1f}%')` , it has no effect.

If I format y-axis: `scale_y_continuous(format="{.0f} %")` , then the y-axis tooltip shows only integer part (expected to see tenths).

**Comment by OLarionova-HORIS** [comment]
Now the tooltip format() does not apply to the axis tooltip. But should it be applied? Then the `field='^y'` will apply for y-axis tooltip and `'^Y'` - for all positional including y-axis. 
And tenths will be displayed in the case of `layer_tooltips().format('^y', '{.1f}%')`.

**Comment by alshan** [comment]
I think yes, "^y" and "@Y" should include "y" aesthetic no matter in which tooltip.

The 2nd part in this issue is that  using `scale_y_continuous(format="{} %")` shouldn't change y-axis tooltip formatting.

**Comment by alshan** [comment]
> using scale_y_continuous(format="{} %") shouldn't change y-axis tooltip formatting.

Expected the same behavior as in this notebook: https://nbviewer.org/github/JetBrains/lets-plot-docs/blob/master/source/examples/cookbook/formatting_axes_etc.ipynb

See Out[6]

**Comment by OLarionova-HORIS** [comment]
The first path of the issue - applying `format()` to the axis tooltip: https://github.com/JetBrains/lets-plot/pull/473

**Comment by OLarionova-HORIS** [comment]
Add changes https://github.com/JetBrains/lets-plot/pull/483 - the scale format is applied to tick labels only.

The rules now are as follows:
    - the scale's `format` parameter is applied to tick labels only and does not affect tooltips;
    - the tooltip `format()` is also applied to the axis tooltip;
    - if the tooltip `format()` is not specified, the tooltip will get the value after applying the default formatting from the scale (without using the specified format for the scale).

So the following settings
`layer_tooltips().format("^Y", "{.1f} %")`  -- tooltip
+
 `scale_y_continuous(format="{} %")`  -- ticks
will give the result:

<img width="169" alt="Screenshot 2021-11-25 at 19 22 23" src="https://user-images.githubusercontent.com/46743085/143475629-6853fe7a-778b-4ecf-bd32-b7a7837d3fe9.png">
