### ISSUE TITLE
element_text() not implemented yet? 

### ISSUE THREAD

**Issue by schakalakka** [JetBrains/lets-plot#396]
element_text() does not seem to be implemented yet. 
But element_blank() is. 

Changing the axis size is not possible for now.

**Comment by alshan** [comment]
That's right, currently there is no way to adjust the axis style.

**Comment by alshan** [comment]
Hi, in [v2.2.0](https://github.com/JetBrains/lets-plot#what-is-new-in-220) `element_text()` was added but without ability to modify font size, family or face. However, we've increased the default font size so the need for adjustments is less pressing now.

Changing axis size (i.e. the line thickness) is now possible, if that is what you meant.

**Comment by alshan** [comment]
Font `size, family, face` as well as `hjust, vjust` and `margin` parameters were added in [v2.5.0](https://github.com/JetBrains/lets-plot#what-is-new-in-250).
