### ISSUE TITLE
Axis value font size

### ISSUE THREAD

**Issue by permiakover** [JetBrains/lets-plot#400]
Hello, new to let-plot, is it possible to change the font size for axes values?

**Comment by alshan** [comment]
At the moment this is not possible unfortunately. Is is too small?

**Comment by permiakovsa** [comment]
for the purpose of paper preparing - yes, it is rather small

**Comment by alshan** [comment]
Added in [v2.5.0](https://github.com/JetBrains/lets-plot#what-is-new-in-250).
