### ISSUE TITLE
Pie chart in python

### ISSUE THREAD

**Issue by pwwang** [JetBrains/lets-plot#423]
I don't find any way to plot a pie chart in python.

I see it's implemented in kotlin (#40), but not yet in python.

Is there a plan to implement `geom_pie` or `coord_polar` in python?

**Comment by alshan** [comment]
This is something what is not available in either Lets-Plot APIs ( 

We are planning for `coord_polar`. Meanwhile may be you could workaround by coding pie with the help of `geom_polygon()`? See: [#68](https://github.com/JetBrains/lets-plot-kotlin/issues/68)

**Comment by alshan** [comment]
geom_pie added in [v3.0.0](https://github.com/JetBrains/lets-plot#what-is-new-in-300)
