### ISSUE TITLE
not working in Jupyter Notebook 

### ISSUE THREAD

**Issue by antonio-yu** [JetBrains/lets-plot#429]
When making the graphics ,only return a result like 

> <lets_plot.plot.core.PlotSpec at 0x26c5606c6a0>

**Comment by antonio-yu** [comment]
I tried the example in Jupyter 
```
import numpy as np
from lets_plot import *
LetsPlot.setup_html()

np.random.seed(12)
data = dict(
    cond=np.repeat(['A','B'], 200),
    rating=np.concatenate((np.random.normal(0, 1, 200), np.random.normal(1, 1.5, 200)))
)

ggplot(data, aes(x='rating', fill='cond')) + ggsize(500, 250) \
+ geom_density(color='dark_green', alpha=.7) + scale_fill_brewer(type='seq') \
+ theme(axis_line_y='blank')
```

It didn't work.

**Comment by alshan** [comment]
Could you try to store plot in a variable:
```
p = ggplot(data, ....
```

and then try:
```
p.show()
```

Also try:
```
from IPython.display import display

display(p)
```

what does it say?

If it doesn't say anything, please look at the browser's console. Are there any error messages related to lets-plot?

**Comment by antonio-yu** [comment]
> Could you try to store plot in a variable:
> 
> ```
> p = ggplot(data, ....
> ```
> 
> and then try:
> 
> ```
> p.show()
> ```
> 
> Also try:
> 
> ```
> from IPython.display import display
> 
> display(p)
> ```
> 
> what does it say?
> 
> If it doesn't say anything, please look at the browser's console. Are there any error messages related to lets-plot?

Thanks for replying. 
In my another new computer, it works well in all ways.  
Maybe it's the `version` problem  between Python and Lets_plot.    

Old PC, python  version 3.8.3 , lets_plot 2.0.4 works, lets_plot 2.1.0 doesn't work;
New PC, python version 3.8.8, lets_plot 2.1 works.

**Comment by alshan** [comment]
Very good you decided to ditch your old PC. )
