### ISSUE TITLE
Feature request: coord_polar

### ISSUE THREAD

**Issue by PoslavskySV** [JetBrains/lets-plot#452]
Hi guys, 

thanks for your awesome work! Are there any plans to implement `coord_polar` ?

Best,
Stas

**Comment by alshan** [comment]
This is a useful feature (and already was requested https://github.com/JetBrains/lets-plot/issues/423) but not easy to implement. If possible we will try to add it in Q4.

Thanx for feedback!

**Comment by alshan** [comment]
Hi @PoslavskySV , `coordPolar()` was just added in [v4.7.0](https://github.com/JetBrains/lets-plot-kotlin?tab=readme-ov-file#coordpolar).
