### ISSUE TITLE
Heatmap: geomTile() + coordFixed() strange result

### ISSUE THREAD

**Issue by PoslavskySV** [JetBrains/lets-plot#453]
Hi guys,

thanks for the great instrument! I have an issue with `geomTile()` in a combination of `coordFixed()` on which I stuck for more than a day already. I would very much appreciate any your help. 

The code:

```kotlin
val data = DataFrame.readCSV("https://raw.githubusercontent.com/PoslavskySV/scratch/master/lets-plot-heatmap/data1.csv")
val mData = data.head(1000).toMap()
var plot = letsPlot(mData) {
    x = "sample"
    y = "gene"
    fill = "weight"
} + geomTile(color = "white") + coordFixed()
```

In R this will give you a nicely looking plot, but here you get:

![image](https://user-images.githubusercontent.com/3834261/136115365-f0d5dd80-120c-4557-8543-7dffc236098a.png)

You can try to add some `ggsize()`, but which sizes to choose - is there any way to do this automatically? We are trying to use lets-plot as a part of automated data analysis pipeline which generates plots automatically,  so there is no option to manually adjust ggsize for each particular plot. Lets pick some values and try:

```kotlin
val plot = letsPlot(mData) {
    x = "sample"
    y = "gene"
    fill = "weight"
} + geomTile(color = "white") +
        scaleXContinuous(expand = listOf(0.0, 0.0)) +
        scaleYContinuous(expand = listOf(0.0, 0.0)) +
        coordFixed() +
        ggsize(375, 2850)
```

The result will not look great: 

![psapopierdolilo](https://user-images.githubusercontent.com/3834261/136115590-b1a4236f-fb0f-42eb-b7a3-b788349d48c6.png)

Is there any way to get rid of these white spaces? Note that I've specifically added `expand = listOf(0.0, 0.0)` which gave no effect.

If you try `coordCartesian` there will be no whitespaces, but this will give undesired non-square cells.

PS. In R, the first code snippet will give you the following result (thats what I'm trying to achieve):

![ggplot2](https://user-images.githubusercontent.com/3834261/136116495-36436f67-6afc-4794-b5a0-2f18d64b9c66.png)

**Comment by alshan** [comment]
Hi Stanislav!
In [3.1.1](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v3.1.1) the issue with incorrect plot layout when using `coord_fixed()` has been fixed. (https://github.com/JetBrains/lets-plot/issues/478).

**Comment by PoslavskySV** [comment]
Hi Igor! Thank you for letting me know. Meanwhile we are working on dendrograms (still in private) and we'll make a PR in a couple of weeks.
