### ISSUE TITLE
Ordering facets

### ISSUE THREAD

**Issue by essicolo** [JetBrains/lets-plot#454]
Hi,

Is there a way to order facets? For example, I load the daily minimum temperatures in Melbourne in the aim of plotting the temperature per month.

```
import numpy as np
import pandas as pd
import lets_plot as lp
lp.LetsPlot.setup_html()

temp = pd.read_csv("https://raw.githubusercontent.com/jbrownlee/Datasets/master/daily-min-temperatures.csv")
temp.Date = pd.to_datetime(temp.Date)
temp = temp.assign(
    year = temp.Date.dt.year,
    month = temp.Date.dt.month_name(),
    day = temp.Date.dt.day
)
```

In R-ggplot, the ordering can be based on ordinal factors. So I ordered the `month` column.

```
from pandas.api.types import CategoricalDtype
months = pd.date_range(start='1900-01', freq='M', periods=12).month_name()
month_cat = CategoricalDtype(months, ordered=True)
temp = temp.assign(month = temp.month.astype(month_cat), year = temp.year.astype(str))
```

It seems that let's-plot doesn't consider the order.

```
lp.ggplot(temp, lp.aes(x = 'day', y = 'Temp')) +\
    lp.geom_line(lp.aes(colour = 'year')) +\
    lp.facet_wrap(facets = 'month')
```

<img width="1070" alt="Capture d’écran, le 2021-10-06 à 10 32 38" src="https://user-images.githubusercontent.com/5118227/136224142-af505bc3-645e-419b-89d2-9cdc67af39ce.png">

Edit: I used a better example with temperatures rather than CO2.

**Comment by alshan** [comment]
Unfortunately you seem to be right: lets-plot ignores the original order and sorts values one way or another. Certainly must be fixed.
All you can do right now is to change values so what they are sorted in the desired order, i.e. : "January" --> "01-Jan" and so on.
