### ISSUE TITLE
Select better labels for datatime axis

### ISSUE THREAD

**Issue by vlsi** [JetBrains/lets-plot#470]
```kotlin
val data = mapOf(
     "time" to doubleArrayOf(0.0, 90*60*1000.0, 2*90*60*1000.0) , 
    "rate" to doubleArrayOf(0.0, 50.0, 250.0) 
)
 val plot = letsPlot(data) + geomLine { x = "time"; y = "rate" } +
         scaleXDateTime("Time", expand = listOf(0, 0))
```

Output:
<img width="786" alt="time chart" src="https://user-images.githubusercontent.com/213894/139594276-f11e261c-5c90-4363-8235-8d6b9325742e.png">

Note how labels are duplicated, and it is hard to tell which means what

The very first label should probably include more time units.

**Comment by IKupriyanov-HORIS** [comment]
Hello! Could you clarify what output exactly do you expect. Something like "0:00" ... "0:45" ... "1:15" ... "2:45" etc? Isn't this issue similar to #468, or there are differences?

**Comment by vlsi** [comment]
This is similar, yet the difference is "absolute time" vs "relative time".

"relative time" is "time since test started". In other words, the time starts at 0, and then goes to 1h, 2h, ... 1d, 2d, ...

"absolute time" is like "suppose the test would start right now". Then the chart should show something like 2021-11-16 19:00, then 2021-11-16 20:00, then ... 2021-11-17 ... and so on.

The issue with the very first comment is that lets-plot used "15 minute" intervals between ticks on the axis, however it should have been included hours when they change.

I would expect:
* 15min ticks look reasonable for this scale
* So I would expect that minor ticks should include hours, not just minutes. For instance, `hh24:mm` format would be reasonable
* I would expect a full date at the very beginning of the horizontal axis, so it would be possible to understand what the timestamps mean
* I would expect month+date instead of 00:00 ticks, so it is clear when the new day starts

Does that make sense?

**Comment by IKupriyanov-HORIS** [comment]
Thank you for clarification! Yes, it does make sense. Will check how we can fix this issue.

**Comment by alshan** [comment]
Hi @vlsi , we've added `scaleXTime()` suited for 'time delta" values (in milliseconds). The "time delta" is close to what you call "relative time" except it is always relative to 0. 
I.e. it doesn't show a date in the origin and you will have to show this date somewhere else (axis title for example).

Would `scaleXTime()` work for you. 
See an example notebook: https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/scale_time.ipynb

**Comment by vlsi** [comment]
I wonder if you considered referencing the notebooks in the javadocs :)

So far `scaleXTime()` works for me. Thanks for the fix.


The output for `10000 days` duration is weird, however, I think all the reasonable inputs in my case would be less than "1 month".

<img width="858" alt="Снимок экрана 2021-12-14 в 21 06 40" src="https://user-images.githubusercontent.com/213894/146055069-cc7deaee-c058-43ac-b4e3-b995fd5c2650.png">

**Comment by alshan** [comment]
> I wonder if you considered referencing the notebooks in the javadocs :)
Might be a good idea!

> The output for 10000 days duration is weird,
Did you provide the scale breaks or these are auto-generated breaks?

**Comment by vlsi** [comment]
>Did you provide the scale breaks or these are auto-generated breaks?

The breaks are auto-generated.

**Comment by vlsi** [comment]
The code is https://github.com/apache/jmeter/pull/681/files#diff-e183a156e38694ea6a9982456cb0aba18376055825b4cdedbfe7a8269c6ce7b0R127-R130

I probably need to learn to create notebooks.

**Comment by alshan** [comment]
Definitely looks like an issue: https://github.com/JetBrains/lets-plot/issues/494

Does the "time" series contain negative values (as shown on the axis)?

**Comment by vlsi** [comment]
The data is `time=[0.0, 8.64E11]`, `value=[1, 1]`

-336d appears there because I forgot to include `, expand = listOf(0, 0)` before taking the screenshot.

**Comment by alshan** [comment]
@vlsi  I'm closing this issue: we will consider improvements in javadocs that you proposed and #494 remains open of course.
