### ISSUE TITLE
Please bundle LICENSE file to the published jar artifacts

### ISSUE THREAD

**Issue by vlsi** [JetBrains/lets-plot#472]
org.jetbrains.lets-plot:plot-config-portable-jvm:2.2.0 says it is MIT-licensed, however,
1) It references an invalid license: https://opensource.org/licenses/MIT. The thing is there's no generic text for MIT license, and the actual uses of MIT always customize copyright owner and copyright year, so all "MIT licenses" are *different*.

2) License text might vary over time (e.g. copyright owners might vary), so the ones who bundle MIT-licensed software need to carefully follow the exact license text for the particular version. For instance, if Apache JMeter bundles `lets-plot`, then MIT license requires that `copyright notice shall be included in all copies or substantial portions of the Software`. In other words, it requires to include the copy of the license *with the appropriate copyright notice*.

I would suggest including the license text as `META-INF/LICENSE` so the ones who consume (and redistribute) the jar know the license for the given artifact.

Here is the list of the artifacts without a corresponding license file:

  * org.jetbrains.lets-plot:lets-plot-kotlin-jvm:3.1.0
  * org.jetbrains.lets-plot:lets-plot-common:2.2.0
  * org.jetbrains.lets-plot:plot-config-portable-jvm:2.2.0
  * org.jetbrains.lets-plot:plot-builder-portable-jvm:2.2.0
  * org.jetbrains.lets-plot:plot-base-portable-jvm:2.2.0
  * org.jetbrains.lets-plot:plot-common-portable-jvm:2.2.0
  * org.jetbrains.lets-plot:vis-svg-portable-jvm:2.2.0
  * org.jetbrains.lets-plot:base-portable-jvm:2.2.0

**Comment by VDovidaytis-HORIS** [comment]
#490

**Comment by alshan** [comment]
Hi @vlsi, 
The LICENSE file is now added to all jars. Please, check out the latest lets-plot v2.2.1 and lets-plot-kotlin v3.1.1.

**Comment by vlsi** [comment]
Thanks, 2.2.1 and 3.1.1 include the licenses indeed.
