### ISSUE TITLE
facetWrap should support scales argument

### ISSUE THREAD

**Issue by holgerbrandl** [JetBrains/lets-plot#479]
See https://ggplot2.tidyverse.org/reference/facet_wrap.html for use-case and API examples.

I'm doing this with [kravis](https://github.com/holgerbrandl/kravis) at the moment to produce plots in kalasim (https://www.kalasim.org/resource/#timeline)  such as
![image](https://user-images.githubusercontent.com/200952/142731971-b6a16787-2e22-403f-8b53-f107117e4207.png)
which I'd love to also support via lets-plot-jvm. This can't work without `scales` as the sub-plots don't share the same range.

**Comment by alshan** [comment]
The `scales` parameter is implemented in [v3.2.0](https://github.com/JetBrains/lets-plot-kotlin#what-is-new-in-320).
