### ISSUE TITLE
Is there a way to customize plot background (all the background) in JVM?

### ISSUE THREAD

**Issue by vlsi** [JetBrains/lets-plot#485]
I see `BACKDROP_COLOR = "white"`, however I do not see the way to customize it via themes.

https://github.com/JetBrains/lets-plot/blob/422d3081ee0ca2a958ea0c1ae1a527cbb2ce825d/plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/presentation/Defaults.kt#L32

I want to make the chart look well for themes like https://github.com/weisJ/darklaf#screenshots, and it looks like the white background for dark themes is not suitable.

Is there a way to adjust the background?

**Comment by alshan** [comment]
At the moment there is no way to do that. ggplot2 theme has `plot.background` parameter which we are missing. I'll take a look.

**Comment by alshan** [comment]
Hi, in [3.1.1](https://github.com/JetBrains/lets-plot-kotlin/releases/tag/v3.1.1)  I've aded `plotBackground, legendBackground` theme parameters (both - elemRectangle). 
This should allow you to configure plot themes matching darklaf.
