### ISSUE TITLE
Feature request: geom_dotplot

### ISSUE THREAD

**Issue by PoslavskySV** [JetBrains/lets-plot#498]
It will be great to have a `geom_dotplot` similar to [ggplot2](https://ggplot2.tidyverse.org/reference/geom_dotplot.html). Are there any plans to support it?

**Comment by alshan** [comment]
Hi Stanislav, do you use (or are planning to use) the parameters combo: 
`method="dotdensity", binpositions="all"`?

We found out that `binpositions="all"` doesn't play very well with the way we are currently computing statistics in Lets-plot.

**Comment by PoslavskySV** [comment]
Hi Igor,

no, we are not using this combo and not planning to use (at least as far as I can imagine). Thanks!

Stanislav
