### ISSUE TITLE
Multiple color/fill scales

### ISSUE THREAD

**Issue by PoslavskySV** [JetBrains/lets-plot#501]
Dear colleagues, 

Is there any way to use multiple color/fill scales on the same plot like [ggnewscale](https://github.com/eliocamp/ggnewscale) or [relayer](https://github.com/clauswilke/relayer)? I'm trying to implement a heat map with additional color key, like this one:

![image](https://user-images.githubusercontent.com/3834261/149625261-2d5ba7bd-794c-42bd-aa6f-d0107dbe4750.png)

How can I make the left-most column use different pallet and add it to the legend?

Thank you in advance,
Stanislav

**Comment by alshan** [comment]
Hi, you can't create two 'fill' scales on one plot, but in the case of monochromatic heat map you can try to use the  'alpha' aesthetic to achieve similar effect. Then the second layer could use the 'fill' aesthetic.

**Comment by PoslavskySV** [comment]
Thank you, Igor, for the explanation!
