### ISSUE TITLE
No 3.10 wheel

### ISSUE THREAD

**Issue by larsoner** [JetBrains/lets-plot#505]
Python was released on Oct 04, 2021. It would be great if there were a 3.10 wheel up on PyPi!

**Comment by VDovidaytis-HORIS** [comment]
#529

**Comment by schakalakka** [comment]
Does it mean that it is currently not possible to install lets-plot with python 3.10? 
Because I get the error message 

> ERROR: Could not find a version that satisfies the requirement lets-plot (from versions: none)
ERROR: No matching distribution found for lets-plot

when I try to do `pip install lets-plot`

**Comment by alshan** [comment]
That's correct, the 3.10 support is only coming in the next release of lets-plot.
