### ISSUE TITLE
geomText with facetWrap breaks y axis limits (bug?)

### ISSUE THREAD

**Issue by PoslavskySV** [JetBrains/lets-plot#513]
Dear team,

consider the following example of a box plot with facets and some text on it:
```kotlin
val data = mapOf(
    "x" to listOf("A", "B", "A", "B", "A", "B", "A", "B", "A", "B", "A", "B"),
    "f" to listOf("C", "D", "D", "C", "C", "D", "D", "C", "C", "D", "D", "C"),
    "y" to listOf(101, 102, 103, 104, 105, 106, 111, 112, 113, 114, 115, 116),
)

var plt = ggplot(data) { x = "x"; y = "y" }
plt += geomBoxplot()
plt += facetWrap(facets = "f", nrow = 1)

// add text at a specific position on the plot
val txt = mapOf(
    "x" to listOf("A"),
    "f" to listOf("C"),
    "y" to listOf(120),
    "l" to listOf("AC"),
)

plt += geomText(
    data = txt,
    color = "black",
    size = 2.0,
    sizeUnit = "y",
    hjust = 1.0,
) {
    label = "l"
}
```

As result, I get the plot with broken y axis limits (setting `ylims` has no effect) :

![image](https://user-images.githubusercontent.com/3834261/154072425-05051296-d19d-4f26-84d1-08fae43c13f3.png)

Without `geomText(...)` OR if e.g. `txt` data contain all x-points (which doesn't work in my case, since I want to add a single text at a specific place): 
```kotlin
val txt = mapOf(
    "x" to listOf("A", "B", "A", "B"),
    "f" to listOf("C", "D", "D", "C"),
    "y" to listOf(120, 120, 120, 120),
    "l" to listOf("AC","BD", "AD", "BC")
)
```

y axis limits are correct:

![image](https://user-images.githubusercontent.com/3834261/154073386-df24777e-d6e5-4468-84d5-75e1b771aeb8.png)

Is there any workaround to avoid this behaviour?

**Comment by alshan** [comment]
Hi, after some experimentation I've found that a single additional NULL D-point does the job: 

```
val txt = mapOf(
    "x" to listOf("A", null),
    "f" to listOf("C", "D"),
    "y" to listOf(120, null),
    "l" to listOf("AC", null),
)

```

But this needs further investigation.

**Comment by PoslavskySV** [comment]
Thank you, Igor, for the workaround!

I found another example to reproduce the problem, without facetWrap, just add empty text layer:

```kotlin
val data = mapOf(
    "x" to listOf("A", "B", "A", "B", "A", "B", "A", "B", "A", "B", "A", "B"),
    "y" to listOf(101, 102, 103, 104, 105, 106, 111, 112, 113, 114, 115, 116),
)

var plt = ggplot(data) { x = "x"; y = "y" }
plt += geomBoxplot { fill = "x" }
plt += geomText(
    data = mapOf(
        "x" to emptyList<Any>(),
        "y" to emptyList(),
        "l" to emptyList(),
    )
) {
    label = "l"
}
```

![image](https://user-images.githubusercontent.com/3834261/154337262-aa19092b-9591-42b6-bd5c-894f25bf5f80.png)

**Comment by alshan** [comment]
Yes, it looks similar.
