### ISSUE TITLE
Add horizontal segment for boxplot whiskers and option to control its size

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/lets-plot#549]
Result should look like combination of `boxplot` and `errorbar`:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/14200189/176171708-f0891f8f-6ea1-41c5-a2e9-78f5c31f0c8d.png">

**Comment by OLarionova-HORIS** [comment]
PR: https://github.com/JetBrains/lets-plot/pull/578
