### ISSUE TITLE
Feature request: ability to specify font size, family, hjust and vjust for element_text()

### ISSUE THREAD

**Issue by PoslavskySV** [JetBrains/lets-plot#562]

**Comment by OLarionova-HORIS** [comment]
@PoslavskySV 
For which elements are these parameters planned to be used first?
I mean, maybe it's ok to implement for all titles first (plot title, subtitle, caption, legend and axis titles), and for axis tick labels do it later.

**Comment by PoslavskySV** [comment]
Super sorry for late reply. Yes, I meant precisely for titles, not for ticks. Thanks!

**Comment by alshan** [comment]
Added in [v4.1.0](https://github.com/JetBrains/lets-plot-kotlin#what-is-new-in-410) Lets-Plot Kotlin API.
