### ISSUE TITLE
latitude and longitude are transposed in `geom_livemap` example

### ISSUE THREAD

**Issue by mikemac-n0** [JetBrains/lets-plot#568]
The `geom_livemap` python docs page ([ref](https://lets-plot.org/pages/api/lets_plot.geom_livemap.html#lets_plot.geom_livemap)) gives an example showing the path between New York and Singapore. In the example, the following data are presented:

```
data = {
    'city': ['New York City', 'Singapore'],
    'lat': [-73.7997, 104.0012],
    'lon': [40.6408, 1.3256],
}
```

This would suggest that the latitude of NYC is -73.7997, and the longitude is 40.6408.

This is transposed: the latitude of NYC is about 41, and the longitude about -74. Eg: ([ref](https://www.latlong.net/place/new-york-city-ny-usa-1848.html))

In the lets plot docs example, and in a notebook I've run locally, the example with the data above plots NYC (and Singapore) in the right places on a geographic map. So it would appear that geom_livemap has the aesthetics flipped, treating latitude as longitude and vice versa.

**Comment by mikemac-n0** [comment]
Thank you for the quick response. I'm not sure where I got this notion, but I'd actually come to think that `geom_livemap` was looking for aesthetics called "lat" and "lon", instead of "x" and "y", which makes more sense in the ggplot context.

The `geom_livemap` docs above don't mention `x` and `y` -- that may be intentional -- if eg we regard `geom_livemap` as a value-added version of `geom_point` -- but might you consider adding this to those docs? Updating the NYC/Singapore eg would also be helpful. I'd be happy to contribute a PR if you like. Thanks.

**Comment by alshan** [comment]
> The geom_livemap docs above don't mention x and y -- that may be intentional

No, this was not intentional, x & y should be certainly mentioned. 
The main function of `geom_livemap` is to provide an interactive basemap layer but you are right, it can optionally add scatter ontop and thus understands all aesthetics of `geom_point()`.

Please feel free to fix those issues, this is always welcome.

**Comment by alshan** [comment]
@mikemac-n0 Oh, I forgot, go ahead and please close it.
