### ISSUE TITLE
Make `segment` geometry better suited for graphs visualization.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#572]
Currently, segment connects to points without taking in account the shape of points.

If the shape of an end-point (or a graph vertex) has significant dimensions, then for example, segment arrow heads become trimmed in this notebook: [Pushkin](https://datalore.jetbrains.com/view/notebook/DyD2CLrAbpfO3FMtg6QuhT)

<img width="43" alt="image" src="https://user-images.githubusercontent.com/4430922/179271168-3c59aeab-63ec-46a3-87cf-b6ccb03147a6.png">

**Comment by OLarionova-HORIS** [comment]
Aesthetics to adjust start/end coordinates: `size_start, size_end, stroke_start, stroke_end`.
segment: https://github.com/JetBrains/lets-plot/commit/0b42d45a05f21cb5aecc06afcaf4864fb5e4d4b8 + https://github.com/JetBrains/lets-plot/commit/1b5c4220bce9e587a554fce7968e96d0c762d64c (on livemap)
curve: https://github.com/JetBrains/lets-plot/commit/b63f2b5642730b7b29b929cf3e7e272d40d4af6e
