### ISSUE TITLE
Tooltip: different formats for same aesthetic Y

### ISSUE THREAD

**Issue by OLarionova-HORIS** [JetBrains/lets-plot#579]
boxplot example - values in outlier tooltips are formatted in the exponential notation:
<img width="575" alt="Screenshot 2022-08-02 at 12 34 43" src="https://user-images.githubusercontent.com/46743085/182345463-5a8edfa4-cc00-4862-8abc-815aa4d558c2.png">

Simplified:
```
data = {
    "alphabet": ["a","a","b","a","a","a","b","b","b","a","a","a"],
    "coeff": [
        0.9898989898989898, 0.98989898989899, 0.9871794871794872,
        0.9916666666666667, 0.9882352941176471, 0.9947368421052631,
        0.9916666666666667, 0.9882352941176471, 0.9947368421052631,
        0.9916666666666667, 0.9882352941176471, 0.9947368421052631
     ]
}
ggplot(data) + geom_boxplot(aes("alphabet", "coeff"))
```

**Comment by alshan** [comment]
![image](https://user-images.githubusercontent.com/4430922/194414155-46040056-f77b-4eec-922f-929576ffc699.png)
Probably related. (formatting_axes_etc.ipynb)
