### ISSUE TITLE
No arm64 manylinux wheels

### ISSUE THREAD

**Issue by rchui** [JetBrains/lets-plot#581]
There are arm64 MaoOS wheels. There is also x86_64/amd64 manylinux, MacOS, and Windows wheels. However, there are no arm64 manylinux wheels.

**Comment by alshan** [comment]
We'll take a look, thank you!

**Comment by alshan** [comment]
Hi @rchui,  
Unfortunately, we don't have an ARM-baed hardware setup.  As ARM was perceived rather exotic (maybe wrongly) we didn't really dig into a crosscompiler-involved wheel building for the arm64 manylinux target.  

Do you build Python wheels? Would appreciate an advice.

**Comment by rchui** [comment]
@alshan When I build python wheels I usually use this: https://github.com/pypa/cibuildwheel running GH actions. I'm unfamiliar with how this particular library is built and tested.

**Comment by alshan** [comment]
@rchui Could you try [2.5.0rc1](https://pypi.org/project/lets-plot/2.5.0rc1/)? It includes arm64 manylinux wheels.
