### ISSUE TITLE
Unclear size unit of `width` and `positionDodge(width = ?)`

### ISSUE THREAD

**Issue by CommanderTvis** [JetBrains/lets-plot#589]
We can't understand size units, minimal and maximum values of `width` aesthetic and `width` option in `positionDodge`.

Size units in lets-plot are completely undocumented, so the only way of changing sizes is trial and error.

**Comment by alshan** [comment]
Throughout Lets-plot/ggplot2 API `width` and `height` are relative values where the actual width or height in pix will depend on "data resolution" (i.e. minimal distance between data-point) along correspondent axis. 

Typically, it is in range 0..1.

Certainly need to make it more clear in the docs.

**Comment by ASmirnov-HORIS** [comment]
Solved in [#315e95f](https://github.com/JetBrains/lets-plot/commit/315e95f75761d456a50bc0ec8b0747524dc0d7fb) and [#75c8830](https://github.com/JetBrains/lets-plot/commit/75c8830612b4812dc89655af7c3afd0a45f5227c).
