### ISSUE TITLE
question:how to use lets-plot in compose for desktop?

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/lets-plot#593]
hello, how to use lets-plot in compose for desktop?

**Comment by alshan** [comment]
As compose for desktop supports [embedding of Swing components](https://blog.jetbrains.com/kotlin/2021/02/jetpack-compose-for-desktop-milestone-3-released/#Embedding_Swing_components_in_Compose_for_Desktop_compositions) , you can try to use a plot Swing component available in lets-plot. 
For example - `DefaultPlotPanelBatik` which extends `JPanel`.

Here is an example of using the `DefaultPlotPanelBatik` in a regular Java Swing application: 
https://github.com/alshan/lets-plot-mini-apps/blob/15fe3e02bb8d646d78704e986238a6735634b415/jvm-swing-batik-app/src/main/kotlin/Main.kt#L145

**Comment by changhexuefei** [comment]
Thanks，this helped me
