### ISSUE TITLE
Add png and jpeg support to ggsave

### ISSUE THREAD

**Issue by schakalakka** [JetBrains/lets-plot#596]
It seems that ggsave in [lets-plot-kotlin](https://github.com/JetBrains/lets-plot-kotlin#export) supports more file formats like png and jpeg. Is there a specific problem with the python version for not supporting these formats?

**Comment by alshan** [comment]
Yes, it turned out to be not a trivial task in Python so we put it away for a while.

**Comment by schakalakka** [comment]
I understand. A workaround I am using right now is the cairosvg package. 

```python
from cairosvg import svg2png
...
p = ggplot(..) + ...
ggsave(p, filename='mysvg.svg', ...)
svg2png(url='mysvg.svg', write_to='mypng.png')
```

For anyone who is interested in saving the plots as png files.

**Comment by alshan** [comment]
Looks good! 
One possible issue might be their LGPLv3 license. Its copyleft-type license and we possibly are not allowed to bundle CairoSVG with Lets-Plot or even just hardcode a dependency on CairoSVG. But this need to be checked.

**Comment by schakalakka** [comment]
I am no legal expert but [it seems ](https://softwareengineering.stackexchange.com/questions/141847/how-does-using-a-lgpl-gem-affect-my-mit-licensed-application) that it does not affect your license if you use the library as it is.

**Comment by alshan** [comment]
I've ask our legal dept for clarification. I hope you are right.

**Comment by alshan** [comment]
They said that we can use CairoSVG but we shouldn't install it by default and instead should prompt user to install CairoSVG himself when required.

**Comment by alshan** [comment]
Done (PNG only) in [v3.1.0](https://github.com/JetBrains/lets-plot#other-new-features-and-improvements).

@schakalakka , thanks for tipoff )
