### ISSUE TITLE
Rendering is broken inside Databricks with DBR 11.x and higher - potential fix included

### ISSUE THREAD

**Issue by fwetdb** [JetBrains/lets-plot#602]
Hello,

lets-plot used to work on Databricks with DBR 10.x (cluster version) and lower and we have customers who love and use it.

However, with DBR 11.x the auto-renderer breaks because it detects the wrong display type.
To fix this, customers have to explicitly do `LetsPlot.setup_html(isolated_frame=True)` because `isolated_frame` is auto-detected to be False. IMO most likely as part of `_detect_isolated_frame`.

Databricks can be detected e.g. via `"databricks" in str(os.environ)` which might be added to https://github1s.com/JetBrains/lets-plot/blob/HEAD/python-package/lets_plot/frontend_context/_html_contexts.py#L68-L69 or similar.

What do you think?

**Comment by alshan** [comment]
Sure, we can do it. 
But what about  DBR 10.x and lower? Will this solution still be compatible with  those versions?

**Comment by fwetdb** [comment]
Great and thank you for quickly getting back @alshan !
It will be compatible because `isolated_frame=True` is always the right setting for Databricks - both below 10.x and above 11.x

**Comment by alshan** [comment]
@fwetdb I've pushed your proposal to master : https://github.com/JetBrains/lets-plot/commit/429e19aa541719b562c3f143f1387850cccad2c2

Luckily we are expecting the next release in few days so the fix is coming really soon.

**Comment by fwetdb** [comment]
That's great! The customers will really appreciate your fast fix around that!

**Comment by alshan** [comment]
Hi @fwetdb , could you verify that the fix works? Lets-Plot [v2.5.0](https://github.com/JetBrains/lets-plot/releases/tag/v2.5.0) is out.

**Comment by fwetdb** [comment]
Hi @alshan Thank you for the reach out and the fast release. I verified that the fix worked as intended.
