### ISSUE TITLE
plot alignment not working with ggbunch

### ISSUE THREAD

**Issue by egayer** [JetBrains/lets-plot#603]
Following the tutorial "ggbunch with Lets-Plot" on the Lets-Plot Usage Guide, and setting scale X limits manually I still can't align plots in the example below. Is it because of the format of the Y axis in that example, or setting scale X manually should align plots anyway ?

```
dataex={'x':np.linspace(0,100,51), 'y1':np.random.rand(51)*10,'y2':np.random.rand(51)*1e7}

p1=ggplot(dataex, aes(x='x',y='y1'))+geom_point()
p2=ggplot(dataex, aes(x='x',y='y2'))+geom_bar(stat='identity')

scale_x = scale_x_continuous(limits=[0, 100])
bunch = GGBunch()
bunch.add_plot(p1 + scale_x, 0, 0)
bunch.add_plot(p2 + scale_x, 0, 400)
```
<img width="478" alt="Screen Shot 2022-09-25 at 22 18 16" src="https://user-images.githubusercontent.com/14859142/192163480-b51cd979-87aa-4139-a363-d2b4ddfc6bac.png">

**Comment by alshan** [comment]
> Is it because of the format of the Y axis in that example,

Yes, Lets-Plot only allows you to manage outer size of plot. Thus if labels on Y-axis have different width than inner areas of plots are not aligned. 

Depending on your needs you can try following workarounds: 
- Use marginal plots: https://lets-plot.org/pages/charts.html#marginal-icon-marginal-plots 
- Customize Y-axis label formatting: https://lets-plot.org/pages/formats.html 
- Move origin of `p1` in your example to the right and decrease it's horizontal size accordingly

In the coming Lets-Plot release we will also provide a way to adjust label margins. This could work as well.

**Comment by egayer** [comment]
Dear @alshan, 
thank you very much for your help. Unfortunately, none of the 3 solutions seems to produce a proper grid of plots (or subplots).

Would it be possible to provide a function such as `plt.subplot in Matplotlib` or `geom.subplot_grid from gadfly (Julia)` ?

Here for example is the result with Y-axis formatting, where we can see that the plots are still not aligned.

Thanks

![Screenshot 2022-09-29 at 11 41 59 AM](https://user-images.githubusercontent.com/14859142/192999905-2b4d8f92-0877-499e-9d60-458f92691255.png)

**Comment by alshan** [comment]
> none of the 3 solutions seems to produce a proper grid of plots (or subplots).
Now the 4th solution (adjustable label margins) is also available in [v2.5.0](https://github.com/JetBrains/lets-plot/releases/tag/v2.5.0)

Those solutions are for the purpose of aligning of left and right margins of plotting areas of two plots.

Now, to align the grid inside plotting areas you have to set same "limits" (sometimes also same "extend") for the x-axis on both plots.

**Comment by egayer** [comment]
isn't it what `scale_x = scale_x_continuous(limits=[0, 100])` does ? forcing the two plots to go from 0 to 100 on the x-axis since I would like to align them vertically ?

**Comment by alshan** [comment]
> isn't it what scale_x = scale_x_continuous(limits=[0, 100]) does ?

That's right. It doesn't work quite well in this example because lets-plot expands limits by a half of the bar at each end. Thus the effective limits on histogram are slightly different. (not sure now if this is an expected behavior).

As a workaround we can set our limits a bit bigger then the span of the data: [-5, 105].

Moreover, if we choose to use a nicer formatting, we also have to use a monospaced font-family for labels on y-axis.

```
scale_y_font_mono = theme(axis_text_y=element_text(family="Courier"))
scale_x = scale_x_continuous(limits=[-5, 105], expand=[0,0])
scale_y = scale_y_continuous(format=" >10,.0f")
bunch = GGBunch()
bunch.add_plot(p1 + scale_x + scale_y + scale_y_font_mono, 0, 0)
bunch.add_plot(p2 + scale_x + scale_y + scale_y_font_mono, 0, 400)
```

![image](https://user-images.githubusercontent.com/4430922/193376723-e1705d20-8a4a-455e-afaf-2fc5fed7cd68.png)

**Comment by egayer** [comment]
Thanks a lot for your help @alshan. I applied this workaround with 3 complicated plots and it is working just fine (on version 2.5 though, not 2.4).

I still think that it would be a real plus if Lets-plot allowed to make subplots in an easier way (especially in order to keep the default font on ticks).

I hope you guys will include such a function in the coming versions.

**Comment by alshan** [comment]
I agree, there should be an easier way to achieve alignment.

Yet, looking at [subplots](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplots.html#) the grid is largely out of alignment. Sometimes it is aligned accidentally, just because plots a of the same type. 

Am I missing something?

**Comment by egayer** [comment]
I am really not an expert in the way Matplotlib does its things. However I never experienced misalignment of the axes (or ticks) using `subplots` especially with the `sharex` or `sharey` arguments (even when not using these arguments and only specifying the `xlim` or `xlim` i. e.  the x or y extents). 

What do you mean by "the grid being largely out of alignment using subplots" ?

As for a similar function with Lets-plot, I wouldn't dare advise you how to do it ;) I mentioned `subplots` because from the point of view the user,  it is an easy way to divide a canvas into a grid in which we can organize plots (sharing x or y axes). A little bit easier than specifying the positions of the plots like it is the case in `ggbunch` for example. Of course it is always possible to make a function using `ggbunch` like the function `pair` in the example notebook of Viridis color scales: (https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/f-22c/colors_viridis.ipynb), but I feel like there is a more efficient way to implement subplots.

**Comment by alshan** [comment]
You are right, parameters `sharex` or `sharey` do indeed align grid/ticks.

**Comment by alshan** [comment]
See [gggrid() in v3.1.0](https://github.com/JetBrains/lets-plot#gggrid).
