### ISSUE TITLE
Issues that appear when using the lets-plot library in pycharm

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/lets-plot#614]
When I use the lets-plot library in python, I get the following error: import lets_plot_kotlin_bridge
ImportError: DLL load failed: The specified module could not be found.
![image](https://user-images.githubusercontent.com/19502034/195534366-e6fc1c3e-7a52-4806-8d3d-f10b50b4f60d.png)

**Comment by alshan** [comment]
Most likely you don't have mingw toolchain installed on your Windows system. 
See [Installation | prerequisites](https://lets-plot.org/)

You can also check out [#118](https://github.com/JetBrains/lets-plot/issues/118) and [other](https://github.com/JetBrains/lets-plot/issues?q=ImportError%3A+DLL+load+failed) issues discussing the same problem.
