### ISSUE TITLE
y axis wrong in stacked barplot

### ISSUE THREAD

**Issue by XinLi0111** [JetBrains/lets-plot#617]
![image](https://user-images.githubusercontent.com/31495943/196156108-3817d685-39a4-4787-a8ed-17681c29756f.png)

```
ggplot(rscu_df) + ggsize(700,300)+ \
    geom_bar(aes(fill='Fill',x='AA',y='RSCU'),
             stat="identity",
             show_legend=False,
             tooltips=layer_tooltips().line('@|@Codon').line('RSCU|@RSCU'))+\
    theme_classic()+xlab('')
```

**Comment by alshan** [comment]
Most likely you need to convert your "RSCU" values to numbers.

**Comment by XinLi0111** [comment]
Yes, you are right, thanks for your help. 

I love lets-plot, its more easier than seanborn. Thanks for you guys effort.
