### ISSUE TITLE
Layout: uneven left/right, top/bottom plot margins

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#625]
```
p = ( ggplot()
 + geom_point(aes(x=[1, 2], y=[1, 3]), size=7)
 + theme_bw()    
 + flavor_darcula()
 + theme(axis="blank")
)
```
![image](https://user-images.githubusercontent.com/4430922/199818014-29771e88-aba9-4413-a16d-e766c1c411a5.png)

Expected: equal margins on all 4 sides.

----

```
p + coord_fixed() + ggsize(300, 500)
```
![image](https://user-images.githubusercontent.com/4430922/199818426-7489be5c-c81d-4dac-a6ac-b0856c0e3487.png)

Expected: equal left/right margins and equal top/bottom margins.

**Comment by OLarionova-HORIS** [comment]
Solution of the problem:
if there are no labels on the axis (title and for ticks), we need to add the same margin (as for the opposite side).
PR: https://github.com/JetBrains/lets-plot/pull/632
