### ISSUE TITLE
Precision error in gradient

### ISSUE THREAD

**Issue by gnefedev** [JetBrains/lets-plot#634]
I plot tiles and lets plot interpret one of existed values as NaN

Code:
```
var plt = letsPlot(
    mapOf(
        "x" to listOf(
            "first",
            "first",
            "second",
            "third",
            "third"
        ),
        "y" to listOf(
            "18",
            "21",
            "21",
            "18",
            "21",
        ),
        "z" to listOf(
            3.5264934876244764E-7,
            0.0974772170888232,
            0.1116666955828674,
            2.58687631451427E-5,
            0.07896070396295593
        )
    )
)
plt += geomTile(
    width = tileFillWidth,
    height = tileFillHeight
) {
    this.x = "x"
    this.y = "y"
    this.fill = "z"
}
plt += scaleFillGradientN(
    colors = listOf(
        "#DFFADC", "#C9F5D3", "#B3F2CF",
        "#9AEBCD", "#80DCCC", "#6DC8D2",
        "#61B7DB", "#5C97DB", "#5A7CD6",
        "#6060C7", "#674BB3", "#693799",
        "#6A277B", "#671D60", "#611347",
    ),
    naValue = Color.BLACK.toHexColor()
)
println(ObjectMapper().writeValueAsString(plt.toSpec()))

writeFile(Paths.get("tmp/reproduce.svg"), plt)
```

<details> 
  <summary>Specification as Json</summary>
{
  "mapping": {},
  "data": {
    "x": [
      "first",
      "first",
      "second",
      "third",
      "third"
    ],
    "y": [
      "18",
      "21",
      "21",
      "18",
      "21"
    ],
    "z": [
      3.5264934876244764E-7,
      0.0974772170888232,
      0.1116666955828674,
      2.58687631451427E-5,
      0.07896070396295593
    ]
  },
  "kind": "plot",
  "scales": [
    {
      "aesthetic": "fill",
      "scale_mapper_kind": "color_gradientn",
      "na_value": "#000000",
      "colors": [
        "#DFFADC",
        "#C9F5D3",
        "#B3F2CF",
        "#9AEBCD",
        "#80DCCC",
        "#6DC8D2",
        "#61B7DB",
        "#5C97DB",
        "#5A7CD6",
        "#6060C7",
        "#674BB3",
        "#693799",
        "#6A277B",
        "#671D60",
        "#611347"
      ]
    }
  ],
  "layers": [
    {
      "mapping": {
        "x": "x",
        "y": "y",
        "fill": "z"
      },
      "stat": "identity",
      "width": 0.95,
      "position": "identity",
      "geom": "tile",
      "height": 0.95
    }
  ]
}
</details>

I expected no black tiles.

I found the [source](https://github.com/JetBrains/lets-plot/blob/1d578631eed076328d2556596fdf2340e14236ce/plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/scale/provider/ColorGradientnMapperProvider.kt#L85) of this behaviour: because of double precision error upper end of the range is not the same as the max value of data. This code divide double by int and multiply it again, in general, it will not be the same as an original.

**Comment by alshan** [comment]
After the fix (left - 1st case, right - 2nd case):

![image](https://user-images.githubusercontent.com/4430922/204683494-059519e7-04eb-40c4-bf22-c1fbf7f6da75.png)
