### ISSUE TITLE
Support for more map projections

### ISSUE THREAD

**Issue by wang-boyu** [JetBrains/lets-plot#635]
Thanks for your work on this amazing project!

I got a question about the `coord_map()` that uses Mercator projection, which is a conformal one that preserves shapes. There are many other [map projections](https://en.wikipedia.org/wiki/Map_projection) with different properties that could be useful in different situations as well. Is there any plan to support more map projections?

**Comment by alshan** [comment]
Hi!
We definitely are going to support more projections in `coord_map()`.

However, as for static maps (in contrast to interactive maps), you can create a map using any projection, as long as it is supported by GeoPandas. 
All you need is to specify EPSG code of your CRS via the `use_crs` parameter.
You will find the schematic in this demo: [map_use_crs.ipynb](https://nbviewer.org/github/JetBrains/lets-plot-docs/blob/master/source/examples/cookbook/map_use_crs.ipynb).

Happy mapping)

**Comment by wang-boyu** [comment]
Thanks for the reply! The `use_crs` parameter is very helpful.

Unfortunately it doesn't really work as expected when an equivalent projection is used. I suppose it's because `coord_map()` only supports Mercator projection?

For example with the following code

```python
from IPython.display import display
from lets_plot import *
from lets_plot.geo_data import *
LetsPlot.setup_html(no_js=True)

country = geocode_countries(['US']).inc_res().get_boundaries()
country.set_crs(epsg=6933, inplace=True)
display(country.crs)
(
    ggplot()
    + geom_map(aes(fill='found name'), data=country, use_crs=country.crs, color='black')
    + xlim(-0.0014, -0.0007)
    + ylim(0.00017, 0.0004)
)
```

I get this result

<img width="594" alt="Screenshot 2022-11-22 at 8 37 01 PM" src="https://user-images.githubusercontent.com/10785873/203453776-74cfe390-a653-4b9f-be90-abc112de158a.png">

while expecting something like this (reference: [link](https://residentmario.github.io/geoplot/user_guide/Working_with_Projections.html))

![](https://residentmario.github.io/geoplot/_images/user_guide_Working_with_Projections_5_1.png)

**Comment by alshan** [comment]
I'm not sure how EPSG:6933 projection should look like. However, judging from your link, you wanted to use [Albers Equal Area](https://epsg.io/9822-method) projection which is EPSG:9822. Try to use this code. 

But you are right, `use_crs` parameter might be insufficient in many cases because straight lines will stay straight when they should be bent.

**Comment by alshan** [comment]
Looks weird ) 
Try to use `to_crs()`, AFAIK `set_crs()` doesn't transform the geometries to a new CRS.

Actually, if just for plotting, you don't need either of them. Simply add `use_crs="espg:9822"` to `geom_map()`.

Pls, don't close this issue as yet.

**Comment by wang-boyu** [comment]
Oh `set_crs()` was used because the GeoDataFrame `country` returned from `geocode_countries(['US']).inc_res().get_boundaries()` doesn't have a valid crs. Upgrading lets-plot from `2.5.0` to `2.5.1` solved the problem.

So in `2.5.1` with the following code:

```python
from IPython.display import display
from lets_plot import *
from lets_plot.geo_data import *
LetsPlot.setup_html(no_js=True)

country = geocode_countries(['US']).inc_res().get_boundaries()
(
    ggplot()
    + geom_map(aes(fill='found name'), data=country, use_crs="epsg:9822", color='black')
)
```

I get

<img width="588" alt="Screenshot 2022-11-23 at 10 54 39 AM" src="https://user-images.githubusercontent.com/10785873/203591105-a31b282d-3332-44a6-8fe5-40b22cba40a4.png">

that looks even more weird : )

For Italy it seems to be fine:

```python
italy = geocode_countries('italy').inc_res().get_boundaries()

ggplot() + geom_map(data=italy, use_crs="epsg:9822", color='black')
```

<img width="430" alt="Screenshot 2022-11-23 at 10 58 53 AM" src="https://user-images.githubusercontent.com/10785873/203592062-670be5c6-da41-46c5-b6d9-c3f7af49213c.png">

But it is at a much smaller scale.

**Comment by alshan** [comment]
Not that weird if you imagine the north pole somewhere is the center of the plot.
'US' includes polygons which are too far away from its mainland polygon.
Let's take just 48 US contiguous states:
```
geocode_states().countries('US-48').inc_res().get_boundaries()
```
Like in this demo: [geocoding_level_state_us.ipynb](https://nbviewer.org/github/JetBrains/lets-plot-docs/blob/master/source/examples/basics/geocoding/geocoding_level_state_us.ipynb)

**Comment by wang-boyu** [comment]
You're right! This makes sense.

Here is the result:

```python
from IPython.display import display
from lets_plot import *
from lets_plot.geo_data import *
LetsPlot.setup_html(no_js=True)

states = geocode_states().countries('US-48').inc_res().get_boundaries()
(
    ggplot()
    + geom_map(data=states, use_crs="epsg:9822", color='black')
)
```

<img width="375" alt="Screenshot 2022-11-23 at 3 48 41 PM" src="https://user-images.githubusercontent.com/10785873/203643436-919a58f1-a4d4-4edf-99e8-ca9155c48a97.png">

It's getting close to what I need, and will probably work with some manual rotations of the plot using image manipulation software.

**Comment by alshan** [comment]
It seems "epsg:9822" won't work for us, we need to find a projection suited specifically for US lon/lat ranges.

**Comment by wang-boyu** [comment]
I got it! Following the advice from [here](https://gis.stackexchange.com/a/141588) there is an equal area projection for the US: [ESRI:102003](https://epsg.io/102003)

Now it is working as expected:

```python
from IPython.display import display
from lets_plot import *
from lets_plot.geo_data import *
LetsPlot.setup_html(no_js=True)

states = geocode_states().countries('US-48').inc_res().get_boundaries()
(
    ggplot()
    + geom_map(data=states, use_crs="ESRI:102003", color='black')
)
```

<img width="596" alt="Screenshot 2022-11-23 at 7 21 06 PM" src="https://user-images.githubusercontent.com/10785873/203667616-622e4755-07d0-479a-b07d-94ab3d4a6f48.png">

Thank you so much!
