### ISSUE TITLE
geom_line weird results when swapping x and y

### ISSUE THREAD

**Issue by egayer** [JetBrains/lets-plot#647]
I have hard time understanding the results I get with` geom_line()` in this example:

The following gives the expected and correct result. 
```
ex1={'aa':[1,2,3,4,5,6,7,8,9], 'bb':[21,3,4,56,7,89,1,32,98]}
ggplot(ex1, aes(x='aa', y='bb'))+ geom_line()  
```

But when swapping X and Y it does not give the expected and correct result. Am I missing something ? 
```
ggplot(ex1, aes(x='bb', y='aa'))+ geom_line()
```

thanks

**Comment by alshan** [comment]
`geom_line()` reordres x-values, try to use [`geom_path()`](https://lets-plot.org/pages/api/lets_plot.geom_path.html).

**Comment by egayer** [comment]
OK !!! gotcha ! sorry my bad, yeah `geom_path()` does the trick
thanks @alshan

**Comment by alshan** [comment]
No problem :)
