### ISSUE TITLE
Groups not sorted similarly when using facets

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#679]
Example:

```python
data = {
    'x': [0, 0, 1, 1, 0, 0, 1, 1],
    'f': ['A', 'B', 'B', 'A', 'B', 'A', 'A', 'B'],
    'g': ['X', 'X', 'X', 'X', 'Y', 'Y', 'Y', 'Y'],
}
ggplot(data) + \
    geom_bar(aes(x='x', fill='f')) + \
    facet_grid(x='g')
```

Result:

<img src="https://user-images.githubusercontent.com/26162403/216393943-4d5c54f4-68d2-4909-b865-140eb7c38329.png" width="600"></img>

Expected (as in ggplot2):

<img src="https://user-images.githubusercontent.com/26162403/216394186-e16e43c5-4376-4d8f-9c48-fb64c58d1cf5.png" width="600"></img>

---

The case isn't connected with any specific position type, e.g. the same problem comes up for the following plot:

```python
ggplot(data) + \
    geom_bar(aes(x='x', fill='f'), position='dodge') + \
    facet_grid(x='g')
```

<img src="https://user-images.githubusercontent.com/26162403/216394662-cd57408e-ded8-479a-9d96-7a285164ceba.png" width="600"></img>

**Comment by alshan** [comment]
Fixed in [v3.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#320---2023-05-09)
