### ISSUE TITLE
"Variable not found" error in ggmarginal

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#681]
Code:

```python
ggplot({'x': [], 'y': []}, aes('x', 'y')) + \
    geom_point() + \
    ggmarginal("t", layer=geom_histogram())
```

Result:

`Variable not found: '..density..'. Variables in data frame: ['x', 'y']`

But:

- the library should work with empty data and
- shouldn't complain about `'..density..'` when current stat is `'..count..'`

**Comment by IKupriyanov-HORIS** [comment]
This code snippet also doesn't work because of this issue:
```python
from lets_plot import *
LetsPlot.setup_html()

ggplot(data={'x': [1, 2], 'y': [1, 2]}) + \
    geom_smooth(aes('x', 'y'), tooltips=layer_tooltips().line('@..se..'))
```

Result:
`'Variable not found: '..se..'. Variables in data frame: ['y', '..ymin..', '..ymax..', 'x']'`
