### ISSUE TITLE
`lets-plot` not working with `poetry`

### ISSUE THREAD

**Issue by erdirstats** [JetBrains/lets-plot#690]
Thanks for the package! As an R user, this looks so nice :)

I am trying to use `lets-plot` within a `poetry` project, in Windows. I can install `lets-plot` using `poetry add lets-plot` but, when I try to import it using `from lets-plot import *`, it doesn't work because the MinGW toolchain is needed (as the docs mention). The problem I have is that I am not being able to install the MinGW toolchain using `poetry`. From what I understand, it can be done only through `conda`, but I need a solution within `poetry`. Any possibility to add support for `poetry`? Would making the MinGW toolchain package available on PyPi solve the problem for me? Apparently, `poetry` uses PyPi to add packages.

**Comment by VDovidaytis-HORIS** [comment]
Hello! Thanks for reporting this issue!

Will be fixed with the next release.

**Comment by VDovidaytis-HORIS** [comment]
Hi, @erdirstats!

We have released a release candidate in which Windows packages no longer require additional tools to run. I checked the installation and import of the library in my poetry installation - I did not find any problems. Could you, please, try in your environment:

`pip install lets-plot==3.1.0rc1`

**Comment by erdirstats** [comment]
Hi @VDovidaytis-HORIS.

It works!! Played a bit with some plots and everything seems to work well. I will try to use it at some work projects in the next weeks.

Thank you very much!!

**Comment by VDovidaytis-HORIS** [comment]
> Will this be included in the next release?

Of course. The new release is coming soon.

**Comment by erdirstats** [comment]
I just tried it out. It works very well! Thank you!

**Comment by VDovidaytis-HORIS** [comment]
Fixed with [v3.1.0](https://github.com/JetBrains/lets-plot/releases/tag/v3.1.0).
