### ISSUE TITLE
"newline" doesn't work in legend' texts.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#726]
```
val dat = mapOf(
    "x" to listOf(1, 2, 3),
    "cat" to listOf("a", "b", "c"),
)
val p = letsPlot(dat)

p + geomPoint(size = 8) {
    x = "x"
    color = "cat"
} + scaleColorDiscrete(name="line1 \n line2",
    limits = dat["cat"],
    labels = listOf(
        "a \n my a-category"
    )
)

```

![image](https://user-images.githubusercontent.com/4430922/226990624-e0f1338f-ca20-4d2c-b72b-60d6e7de4040.png)

**Comment by alshan** [comment]
see discussion : https://github.com/JetBrains/lets-plot-kotlin/discussions/167#discussioncomment-5394063

**Comment by OLarionova-HORIS** [comment]
Added: https://github.com/JetBrains/lets-plot/commit/de3ee14366c20697e7ec0dcf4caed2ea30fabb07
Example: [docs/f-23b/legend_text_multiline.ipynb](https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-23b/legend_text_multiline.ipynb)
