### ISSUE TITLE
line, path: support `size` aesthetic

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#734]
from [discussion](https://github.com/JetBrains/lets-plot/discussions/611#discussioncomment-5361403)

> -4- I am having trouble trying to plot a line (or path) with evolving width along the line. When specifying size='size values' in aes(), geom_line() and geom_path() only apply one value for the line width. I did use geom_segment() as a workaround but it is not as good as the result from ggplot2's geom_line() (and scale_linewidth()).

**Comment by alshan** [comment]
Variadic size/color support added in 4.0.0: https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-23c/aes_size_color_variadic_lines.ipynb

cc @egayer

**Comment by egayer** [comment]
Awesome ! thank you !
