### ISSUE TITLE
Support for marker rotation

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#736]
from [discussion](https://github.com/JetBrains/lets-plot/discussions/611#discussioncomment-5361403)

> -3- Support for marker rotation like Matplotlib in the plt.plot() function (https://stackoverflow.com/questions/23345565/is-it-possible-to-control-matplotlib-marker-orientation)

**Comment by RYangazov** [comment]
Fixed via 312562563be9a323f7f1f8d58b6df03aa029a467 and 89daf2cee2c05e1eb9fec8f377f176d381420b7b

**Comment by alshan** [comment]
@egayer see v4.3.3

**Comment by egayer** [comment]
Awesome ! thanks for the heads up ;) 
As I didn't see the new release on the website, I was wondering if the 4.3.3 was "stable"  but I couldn't wait to upgrade :)) and it works perfectly ! Can't wait to see the change log to see all the other new features !

**Comment by alshan** [comment]
[v4.3.3](https://github.com/JetBrains/lets-plot/releases/tag/v4.3.3) was a maintenance release fixing very annoying issue: 
> Undesired vertical scroller when displaying `gggrid()` in Jupyter notebook.

The only new feature there is "marker rotation" really ) You've requested it a while ago.
