### ISSUE TITLE
`geom_segment()` doesn't take into account the `alpha` 

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#748]
See [discussion](https://github.com/JetBrains/lets-plot/discussions/611#discussioncomment-5361403)

> -3- I am having some trouble with geom_segment() which doesn't take into account the alpha value with the version 3.1. I didn't test it with earlier versions but I tested the same dataset with geom_point()  and alpha is well taken into account. Should I open an issue on geom_segment()?

**Comment by egayer** [comment]
thank you !
