### ISSUE TITLE
Support for stat_function

### ISSUE THREAD

**Issue by breandan** [JetBrains/lets-plot#75]
Would be convenient for plotting functions using a lambda syntax.

cf. https://ggplot2.tidyverse.org/reference/stat_function.html

**Comment by alshan** [comment]
https://ggplot2.tidyverse.org/reference/geom_function.html

**Comment by alshan** [comment]
Added `geom_function()`  in 4.0.0 : https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-23c/geom_function.ipynb
