### ISSUE TITLE
geom_livemap doesn't work well with gggrid

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/lets-plot#750]
When I build a plot with two livemaps on a gggrid only one map is displayed and the plot is oriented vertically.

Code:
```python
from lets_plot import *
LetsPlot.setup_html()
from lets_plot.geo_data import *

gggrid(
    [
        ggplot() + geom_livemap() + geom_map(color='red', map=geocode_states('texas')), 
        ggplot() + geom_livemap() + geom_map(color='red', map=geocode_states('ny'))
    ]
)
```

![image](https://user-images.githubusercontent.com/14200189/229214704-f9f33fb6-7c96-4e12-9b25-6e76a54d3204.png)

Without the `geom_livemap()` the result is what I expected:
![image](https://user-images.githubusercontent.com/14200189/229212295-8efdeaa0-245a-4d86-b91e-524b2e44f8b1.png)

**Comment by alshan** [comment]
After fixing:
![image](https://user-images.githubusercontent.com/4430922/234987195-812e5f71-3c22-4489-b7e3-101a1d984333.png)
