### ISSUE TITLE
`geom_pointrange()`: 'size' aesthetic shouldn't affect line width

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#751]
Example:

```python
ggplot() + geom_pointrange(x=0, ymin=0, ymax=2, y=1, size=10)
```

Output:

<img src="https://user-images.githubusercontent.com/26162403/229518244-03f0c6f4-90b5-4bbd-8bb9-3b797ff30267.png" width="400"></img>

Expected output:

<img src="https://user-images.githubusercontent.com/26162403/229518407-48834642-74da-414a-9cb8-d03cb3a28a70.png" width="400"></img>

**Comment by OLarionova-HORIS** [comment]
Fix via https://github.com/JetBrains/lets-plot/commit/cc4c05bb112b8f155d67c26bcda046e488ed57dd
