### ISSUE TITLE
`geom_boxplot()` doesn't apply `alpha` to outliers

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/lets-plot#754]
```python
import numpy as np
from lets_plot import *
LetsPlot.setup_html()
n = 100
np.random.seed(42)
x = np.random.choice(['a', 'b', 'c'], size=n)
y = np.random.normal(size=n)
ggplot({'x': x, 'y': y}, aes(x='x', y='y')) + \
    geom_boxplot(alpha=0.2)
```
![image](https://user-images.githubusercontent.com/14200189/230177251-3a0e217f-eedb-46e8-bb4b-f76feb16b1b4.png)

**Comment by alshan** [comment]
My guess, on boxplot (as well as on barchart, area, polygons etc.) alpha is only applied to "fill".

**Comment by IKupriyanov-HORIS** [comment]
ggplot2 also applies alpha to outliers:
![image](https://user-images.githubusercontent.com/14200189/230216891-ad89d1e4-1ffb-4893-aee5-84bd41f84bdb.png)

**Comment by alshan** [comment]
Outliers appearance is also controlled by additional parameters `outlier_[color,fill,shape,size]`.
In this vein, we could add two more parameters: `outlier_alpha, outlier_stroke`.
