### ISSUE TITLE
Display chart in vscode

### ISSUE THREAD

**Issue by Boadzie** [JetBrains/lets-plot#758]
It is possible to display the charts in vscode or use it in a dashboard with tools like panel or streamlit?

**Comment by alshan** [comment]
If these tools are providing IPython API and are supporting HTML + JS (or at least SVG) outputs, then its likely that Lets-Plot charts can be displayed in VSCode.

**Comment by Boadzie** [comment]
Ok cool. I wanted to use it in Shiny Python

**Comment by alshan** [comment]
https://github.com/randyzwitch/streamlit-letsplot
