### ISSUE TITLE
Customizing the legend manually.

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot#774]
At the moment, the legends are based on mappngs/scales. Beyond that, however, it would be nice to be able to create a legend completely manually, without being tied to other elements of the plot.

For example, I can build the next plot:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/49092338/236195163-ff43ed2a-c48a-4287-b580-ad734138c18d.png">

And I would like to add to it a legend like
```
<blue line> "A"
<red point> "B"
```

I can trick lets-plot the following way:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/49092338/236195752-7cfd6621-2138-4e14-b570-11e99ad2b76e.png">

However it doesn't work well for other aesthetic attributes, so I would like to have a complete customization of the legend, regardless of data/layers/mapping/scales, etc.

**Comment by zaleslaw** [comment]
@alshan we recognized that we really need this feature to implement series feature, we added a few weeks ago candlestick chart, and in some cases it looks sad without series support.

Could you please make the priority higher?

**Comment by alshan** [comment]
Available in [v4.4.0](https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-440).
