### ISSUE TITLE
`ggsave()` doesn't save `geom_raster()` layer to a file

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/lets-plot#778]
Code:
```python
from lets_plot import *
from IPython.display import SVG

LetsPlot.setup_html()

data = {
    "x": [ -1.0, 1.0, -1.0, 1.0 ],
    "y": [ -1.0, -1.0, 1.0, 1.0 ],
    "z": [ 0.024, 0.094, 0.094, 0.024 ]
}
p = ggplot(data) + \
    geom_raster(aes(x='x', y='y', fill='z'), data=data) + \
    geom_point(aes(x='x', y='y'), size=5, data=data) + \
    scale_fill_gradient(low="#54278f", high="#f2f0f7")

print("Plot")
p.show()

print("Image")
plot_filename = ggsave(p, 'issue_ggsave_raster.svg')
display(SVG(plot_filename))
```

Result:
![image](https://user-images.githubusercontent.com/14200189/236532623-9d4e9ea5-b035-4ef4-93f5-23bd8a58bed3.png)

**Comment by alshan** [comment]
There is no "portable" RGB encoder: https://github.com/JetBrains/lets-plot/blob/fa86a9c643a4b50c2638315973277231b38d22d3/plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/PlotSvgExportPortable.kt#L20

Also `geom_imshow` should have the same ggsaving problem.

**Comment by alshan** [comment]
Same issue when ggsaving `geom_imshow` (i.e. empty plot).
