### ISSUE TITLE
Palettes support for discrete scales

### ISSUE THREAD

**Issue by IKupriyanov-HORIS** [JetBrains/lets-plot#79]
Allow to use palettes with discrete scales. 

```scale_color_discrete(palette='BuGn')```

or:

```scale_color_brewer(palette='Blues', discrete=True)```

**Comment by alshan** [comment]
@IKupriyanov-HORIS I'm not sure what is this issue about.

Sequential brewer palettes are intended primarily for continuous data series but can be used with categorical data series as well:

```
scale_color_brewer(type='seq', palette='BuGn')
scale_color_brewer(type='seq', palette='Blues')
```
