### ISSUE TITLE
geom_density2d: support weight aesthetic

### ISSUE THREAD

**Issue by ASmirnov-HORIS** [JetBrains/lets-plot#791]
By analogy with the same aesthetic for `geom_bin2d()`.

Also, see similar [issue in ggplot2](https://github.com/tidyverse/ggplot2/issues/79) and corresponding [discussion on stackoverflow](https://stackoverflow.com/questions/13530028/ggplot2-2d-density-weights).

**Comment by alshan** [comment]
https://forum.datalore-plot.jetbrains-boston.com/t/weighted-density2d/328/1
