### ISSUE TITLE
Pie Chart Labels Example throws runtime error

### ISSUE THREAD

**Issue by fierg** [JetBrains/lets-plot#799]
I was looking for some Kotlin examples for including labels of relative percentage values of the values in a pie chart.
Finally i found some in the lets-plot:lets-plot-kotlin-jvm-4.2.0.jar in the layerLabels Class file.

The Example listed there is
```
Configure annotations (for pie chart). Defines the content and format for displaying the value.
Examples

val data = mapOf("name" to listOf("a", "b", "c", "d", "b"), "value" to listOf(40, 90, 10, 50, 20))
letsPlot(data) +
     geomPie(
         size = 15, hole = 0.2,
         labels = layerLabels("..proppct..").format("..proppct..", "{.1f}%").size(15)
     ) { fill = asDiscrete("name", orderBy = "..count.."); weight = "value" }
```

But when i try to run this, i get a runtime exception of

```
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
Element type "text" must be followed by either attribute specifications, ">" or "/>".

	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
```

Could you please fix the example or can anyone tell me how to get the labels in the pie chart working on kotlin? Any help is appreciated.

**Comment by alshan** [comment]
Hi, try to use the latest releases of [Lets-Plot](https://github.com/JetBrains/lets-plot/releases) and [Lets-Plot Kotlin API](https://github.com/JetBrains/lets-plot-kotlin/releases).

IMO the easiest way to run this particular demo is to checkout the [lets-plot-mini-apps](https://github.com/alshan/lets-plot-mini-apps) from Github and replace [here](https://github.com/alshan/lets-plot-mini-apps/blob/90044e250cdaf22120885305c8e2cf139bc098ba/jvm-swing-batik-app/src/main/kotlin/Main.kt#L23) the 'density' example with the pie plot code mentioned above.

**Comment by alshan** [comment]
More info on pies: https://lets-plot.org/kotlin/-lets--plot--kotlin/org.jetbrains.letsPlot.geom/geom-pie/index.html

**Comment by fierg** [comment]
Yes, using version 4.4.1 of lets-plot-koltin-jvm resolved the issue. Thanks!
