### ISSUE TITLE
geom_crossbar aesthetics take 'middle' argument insteadof 'y'

### ISSUE THREAD

**Issue by schakalakka** [JetBrains/lets-plot#804]
As opposed to ggplot2 the geom_crossbar aesthetics takes the arguments x, *middle*, ymin, ymax, ...

in ggplot2 it is x, *y*, ymin, ymax, ...

Why the difference of *y* and *middle* between lets-plot and ggplot2? 

In contrast the geom_errorbar does not have the middle arguemtn, but y instead. The same for ggplot2.

**Comment by alshan** [comment]
You are absolutely right. Definitely should be aes y for the midline.
