### ISSUE TITLE
symmetrical log or symbol scale

### ISSUE THREAD

**Issue by egayer** [JetBrains/lets-plot#819]
Hi, 

I need to plot positive and negative values in the same plot, with a log scale, using Lets-Plot. Of course this is mathematically impossible, but Matploltlib makes it possible thanks to an option called `symlog`.

Matplotlib transforms the data to be plotted using `SymmetricalLogTransform ` (in `Matplotlib.scale`, which keeps linear progression close to 0) and then manages the markers and labels.

The function is easy to access and works well to transform the data. This is what I'm using at the moment, but then, when plotting them using Lets-Plot I'm having trouble working with the markers and labels. The transformation bring the data to a linear scale and ticks and labels need to be generated "manually" since Lets-Plot cannot generate the right labels (10^2, 10^3, etc.).

So, I'm wondering if it's possible to implement the `symlog` scale in Lets-Plot, or if there's a trick already available for better managing markers and labels in that particular case.

Several people have implemented this function for ggplot2 (e.g. https://gist.github.com/davidtedfordholt/3e6ed189c58af941069991aef79b45a9) or for Matlab (https://www.mathworks.com/matlabcentral/fileexchange/57902-symlog) if that helps.

Here is a quick example to illustrate:

```
import numpy as np
from matplotlib.scale import SymmetricalLogTransform
from lets_plot import *

x_data = np.array([1, 2, 3, 5, 7, 8])
y_data = np.array([0, 1, 590, -20000, 4000000, -30])

# Create an instance of SymmetricalLogTransform
symlog_transform = SymmetricalLogTransform(base=10, linthresh=1, linscale=1)

# Apply the transformation to 'x' and 'y' data
transformed_y = symlog_transform.transform(np.array(y_data))

# Manually transform and create ticks and labels
listelabel=[-100000, -10000, -1000, -100, 0, 100, 1000, 10000, 100000, 1000000, 10000000]
listelabelSTR=[str(x) for x in listelabel]
listelabelval=symlog_transform.transform(listelabel)


# Create a DataFrame with the transformed data
transformed_data = {'x': x_data, 'y': transformed_y}

# Create a scatter plot with the transformed data
p = ggplot(transformed_data) + geom_point(aes(x='x', y='y'))+scale_y_continuous(breaks=listelabelval, labels=listelabelSTR)
p.show()
```

**Comment by alshan** [comment]
Hi @egayer , please check out symlog in v4.1.0: https://github.com/JetBrains/lets-plot#scale-transformations-log2-and-symlog

**Comment by egayer** [comment]
Awesome ! (sorry I did not answer earlier, I got locked out with 2FA problems ! :)))
