### ISSUE TITLE
Add `stat_sum()` (`geom_count()` in original version)

### ISSUE THREAD

**Issue by jdanbrown** [JetBrains/lets-plot#821]
- https://ggplot2.tidyverse.org/reference/geom_count.html
- https://plotnine.readthedocs.io/en/stable/generated/plotnine.geoms.geom_count.html

**Comment by alshan** [comment]
We've added statistic "sum": https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-23c/stat_sum.ipynb

`stat_sum()` is coming soon as well, but I have reservations about `geom_count()`: there is no such "geom" for starters, and its name clashes with [`stat_count()`](https://ggplot2.tidyverse.org/reference/geom_bar.html) which is something entirely different.

I guess we are going to leave `geom_count()` out.

**Comment by jdanbrown** [comment]
> We've added statistic "sum": https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-23c/stat_sum.ipynb

Thank you!

> stat_sum() is coming soon as well, but I have reservations about geom_count(): there is no such "geom" for starters, and its name clashes with [stat_count()](https://ggplot2.tidyverse.org/reference/geom_bar.html) which is something entirely different.
>
> I guess we are going to leave geom_count() out.

Oh, is your goal for (rough) compatibility with the api of ggplot2 in R, or not? plotnine achieves a pretty high amount of compatibility with R ggplot2 — to the degree that I can search stackoverflow for ggplot stuff in R and then transcribe it almost always directly back into ggplot — and it's really great from a usability and approachability perspective!

I personally think the ergonomics of ggplot2 in R are pretty great, and carbon-copying them would be far from a bad idea in api design. :)

**Comment by alshan** [comment]
Fine, we've squeezed `geom_count()` to the recent bugfix v4.0.1, thanks to your feedback :)
https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-23d/geom_count.ipynb

**Comment by jdanbrown** [comment]
🎉 Thank you! Looking forward to it!
