### ISSUE TITLE
theme_void() equivalent

### ISSUE THREAD

**Issue by Nikita-Pavlenko** [JetBrains/lets-plot#830]
For pie charts, for example, we does not need background, axis and the other things except of chart itself.

Currently this could be done with 
```
themeClassic() + theme(axis="blank")
```

but it would be great to have ggplot analog of theme_void()

**Comment by OLarionova-HORIS** [comment]
Added: https://github.com/JetBrains/lets-plot/pull/833

**Comment by alshan** [comment]
Added in 4.0.0, soon in Kotlin API.

**Comment by alshan** [comment]
In LPK 4.4.2 : https://nbviewer.org/github/JetBrains/lets-plot-kotlin/blob/master/docs/examples/jupyter-notebooks/f-4.4.2/theme_void.ipynb

Unfortunately at the moment `themeVoid()` is not fully compatible with "flavors":  https://github.com/JetBrains/lets-plot/issues/858
