### ISSUE TITLE
geom_blank equivalent

### ISSUE THREAD

**Issue by Nikita-Pavlenko** [JetBrains/lets-plot#831]
In a very special case when we are using  lets-plot library for no-code visualization, where the charts are created by using UI editor, it could happens that user simply erased all settings and than, lets-plot shows the red sign "no layers in plot"
![image](https://github.com/JetBrains/lets-plot/assets/47867313/d76cd0b8-f441-4519-82bd-a46dce5c9f70)

Sometimes it is really good to show some blank state like here:
https://ggplot2.tidyverse.org/reference/geom_blank.html

**Comment by alshan** [comment]
Added to Python : [commit](https://github.com/JetBrains/lets-plot/commit/00b3691865411878fc7b4c4fc96075dda0790269).
ToDo: LPK
