### ISSUE TITLE
Support for dpi parameter in `ggsave()`

### ISSUE THREAD

**Issue by Zaf4** [JetBrains/lets-plot#839]
Currently, there is no support for **dpi** parameter in `ggsave()` . This comes handy when saving to png and it is present in the R version of ggplot.

**Comment by IKupriyanov-HORIS** [comment]
Hi! Could you please describe your use case, how would you use the DPI parameter? What exactly should this parameter affect (set meta info in a PNG file, image resolution, plot size)? We have the `scale` parameter that works in a similar way. Can this parameter work in your cases?
Thank you!

**Comment by Zaf4** [comment]
Hi,

DPI is for resolution. You're right `scale` works in a very similar way. Using pixels makes more sense of course. But in some cases, mostly for printing, people have to use inches or centimeters for dimensions which are then converted to pixels according to given DPI parameter. This eliminates the need for manual calculation to satisfy those requirements. Here are the [ggplot2](https://github.com/tidyverse/ggplot2/blob/4f05313b5e3cbfe71c2d3b9e9183780d66439843/R/save.R) and [matplotlib](https://github.com/matplotlib/matplotlib/blob/f533687dc14a2715650a29fc017180103e527f9e/lib/matplotlib/backends/backend_cairo.py#L440) implementation for reference.

So, using DPI also somewhat necessitates the use of dimensions in terms of inches, centimeters etc., In terms of conversion, **1 pixel = 1/96th of an inch** or **1 point = 1/72nd of an inch** ([source](https://accessibility.psu.edu/legibility/fontsize/#:~:text=PowerPoint-,Points%20vs.,Therefore%2016px%20%3D%2012pt.)). Addition of cm, inch could also help people export vector images with the desired sizes too.

In a sense, when the dimensions are provided, they should override `scale` and be converted into pixels for both vector images and png images. For png images, DPI parameter is also required for resolution in such cases. Default value for `dpi` in matplotlib and ggplot2 are 72 and 300, respectively.

Hope this helps!

**Comment by IKupriyanov-HORIS** [comment]
This helps a lot. Thank you!

**Comment by IKupriyanov-HORIS** [comment]
More details on how DPI and size work in matplotlib:
![image](https://github.com/JetBrains/lets-plot/assets/14200189/a4331ca0-5837-46a2-a2c0-433e9c71777a)

[Source](https://stackoverflow.com/a/47639545)

**Comment by alshan** [comment]
Hi @Zaf4 , @egayer 
Currently, one point is not well understood: the effects observed in matplotlib when the plot size is constant and DPI is varied. Specifically, the sizes of plot elements (font size, line width, etc.) are scaled up with increasing DPI, as shown in @IKupriyanov-HORIS's post above. Is this the desired behavior?

**Comment by Zaf4** [comment]
> Specifically, the sizes of plot elements (font size, line width, etc.) are scaled up with increasing DPI

That's one of things I don't like about matplotlib. I think DPI should not change the size of plot elements at all and higher `figsize` should not result in proportionally smaller plot elements. DPI should only effect the resolution of raster images like `scale`. 

Basically, size parameters such as cm, inch should effect pdf, svg dimensions and dpi should dictate the raster image resolution.

**Comment by IKupriyanov-HORIS** [comment]
Fixed in `v4.3.1`

See [demo](https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-24b/param_dpi.ipynb).

**Comment by egayer** [comment]
once again, great job ;) thanks you guys, it works perfectly !
