### ISSUE TITLE
Tooltip on vertical bar shapes: the `main` tip view is out of place.

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#84]
The spout of "supp" tip view should be pointing to the middle point.

Alternatively "supp" tip view in this example could have no spout at all and be just floating nearby. 

![image](https://user-images.githubusercontent.com/4430922/74569685-fe3ef580-4f48-11ea-98ab-ae90bb65e4a4.png)

See [error_bars.ipynb](https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/error_bars.ipynb)

**Comment by IKupriyanov-HORIS** [comment]
Fixed
