### ISSUE TITLE
bar-plot: do not draw bar border adjacent to the axis

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#845]
Otherwise bar sometimes looks rather like a rectangle:

<img width="163" alt="image" src="https://github.com/JetBrains/lets-plot/assets/4430922/ccddd65b-a47c-4d93-b9cb-e5eca91f3676">

**Comment by alshan** [comment]
![image](https://github.com/JetBrains/lets-plot/assets/4430922/017aaac1-c01d-4457-a278-94a4a061ab94)

**Comment by IKupriyanov-HORIS** [comment]
Fixed via https://github.com/JetBrains/lets-plot/commit/7badb80a3dff5fb4fba4e0686c6e08ddadb4da05
