### ISSUE TITLE
problem with log10 axis ticks formatting and legend overflow

### ISSUE THREAD

**Issue by Zaf4** [JetBrains/lets-plot#846]
Increasing the plot size from ` ggsize(400,300)` to  `ggsize(800,600)` leads to addition of ticks that are not integer powers of 10.  As you can see in the second plot it adds ticks for values which corresponds to the **10 to the power of n+0.5**.

Additionally, when setting manual limits (`xlim()`  `ylim()`), legend **overflows** out of the plot which is visible in both plots below.

```
ax3 = (ggplot(qfitm,aes(x='t',y='value',color='case'))+
    geom_point(size=3,data=durm)+
    geom_line()+
    ggsize(400,300)+
    scale_y_log10()+ylim(0.7,100000)+
    scale_x_log10()+xlim(0.7,10000)+
    theme_classic()+
    scale_color_viridis()
    )
ax3
```
![image](https://github.com/JetBrains/lets-plot/assets/36370013/8b22672d-478f-427b-a67a-b641118d0a77)

```
ax3 = (ggplot(qfitm,aes(x='t',y='value',color='case'))+
    geom_point(size=3,data=durm)+
    geom_line()+
    ggsize(800,600)+
    scale_y_log10()+ylim(0.7,100000)+
    scale_x_log10()+xlim(0.7,10000)+
    theme_classic()+
    scale_color_viridis()
    )
ax3
```
![image](https://github.com/JetBrains/lets-plot/assets/36370013/d3515aaf-70fa-4b32-962b-b9cc79338530)

**Comment by alshan** [comment]
Hi, you can correct ticks by defining desired scale 'breaks' manually:
```
scale_x_log10(breaks=[1, 10, 100, 1000, 10000])
```

----

The legend overflow situation is more concerning. Could you add the following theme settings to your plot:
```
theme(plot_background=element_rect(color="red", size=4), legend_background=element_rect(color="blue", size=4))
```
and then describe the result?

If you can save plot to a SVG file and attach it to this issue that would help as well.

**Comment by Zaf4** [comment]
Thanks for the suggestion on manual breaks. However, I think breaks, by default, should only be 10^n in log10 scale.

As for the overflow, here is the result:

![sample](https://github.com/JetBrains/lets-plot/assets/36370013/87cd137b-c605-4052-8df5-a1b8c6fb93de)

**Comment by alshan** [comment]
This is an issue with our plot layout. It seems we do not handle tick labels overflow correctly (the label "10,000" goes beyond the axis length) which results in a partially trimmed legend.

As a workaround you can
a) increase upper limit along the x-axis: `+ xlim(None, 10400)` 
b) reposition the legend, put it ontop, below or inside the plot

**Comment by Zaf4** [comment]
Thank you for your suggestions. I just wanted to point out the problems.

**Comment by alshan** [comment]
Appreciate it, I've submitted 2 related issues: 

- https://github.com/JetBrains/lets-plot/issues/850
- https://github.com/JetBrains/lets-plot/issues/851
