### ISSUE TITLE
Tooltip text NULL

### ISSUE THREAD

**Issue by alshan** [JetBrains/lets-plot#85]
Lets do `n/a`

![image](https://user-images.githubusercontent.com/4430922/74570567-a4d7c600-4f4a-11ea-8672-03a4c1f04884.png)
See last example in  [geopandas_naturalearth.ipynb](https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/examples/jupyter-notebooks/geopandas_naturalearth.ipynb)

**Comment by IKupriyanov-HORIS** [comment]
Fixed
