### ISSUE TITLE
Default border color in v4.0.0

### ISSUE THREAD

**Issue by Zaf4** [JetBrains/lets-plot#853]
In the updated version of lets-plot there are some changes default border color of violin and boxplot. Honestly, I just realized this because the plots didn't look as appealing as before. 

I checked .svg files from this and prior version and compared them with ggplot2 (from R). 

_Version 3.2.0_ uses **rgb(0,0,0) (HEX #000000**) as the border color and _v4.0.0_ uses **rgb(71,71,71) (HEX #474747)**. Although moving away from pure black is a good decision, border color for _v4.0.0_ is a bit too light which reduces contrast resulting in less appealing plots. For comparison, I used ggplot2 from R and they use border color of **#333333 (rgb(51, 51, 51))** which is not pure black but maintains great contrast and provides quality plots.

I think using a somewhat darker default border (and line) color can improve plot aesthetics greatly.

I am adding the said svg files.
### v3.2.0
![box_LP_32](https://github.com/JetBrains/lets-plot/assets/36370013/c504c2b7-19a4-429c-905a-c104c3874f1d)

### v4.0.0
![box_LP_40](https://github.com/JetBrains/lets-plot/assets/36370013/e91f139b-0278-484a-991f-88ac26013e16)

### ggplot2 (R)
![Box_gg_R](https://github.com/JetBrains/lets-plot/assets/36370013/68363754-c96f-45de-88fa-d7bab2649834)

**Comment by alshan** [comment]
`+ flavor_high_contrast_light()` could help. It's pure black though.

Another option would be to `+ theme(geom=element_geom(pen='#333333')`  (see "4. Re-assigning Geometry Theme Colors" [here](https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-23c/geom_theme_colors.ipynb)).
However it wont work well with dark flavors.
