### ISSUE TITLE
`stat='count'` does not work as intended in `geom_pie()`

### ISSUE THREAD

**Issue by Zaf4** [JetBrains/lets-plot#862]
Maybe I am wrong about how it should work as I do not work with pie charts in general but take a look at the following case.

```
iris = pd.read_csv(r"https://raw.githubusercontent.com/JetBrains/lets-plot-docs/master/data/iris.csv")

ax = (
    ggplot(iris,aes(slice='species',fill='species'))+
    geom_pie(stat='count')+
    theme_minimal()
)
ax
```

![iris_pie](https://github.com/JetBrains/lets-plot/assets/36370013/f5f994d8-8876-46ca-90d9-bf48ecb162f2)

As the number of the all species are the same (50), `stat='count'` does not work as intended here. Sorry, if this is the intented way and if I am making a mistake.

**Comment by IKupriyanov-HORIS** [comment]
Hi!
If you were expecting to get 3 sectors of the same size, there is a small error - `slice` is the correct aesthetic (it determines the sector size), but you should have mapped it to the stat var `..count..`. This is actually how `geom_pie()` works by default, so your example can be shortened (you don't even need to set the stat parameter):

```python
ggplot(iris, aes(fill='species')) \
    + geom_pie() \
    + theme_void()
```

Explicit mapping for the `slice` aesthetic is usually needed with `stat='identity'`.

There are few demos:
https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-22e/geom_pie.ipynb
https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-23c/geom_pie_stroke_and_spacers.ipynb

**Comment by Zaf4** [comment]
Thank you for the clarification.
