### ISSUE TITLE
How to suppress "sampling_* ... was applied to ... layer" message/warning

### ISSUE THREAD

**Issue by OSuwaidi** [JetBrains/lets-plot#863]
In my Jupyter Notebook, I use `lets_plot` to create the visualizations and deploy them as an interactive web app using `Voila`.

However, my data is huge (> 1 million rows), and for almost every plot generated, the message/warning `sampling_* ... was applied to ... layer` accompanies the plot, even though I am the one assigning the sampling process to each of the plots.

How can I suppress/hide this message to make my web app cleaner?

**Comment by alshan** [comment]
Hi, in v4.0.1 there is new option "plot_message" in `theme()` allowing to suppress plot messages either for the entire notebook or per individual plots. Please check out this demo: 
https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-23d/theme_plot_message.ipynb
