### ISSUE TITLE
How to dynamically layer `.line()` methods against `layer_tooltips()`?

### ISSUE THREAD

**Issue by OSuwaidi** [JetBrains/lets-plot#873]
I am trying to make my `lets-plot` plots more interactive by using Streamlit's widgets to dynamically change the generated plots upon widget interaction.

One such widget was the `st.multiselect()` option that is supposed to dynamically change the kind/number of variables to be shown on a plot's tooltips via the `.line()` method. My first attempt was to initialize a `layer_tooltips()` variable and then chain a bunch of `.line()` methods against it in a _for loop_ depending on how many variables were selected to be displayed, but I was unsuccessful (I tried to chain strings of `.line()` in list comprehension and then use `eval()`).

Any idea on how can I accomplish this?

**Comment by IKupriyanov-HORIS** [comment]
Hi.
I made a simple snippet to show how you to config a plot programmatically. The code doesn't use Streamlit, but I hope the code still gives you an idea of how it can be done.
In brief - `layers_tooltip()` returns a builder, meaning you have to create a builder object and configure it as you want. This object should then be passed to the layer creation function as the `tooltips` argument. You should create a separate builder for each layer.
If this won't work, please, let us see some code so we can help you.

```python
from lets_plot import *
LetsPlot.setup_html()

# input
d = {
    'x': [1, 2, 3, 4, 5, 6],
    'y': [1, 2, 3, 4, 5, 6],
    'c': ['a', 'b', 'c', 'd', 'e', 'f'],
    'g': ['1', '2', '3', '4', '5', '6'],
    's': ['q', 'w', 'e', 'r', 't', 'y']
}

# Enter variables you want to see in a tooltip
vars_for_tooltip = ['c', 'g']


# configuring tooltips and layer
# layer_tooltips() returns a builder object. Each layer needs its own builder.
point_layer_tooltips = layer_tooltips()
for var_name in vars_for_tooltip:
    point_layer_tooltips.line("{}: @{}".format(var_name, var_name))

point_layer = geom_point(tooltips=point_layer_tooltips)

# plot object
p = ggplot(d, aes(x='x', y='y'))

# display a plot
p + point_layer
```
