### ISSUE TITLE
Husl palette equivalent

### ISSUE THREAD

**Issue by Zaf4** [JetBrains/lets-plot#876]
I tried to find the default color palette of R's ggplot (**husl_palette** in seaborn) in lets-plot but I couldn't. It is a great palette for categorical data. So, I think it would be a great addition to lets-plot. 

Here is the link to the seaborn one: https://seaborn.pydata.org/generated/seaborn.husl_palette.html
And this to the R's ggplot: https://scales.r-lib.org/reference/hue_pal.html

FYI, I already tried following existing palettes.
```
diverging = ["BrBG", "PiYG", "PRGn", "PuOr", "RdBu", "RdGy", "RdYlBu", "RdYlGn", "Spectral"]
qualitative = ["Accent", "Dark2", "Paired", "Pastel1", "Pastel2", "Set1", "Set2", "Set3"]
sequential = ["Blues", "BuGn", "BuPu", "GnBu", "Greens", "Greys", "Oranges", "OrRd", "PuBu", "PuBuGn", "PuRd", "Purples", "RdPu", "Reds", "YlGn", "YlGnBu", "YlOrBr", "YlOrRd"]
```

and the viridis ones,
`viridis = ["A","B","C","D","E","turbo","twilight"]`

and none of them looks like ggplot2's default palette.

**Comment by alshan** [comment]
Have you tried "hue" scales? 
https://lets-plot.org/pages/api/lets_plot.scale_color_hue.html

**Comment by Zaf4** [comment]
I tried it after your suggestion. They use the same principle but somehow with the same h,c,l values resulting palettes are very different.

**Comment by Zaf4** [comment]
Here is the R's ggplot default.
![R ](https://github.com/JetBrains/lets-plot/assets/36370013/c87a8c21-d3f9-42a9-8132-037ae7754cf0)
Then, seaborn using 'husl'
![seaborn](https://github.com/JetBrains/lets-plot/assets/36370013/737cb53f-1e7c-483e-b5bf-925a0b409a06)
Lastly, from lets-plot + `scale_fill_hue()` 
![lets_plot](https://github.com/JetBrains/lets-plot/assets/36370013/cd206b0f-3335-40bd-bc75-d4917e4043d8)

Obviously, seaborn and ggplot produce very similar colors. But, lets-plot `scale_hue` produces different set of colors even with the same parameters.

Difference might be scale_hue documentation says " Qualitative color scale with evenly spaced hues for color aesthetic."

While husl_palette says "This function is similar to [hls_palette()](https://seaborn.pydata.org/generated/seaborn.hls_palette.html#seaborn.hls_palette), but it uses a nonlinear color space that is more perceptually uniform."

**Comment by alshan** [comment]
You are right, there is significant difference in colors. Likely this is because lets-plot `scale_hue` uses HSV color space instead of HSL under the hood. Certainly need to be fixed.
