### ISSUE TITLE
How to manually set a colour for a category?

### ISSUE THREAD

**Issue by srooks10** [JetBrains/lets-plot#880]
I want to associate a category with the same colour across different plots. I expect to be able to use `scale_manual_color` and `scale_fill_manual` for that but I don't understand how to associate a category with a colour. The docstrings [1](https://github.com/JetBrains/lets-plot/blob/a2c17961cc52c8a972ddc3a1c50ff9f5fa9bf32f/python-package/lets_plot/plot/scale.py#L187) and [2](https://github.com/JetBrains/lets-plot/blob/a2c17961cc52c8a972ddc3a1c50ff9f5fa9bf32f/python-package/lets_plot/plot/scale.py#L258) mention using a "named vector" for `values`. What is a "named vector" in that context?

According to a Stackoverflow answer one can use a `pandas.Series`. But that is not working for me:

```python
# From: https://stackoverflow.com/a/75795036
import pandas as pd
from lets_plot import *

LetsPlot.setup_html()

data = pd.read_csv(
    "https://raw.githubusercontent.com/JetBrains/lets-plot-docs/master/data/mpg2.csv"
)

p = ggplot(
    data, aes(x="engine horsepower", y="miles per gallon")
) + geom_point(aes(color="origin of car"))

gggrid(
    [
        p
        + scale_color_manual(
            values=pd.Series(
                ["red", "green", "blue"], index=["Asia", "US", "Europe"]
            )
        ),
        p
        + scale_color_manual(
            # swap "Asia" and "US" in the index
            values=pd.Series(
                ["red", "green", "blue"], index=["US", "Asia", "Europe"]
            )
        ),
    ]
)

```
gives: 
![image](https://github.com/JetBrains/lets-plot/assets/836931/a055f50c-05f6-4de4-a784-163c76afb38b)

The colours for Asia and US should be swapped in the right hand side graph but are not.

I'm using lets-plot v4.0.0 on python 3.10 installed from conda-forge on windows.

**Comment by alshan** [comment]
You need to use "limits" parameter to specify the order of the scale breaks:

```
scale_color_manual(
  values=["red", "green", "blue"],
  limits=["Asia", "US", "Europe"]
)
```

`scale_color_manual` the order of scale breaks can be

**Comment by srooks10** [comment]
That works for me, both for `scale_color_manual` and `scale_fill_manual`. Thank you!

May I suggest clarifying the docstrings to reflect this? Because as written, and after reading https://ggplot2-book.org/scales-other.html#sec-scale-manual , I expected `values` to take something like a Python dictionary.

And thanks a lot for lets-plot. It's working really well in combination with polars to explore my data.

**Comment by alshan** [comment]
You are absolutely right. Our cart (docs) before the horse (#882 )

**Comment by alshan** [comment]
Code with named vector (a.k.a. dictionary) should work in [v4.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#added).
