### ISSUE TITLE
Can't create DateTime from instant negative (prior to unix époque)

### ISSUE THREAD

**Issue by egayer** [JetBrains/lets-plot#881]
Hi all, 
I didn't see any post regarding the issue I am facing. (Maybe this one is close to it https://github.com/JetBrains/lets-plot/issues/392).

I am having troubles plotting dates prior to unix epoq and encoded into a pandas dataframe.

The pandas column would be a `dtype: datetime64` and lets-plot returns this error when trying to use it as a x-axis (would be the same on the y-axis) 

`Can't create DateTime from instant -628983360000`

**Comment by IKupriyanov-HORIS** [comment]
Hi!
This bug has been fixed in the latest version - 4.0.1. Which version are you using?

**Comment by egayer** [comment]
Hi @IKupriyanov-HORIS
Guys you are going too fast ! I feel like upgrading to 4.0.0 was yesterday. :)))
I was using the 4.0.0 and I just went to 4.0.1 and now it is working. The bug is fixed indeed ! 
thank you !
