### ISSUE TITLE
Allow export functions to export to a file-like object

### ISSUE THREAD

**Issue by dmoklaf** [JetBrains/lets-plot#885]
The 2 image export functions (export_svg and, export_png) require a "filename" target destination.

However, some use cases don't require the filesystem. E.g., to generate and send back directly a chart PNG to a client from a web server.

It would be very convenient to be able to specify as target, alternatively to a filename, a file-like-object. This is the approach used by pandas (they call usually the argument covering both cases "path", e.g. in DataFrame.to_feather(..., path=..., ...).

This would be easy to implement, as the underlying cairosvg library can handle both of these cases with the same call.

Absent this improvement, the current workaround is to use a temporary file, which lengthens the code and involves an unnecessary write access to the filesystem (use of temp files or not, security, cleanup logic in case of crashes, etc...)

lets_plot 4.0.1
python 3.11.5
macos 13.5.2

**Comment by alshan** [comment]
Hi, added in [v4.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#added) : [example notebook](https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/f-23f/new_export_methods.ipynb).
