### ISSUE TITLE
Please Update Batik to version v1.17

### ISSUE THREAD

**Issue by AdrianAJTang** [JetBrains/lets-plot#887]
Please update to the newer Batik version as v1.16 contains some security problems that are fixed with 1.17.

https://mvnrepository.com/artifact/org.apache.xmlgraphics/batik-codec/1.16

Thanks

**Comment by alshan** [comment]
Done in [v4.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#added).
