### ISSUE TITLE
Flickering during plot downsizing

### ISSUE THREAD

**Issue by Nikita-Pavlenko** [JetBrains/lets-plot#888]
We have a plot created via DefaultPlotComponentProviderBatik.

You can see on the recorder video that upscale works relatively normal and the previous image are displayed until the new one come from render.

But on the downscale we have a different thing with flickering via empty panel, which looks not so good. 

Please, make sizing a little bit smoother. For example, we can show the original image fill the component rect in both cases, in upsizing and downsizing.

![Peek 2023-09-26 13-06](https://github.com/JetBrains/lets-plot/assets/47867313/f6756f3b-7398-49b1-9ad4-eb31c340cafb)

**Comment by alshan** [comment]
In [`PlotPanel`](https://github.com/JetBrains/lets-plot/blob/master/platf-awt/src/jvmMain/kotlin/org/jetbrains/letsPlot/awt/plot/component/PlotPanel.kt) replaced GridBagLayout with BorderLayout, which doesn't seem to get invalidated on downsizing.
However, you can try a different layout manager by overriding 'layout' in a subclass of PlotPanel. Like in  [`MyPlotPanelBatik`](https://github.com/JetBrains/lets-plot/blob/master/demo/plot/src/jvmBatikMain/kotlin/demo/plot/batik/customErrorComponent/MyPlotPanelBatik.kt) demo for example.
