### ISSUE TITLE
geomBar with fill, produces tooltips artefacts

### ISSUE THREAD

**Issue by Nikita-Pavlenko** [JetBrains/lets-plot#895]
When creating a geomBar with position = PosKind.STACK and some fill, and trying to get some tooltips, we are getting artefacts.

![chart 1](https://github.com/JetBrains/lets-plot/assets/47867313/8ead5166-86d1-4d63-a0c1-a749fce4e528)
![chart 2](https://github.com/JetBrains/lets-plot/assets/47867313/903e2b26-b7ff-4c80-bcee-f63c58b86297)

**Comment by IKupriyanov-HORIS** [comment]
Likely related to https://github.com/JetBrains/lets-plot/issues/793

**Comment by alshan** [comment]
Fixed in v4.1.0
