### ISSUE TITLE
ggsave() to .html does not work with special characters

### ISSUE THREAD

**Issue by gregorbaer** [JetBrains/lets-plot#900]
### 🐛 Issue
Plots that are saved with `ggsave()` as .html cannot by default correctly display special characters (e.g. €, ü, ä, ö, etc.). This issue only occurs when saving to .html, not when saving to .svg or other formats, or when displaying the graphs in a notebook.

Manually editing the .html code of the saved plot to include the line `<meta charset="UTF-8">` fixes the display issue.

### 💡 Proposed Solution
Use UTF-8 encoding by default when saving to .html with `ggsave()` (or another encoding which can deal with the special characters).

**Comment by alshan** [comment]
Fixed in v4.1.0
