### ISSUE TITLE
Int DataFrame column names are being converted to float string representation

### ISSUE THREAD

**Issue by kuroski** [JetBrains/lets-plot#901]
Hello, I was working with the following scenario in a notebook.

``` python
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(100, 2))
```

In this example, I have two int columns `0` and `1`.

When trying to plot the DataFrame

``` python
from lets_plot import *
ggplot(df) + geom_point(aes(x="0", y="1"))
```

I am presented with the following error message:

> Variable not found: '0'. Variables in data frame: ['0.0', '1.0']

It seems for some reason, the names are being converted to a float string representation.

![image](https://github.com/JetBrains/lets-plot/assets/1855125/f1a77655-d956-44d8-87d9-18533d4e4266)

**Comment by Zaf4** [comment]
I checked and it's not a problem with **lets_plot**. It's a **pandas** problem. I used the same array and pandas dataframe got errors both in lets_plot and seaborn. But, when you convert the same dataframe to **polars** dataframe, both seaborn and lets_plot works.

```
df_pd = pd.DataFrame(np.random.rand(100, 2))
df_pl = pl.from_pandas(df_pd)
```
### Seaborn Example
![image](https://github.com/JetBrains/lets-plot/assets/36370013/c3046fd8-9143-4ffe-98f4-e44bbcaf2ae7)

### Lets_plot Example
![image](https://github.com/JetBrains/lets-plot/assets/36370013/ef861348-0c5d-46b9-9768-34cf893a5428)

**Comment by alshan** [comment]
Related: #626
