### ISSUE TITLE
Exception label is unresizeble, uncopyable and uncontrollable

### ISSUE THREAD

**Issue by Nikita-Pavlenko** [JetBrains/lets-plot#902]
When we have lets-plot exception with a big text
"IllegalStateException : Can't detect type of pattern 'Let's Talk About Sex (1998)	Drama
One Man's Hero (1999).movieId(mean)' used in string pattern '@{Let's Talk About Sex (1998)	Drama
One Man's Hero (1999).movieId(mean)}'"

The error label on the PlotPanel have a minWidth of 1560, and breakes the layout making it impossible to resize plot area.

Please
1. Make this error label multiline
2. Make it possible for users to copy the error message or even a stacktrace for reporting
3. Set manually the max width to something like 15, to save the layout from explosion
4. Provide a possibility to control it by developers that want to use lets-plot library with swing. Let them to override some "createErrorPanel(t: Throwable) to make it possible to provide our own LAF for errors with reporting and styles"

![image](https://github.com/JetBrains/lets-plot/assets/47867313/a492a3be-b8e1-481c-b046-3a5427539ad6)

**Comment by alshan** [comment]
Done in this fix: 
- A better default "error message" component: multiline, selectable text: [`DefaultErrorMessageComponent`](https://github.com/JetBrains/lets-plot/blob/master/platf-awt/src/jvmMain/kotlin/org/jetbrains/letsPlot/awt/plot/component/DefaultErrorMessageComponent.kt)

- You can plug your own "error message" component by overriding [`createErrorMessageComponent()`](https://github.com/JetBrains/lets-plot/blob/a03f2360a986fe509aa0a08fdf8831217b6d3f11/platf-awt/src/jvmMain/kotlin/org/jetbrains/letsPlot/awt/plot/component/PlotSpecComponentProvider.kt#L89C24-L89C51) in [`PlotSpecComponentProvider`](https://github.com/JetBrains/lets-plot/blob/master/platf-awt/src/jvmMain/kotlin/org/jetbrains/letsPlot/awt/plot/component/PlotSpecComponentProvider.kt)

See example: [`MyErrorMessageComponent`](https://github.com/JetBrains/lets-plot/blob/master/demo/plot/src/jvmBatikMain/kotlin/demo/plot/batik/customErrorComponent/MyErrorMessageComponent.kt).


And BTW, when you are done with your custom "error message" component could you share its code? We'd love to make it a default "error message" component :)

**Comment by Nikita-Pavlenko** [comment]
This is how first draft looks, without UI/UX review:
![Peek 2023-11-14 12-04](https://github.com/JetBrains/lets-plot/assets/47867313/36194b34-0a9d-4ff0-8ebc-62397d5b0617)

**Comment by alshan** [comment]
Looks awesome :)
