### ISSUE TITLE
Cannot find distribution for lets-plot upon installing in Python 3.12

### ISSUE THREAD

**Issue by OSuwaidi** [JetBrains/lets-plot#907]
I have recently upgraded to Python 3.12 given that it's stable enough.

But upon trying to install `lets-plot` via `pip install lets-plot`, I get the following error:

> ERROR: Could not find a version that satisfies the requirement lets-plot (from versions: none)
ERROR: No matching distribution found for lets-plot

**Specs:**
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
System Type:               x64-based PC
Python Version: Python 3.12.0

**Comment by VDovidaytis-HORIS** [comment]
Python 3.12 support added in [v4.1.0](https://github.com/JetBrains/lets-plot/releases/tag/v4.1.0)
