### ISSUE TITLE
Displaying lets_plot in vscode (no notebook)

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [JetBrains/lets-plot#909]
I'm trying to run a lets_plot example in vscode (no notebook), but I can't seem to put it to display the plot within vscode as I can do with other libraries (where it opens on a new tab in vscode). 

Any solution to this without using notebooks (or inline approaches such as # %%)?

**Comment by alshan** [comment]
Please make sure 
- IPython is installed in your env
- You invoke `plot.show()` method.

I'm not sure if VSCode does execute JS code we provide. Maybe not by default, maybe not at all. If so, try using "no JS" option:
```
LetsPlot.setup_html(no_js=True)
```

**Comment by alshan** [comment]
Hi @Rafael-Silva-Oliveira , 
In v4.3.0 we added [`setup_show_ext()`](https://lets-plot.org/python/pages/api/lets_plot.LetsPlot.html#lets_plot.LetsPlot.setup_show_ext) which you can use instead of `setup_html()`to allow plots to be displayed in an external browser window.
