### ISSUE TITLE
Make the jitter in geom_jitter reproducible

### ISSUE THREAD

**Issue by fewerton** [JetBrains/lets-plot#911]
How to make the jitter in geom_jitter reproducible?

In R using ggplot2, one can set a random seed using the set.seed() function before creating the plot. 
In python matplotlib one can use np.random.

But how to ensure the plot is reproducible when adding random noise for the jittering using lets-plot?
Thank you.

**Comment by alshan** [comment]
Seeds added in [v4.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#added).
