### ISSUE TITLE
Incorrect 'plot_background' area (with empty space capture)

### ISSUE THREAD

**Issue by OLarionova-HORIS** [JetBrains/lets-plot#918]
```
from lets_plot import *
LetsPlot.setup_html()

import numpy as np
np.random.seed(42)

data = {'x': np.random.randint(10, size=50)}

ggplot(data, aes(x='x')) + \
    geom_bar() + \
    coord_fixed(0.5) + \
    theme(plot_background=element_rect(size=2, fill='light_grey'))
```

The filled area corresponds to the overall size of the plot:
<img width="50%" alt="Screenshot 2023-11-01 at 13 48 40" src="https://github.com/JetBrains/lets-plot/assets/46743085/5ec9abe8-1f53-4706-9ef7-4ab387b13cd9">

It's more correct not to take the empty space around - use the plotting area with all titles and margins.
The expected result will be like this:
<img width="50%" alt="Screenshot 2023-11-01 at 13 48 25" src="https://github.com/JetBrains/lets-plot/assets/46743085/00cf9b32-e8f0-490a-bcd1-eb10a955e2e9">

**Comment by IKupriyanov-HORIS** [comment]
```python
from lets_plot import *
LetsPlot.setup_html()

margins = theme(plot_margin=40)

p = ggplot() + geom_point(aes(x=[10, 20, 30], y=[0, 10, 20])) + theme(plot_background=element_rect(size=6, fill='light_grey', color='black'))

gggrid([
    p + ggtitle('Default'),
    p + margins + ggtitle('plot_margin=40'),
    p + coord_fixed() + margins + ggtitle('plot_margin=40 + coord_fixed()'),
    p + coord_fixed() + margins + facet_grid(x='x') + ggtitle('plot_margin=40 + facet_grid')
])
```

Before:
![image](https://github.com/JetBrains/lets-plot/assets/14200189/3331bb5f-3f75-4487-acde-db99f54a05f1)


After:
![image](https://github.com/JetBrains/lets-plot/assets/14200189/3b6c155f-c94b-46c5-82f9-47dacfdebcb2)

**Comment by IKupriyanov-HORIS** [comment]
Looks like background should be expanded be the margin.

ggplot2 version for reference:

```r
df <- data.frame(
    x = c(10, 10, 20, 20, 30, 30),
    y = c(1, 10, 2, 8, 3, 5)
)

p = ggplot(df) + 
    geom_point(aes(x=x, y=y)) + 
    theme(
        plot.margin=margin(2, 2, 2, 2, "cm"), 
        panel.background=element_rect(fill='orange'), 
        plot.background=element_rect(fill='grey')
    ) + 
    facet_grid(cols=vars(x)) + 
    ggtitle("Default")
p
```
![image](https://github.com/JetBrains/lets-plot/assets/14200189/e62ee34a-da9e-453e-bad6-9256f3da08e4)

```r
p + coord_fixed() + ggtitle("coord_fixed()")
```
![image](https://github.com/JetBrains/lets-plot/assets/14200189/9c41c8d9-4ff4-4b34-9327-be1c7d267cd4)

**Comment by IKupriyanov-HORIS** [comment]
```python
from lets_plot import *
LetsPlot.setup_html()

margins = theme(plot_margin=[5, 0, 0, 40])

p = ggplot() \
    + geom_point(aes(x=[0, 1, 2], y=[1, 2, 3])) \
    + theme(
        plot_background=element_rect(size=5, fill='light_grey', color='grey'),
        panel_background=element_rect(fill='orange'),
        panel_grid_minor=element_line(),
    )

dump_plot(gggrid([
    p + ggtitle('Default'),
    p + coord_fixed(0.3) + ggtitle('coord_fixed()'),
    p + margins + ggtitle('plot_margin=[5, 0, 0, 40]'),
    p + margins + coord_fixed(0.3) + ggtitle('plot_margin=[5, 0, 0, 40] + coord_fixed()'),
], ncol=2))
```

Result:
![image](https://github.com/JetBrains/lets-plot/assets/14200189/d6195751-7ba5-46fb-9853-31acf84b99b8)
