### ISSUE TITLE
`scale_*_log2()` as a shortcut for `trans='log2'`

### ISSUE THREAD

**Issue by Zaf4** [JetBrains/lets-plot#922]
`scale_x_log2()` and `scale_y_log2()` can be used as shorcuts for  `scale_*_continuous(trans='log2')` on top of #828. This already exists for **log10** on lets_plot and **log2** one is available in ggplot2.

**Comment by alshan** [comment]
Added in [v4.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#added).
