### ISSUE TITLE
Enormous CPU / Time/  Memory consumption on some data

### ISSUE THREAD

**Issue by Nikita-Pavlenko** [JetBrains/lets-plot#932]
This, relatively small and simple data 
1. Consumes 1.5 Gigabytes (GB) memory on trying to create DefaultPlotPanel
2. Takes nearly 2 minutes on relatively fast PC

```
 val rand = java.util.Random()
    val n = 90000
    val data = mapOf<String, Any>(
        "x" to List(n) { "Some average text $it" },
        "y" to List(n) { rand.nextGaussian() }
    )

    val plot = letsPlot() + themeClassic() + geomLine(data = data, showLegend = false, sampling = samplingNone) {
        x = "x"
        y = "y"
    }
```

[Main.zip](https://github.com/JetBrains/lets-plot/files/13364289/Main.zip)

**Comment by alshan** [comment]
The reason for disappointing performance found to be a huge number of ticks and gridlines along the x-axis.
After the fixes you will see significant performance improvement it terms of both, building time and memory consumption.
