### ISSUE TITLE
Mouse hovering and tooltips viewing has low performance on some data

### ISSUE THREAD

**Issue by Nikita-Pavlenko** [JetBrains/lets-plot#933]
`DefaultPlotComponentProviderBatik` requires executor for processing mouse events for showing tooltips.
_Looks like this executor should execute in EDT, at least in all other cases i am getting tons of exceptions._

When moving move over geomLine, we will see huge CPU load on 2000 points, unresponsiveness at 5000, and in >10000 points we can get a 1-2 second freezes.

This is a sample code for testing
```
val rand = java.util.Random()
val n = 5000
val data = mapOf<String, Any>(
        "x" to List(n) { "Some average text $it" },
        "y" to List(n) { rand.nextGaussian() } )

val plot = letsPlot() + themeClassic() + geomLine(data = data, showLegend = false, sampling = samplingNone) {
        x = "x"
        y = "y"
}
```

Probably we can move all the math at least in the background thread, and probably, we should somehow improve the hover detection math for charts with a number of points > 1000.

**Comment by IKupriyanov-HORIS** [comment]
Thats strange. The line geom uses binary search by default (if no scatterplot layers present, like points).
This is my test code:
```kotlin
val n = 25_000
val step = 4 * PI / n
val x = MutableList(n) { "Some average text $it" }
val y = MutableList(n) { sin(it * step) }

val data = mapOf<String, Any>(
        "x" to x,
        "y" to y
    )

val plot = letsPlot() + themeClassic() + geomLine(data = data, showLegend = false, sampling = samplingNone) {
        x = "x"
        y = "y"
}
plot
```

And this is how tooltips work (upper window - Chrome, lower window - Batik):

https://github.com/JetBrains/lets-plot/assets/14200189/0b97a887-ce78-4138-ab7b-175e115e8831

**Comment by Nikita-Pavlenko** [comment]
Sorry. I have checked on different data and both on batik & javafx and everything is ok in separate test project, but extremely slow in IDE. Probably we have some specialities in our batik, i will check this on our side, this is not a problem of lets-plot.
