### ISSUE TITLE
scale manual: behavior with specified `breaks` and `limits` parameters

### ISSUE THREAD

**Issue by OLarionova-HORIS** [JetBrains/lets-plot#934]
Example: 
```
p = ggplot(mpg2.head(32), aes('miles per gallon', 'vehicle weight (lbs.)')) + \
    geom_point(aes(color=as_discrete('number of cylinders')))
p + scale_color_manual(
    values = ["red", "blue", "darkgreen", "orange"],
    breaks = [8, 4, 6, 10],
    limits = [4, 8]
) 
```
Result:
<img width="450" alt="Screenshot 2023-11-20 at 15 31 22" src="https://github.com/JetBrains/lets-plot/assets/46743085/17345068-2508-4fd4-b678-8064108b21e6">

Similar plot using ggplot2:

<img width="500" alt="Screenshot 2023-11-20 at 15 10 54" src="https://github.com/JetBrains/lets-plot/assets/46743085/c2080af5-23cd-41a8-8d19-c645f477b2e3">

The ggplot2 result seems more correct:
 the `values` (colors) correspond to the items specified in the `breaks` parameter.

**Comment by alshan** [comment]
But according to the docs (in both libraries), the "values" is defined as 
> ..the values will be matched in order (usually alphabetical) with the limits of the scale.

Thus, `values` do not neccessarily correspond to `breaks`.

The order in legend seems correct in lets-plot and not correct in ggplot2.

However, what does "usually alphabetical" in docs mean? I.e. "blue" is before "red" alphabetically. Should "blue" be matched before "red"?
