### ISSUE TITLE
How to add space between a plot's y-ticks and its "geom" area to show full y-axis ticks?

### ISSUE THREAD

**Issue by OSuwaidi** [JetBrains/lets-plot#939]
<img src="https://github.com/JetBrains/lets-plot/assets/120381151/829681b0-c088-44fd-8b37-962bc6e0b142" width="500">

As shown in the screenshot above, the y-ticks in my bar plot are truncated.
Here is the code:
`
(ggplot(df_offer.select('offer_name', 'efficiency').sort('efficiency', descending=True).head().sort('efficiency'))
                       + geom_bar(aes(y='offer_name', x='efficiency', fill='efficiency'), stat='identity', orientation='y', legend='blank')
                       + labs(x='efficiency', y='Offer Name',
                              title='Top 5 Offers by efficiency'))
`

When trying to add some whitespace between the y-ticks and the plot via:
`+ theme(axis_text_y=element_text(margin=margin(t=0,r=50,b=0,l=0)))`, I get the following (still truncated text):

<img src="https://github.com/JetBrains/lets-plot/assets/120381151/92fcf871-9590-4ab1-8772-1b62ff8edf25" width="500">

And when trying to use `axis_ticks_y` instead of `axis_text_y`, nothing happens no matter where you add the margins.

How can I show the full text on the y-axis?

**Comment by alshan** [comment]
Hi, this case is unfortunately not covered at the moment.
Couple of workarounds currently I can think of is to 
a) insert line breaks directly into the strings in the "Offer Name" column of your dataset;
b) define shorter labels via `scale_y_discrete(labels=...)`

**Comment by alshan** [comment]
Hi, in [v4.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#added) we've removed limits on labels length and added an option to set such limit explicitly if necessary: [example notebook](https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/f-23f/scale_lablim.ipynb).
