### ISSUE TITLE
Long axis labels getting truncated

### ISSUE THREAD

**Issue by luan-n-nguyen** [JetBrains/lets-plot#946]
Hi,

Is there a way to disable the truncation of long axis labels (see below example plot)?
I've looked through the API docs but couldn't find how to do this.

Luan

![image](https://github.com/JetBrains/lets-plot/assets/125411678/4f35fffe-bd83-4850-81aa-4609d7f0329a)

**Comment by alshan** [comment]
Hi, currently there is no way to disable labels truncation unfortunately.
For now I can only suggest to try to shorten the labels by yourself and pass them to the x-axis via  
```
scale_x_discrete(breaks=..., labels=...)
```

**Comment by alshan** [comment]
Hi, in [v4.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#added) we've removed limits on labels length and added an option to set such limit explicitly if necessary: [example notebook](https://nbviewer.jupyter.org/github/JetBrains/lets-plot/blob/master/docs/f-23f/scale_lablim.ipynb).

**Comment by luan-n-nguyen** [comment]
Perfect thanks a lot!
