### ISSUE TITLE
geom_tile remaing square and not stretching when plot size is rectangular

### ISSUE THREAD

**Issue by luan-n-nguyen** [JetBrains/lets-plot#951]
Hi there,

When i have a rectangular canvas (using `ggsize(500, 250)`, see below example code), the `geom_tile`s remain square.
However, I would like the tiles to stretch widthwise (see second heatmap), which is the behavior found in R's ggplot.

Is there a way to enable this / Will this be a planned feature?

Best regards,
Luan

```
import numpy as np
import pandas as pd
from lets_plot import *

matrix = pd.DataFrame(np.random.rand(10, 10))
matrix.columns.name = "col"
matrix.index.name = "row"

plot_data = matrix.reset_index().melt('row')

p = (
    ggplot(plot_data, aes(y="row", x="col")) +
    geom_tile(aes(fill="value")) +
    theme_bw() +
    ggsize(500, 250)
)
ggsave(p, "/Users/lnguyen/Desktop/plot.png")
```
![image](https://github.com/JetBrains/lets-plot/assets/125411678/ad9488a8-965a-4a71-b008-d24d57f91bc9)

![image](https://github.com/JetBrains/lets-plot/assets/125411678/803ccf40-a98c-4111-ad95-22cda8788656)

**Comment by alshan** [comment]
Hi, by default we use `coord_fixed` for tiles. Try to `+ coord_cartesian()` to override this default.

**Comment by luan-n-nguyen** [comment]
Thank you, that fixed the issue!
