### ISSUE TITLE
`scale_continuous()` fails with non-color aesthetics

### ISSUE THREAD

**Issue by OLarionova-HORIS** [JetBrains/lets-plot#953]
Example:
```
np.random.seed(42)
x = np.random.randint(-5, 5, size=25)

ggplot({'x': x}, aes(x='x')) + geom_histogram(bins=8) + scale_continuous('x', breaks=[-5, -2, 1, 4])
```

Output:
> ERR [SpecTransformBackendUtil] : Internal error: ClassCastException : class kotlin.Double cannot be cast to class org.jetbrains.letsPlot.commons.values.Color
Internal error: ClassCastException : class kotlin.Double cannot be cast to class org.jetbrains.letsPlot.commons.values.Color

**Comment by alshan** [comment]
Fixed in [v4.2.0](https://github.com/JetBrains/lets-plot/blob/master/CHANGELOG.md#added).
