### ISSUE TITLE
Native support for Radar plots as a `LayerSpec` object

### ISSUE THREAD

**Issue by OSuwaidi** [JetBrains/lets-plot#958]
Would love to see [Radar plots](https://en.wikipedia.org/wiki/Radar_chart) being natively supported in the `lets-plot` library to expand the library's richness.

I believe it would be a good addition to be able to visualize datasets with multivariate features against multiple categories!

**Comment by alshan** [comment]
See discussion https://github.com/JetBrains/lets-plot/discussions/952

**Comment by alshan** [comment]
Hi @OSuwaidi , since 4.3.0 radar/spider plots are supported via `coord_polar()` + "flat" option: 
- https://nbviewer.org/github/JetBrains/lets-plot/blob/master/docs/f-24a/coord_polar.ipynb
- https://nbviewer.org/github/JetBrains/lets-plot-docs/blob/master/source/examples/demo/palmer_penguins.ipynb
