### ISSUE TITLE
Problem About the Greece Letters Showing

### ISSUE THREAD

**Issue by richardmkit** [JetBrains/lets-plot#960]
It seems to have some problems to show the Greece letters in the axes and legend. 

File attached.
<img width="430" alt="ggplot" src="https://github.com/JetBrains/lets-plot/assets/153658648/de214cf8-aae8-4e7c-a41f-cb5312f39047">

Wish to get fixed, 👍

**Comment by alshan** [comment]
Hi, we don't support LaTeX  but you can use unicode escaping to show Theta, i.e. : '\u03F4'.

**Comment by alshan** [comment]
Related #861

**Comment by alshan** [comment]
Fixed in [v4.5.0](https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-450)
