### ISSUE TITLE
How to remove whisker horizontal line

### ISSUE THREAD

**Issue by AndreiKingsley** [JetBrains/lets-plot#969]
![image](https://github.com/JetBrains/lets-plot/assets/49092338/55e03a73-0959-442f-86e9-423e48a7dcc3)
I want to plot something like that

**Comment by AndreiKingsley** [comment]
And it's very useful to have that line length adjustment.

**Comment by OLarionova-HORIS** [comment]
`geom_boxplot()` has a `whisker_width` parameter to control this horizontal line.
> whisker_width, default=0.5
> A multiplicative factor applied to the box width to draw horizontal segments on whiskers.

So by default the line is a half the box width. 
And `whisker_width=0` removes the line.

**Comment by AndreiKingsley** [comment]
Oh, hadn't noticed, thanks!
