### ISSUE TITLE
web site's SEO is terrible; impossible to find lets-plot on Google

### ISSUE THREAD

**Issue by HarlanH** [JetBrains/lets-plot#977]
Hi, this is a bit meta, but it's basically impossible to find https://lets-plot.org/ on Google using search terms such as "ggplot2 python" or "grammar of graphics python". Instead, you get plotnine (which is fine, but not as good as lets-plot), and a bunch of links to abandonware for _pages_ before lets-plot shows up. I suspect that some basic SEO techniques, such as use of meta-tags, making sure that keywords such as "ggplot2" and "ggplot" are used repeatedly on the home page, adding links from other reputable domains, etc., would go a long way.

**Comment by alshan** [comment]
Hi, thank you, you are right, it's about time to look into SEO.  Reputable domains are keeping their distance though :)

**Comment by alshan** [comment]
Hi @HarlanH,  so, we have our documentation web site facelifted. 
Note, the landing page is new (https://lets-plot.org/) and the  former home page has moved to https://lets-plot.org/python/.
"ggplot2" and "Grammar of Graphics" are now used on every opportunity and meta-tags were added as you have suggested.
Hope, search engines will pick it up and we'll see better search results soon.

**Comment by HarlanH** [comment]
Nice!! The new home page looks sharp!

**Comment by alshan** [comment]
I believe we've addressed this issue well. Let's hope the situation in Google search results will improve over time as more quality backlinks appear.
