### ISSUE TITLE
Add interactive zoom options

### ISSUE THREAD

**Issue by Episkiliski** [JetBrains/lets-plot#983]
Could you please add the following interactive zoom options in a future development?

- Box zoom
- zoom in
- zoom out
- scroll zoom

Thanks!

**Comment by araichev** [comment]
Zooming by mouse wheel would be nice.

**Comment by alshan** [comment]
Pan, Zoom see [4.5.0](https://github.com/JetBrains/lets-plot?tab=readme-ov-file#what-is-new-in-450)
